### ISSUE TITLE
Implement Repo Recommendations in the Design System

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1000]
<img width="641" alt="Screen Shot 2023-03-13 at 5 53 51 PM" src="https://user-images.githubusercontent.com/5713670/224864659-fb8a8542-d47b-4558-917e-7025610ea133.png">

[[Figma: Repo Recommendations](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=139%3A537&t=B0fmUuiTTS4HUVTm-1)]

**Comment by Deadreyo** [comment]
Do we already have a component for these repo cards? 
![image](https://user-images.githubusercontent.com/52013393/225247561-8e4743e1-ffe9-48b8-a66f-95d80a68f933.png)

**Comment by 0-vortex** [comment]
> Do we already have a component for these repo cards?
> ![image](https://user-images.githubusercontent.com/52013393/225247561-8e4743e1-ffe9-48b8-a66f-95d80a68f933.png)

We have them for sure in https://hot.opensauced.pizza tho not sure about insights 🍕
