### ISSUE TITLE
Bug: Official logos are not being leverage. 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1007]
### Describe the bug

<img width="628" alt="Screen Shot 2023-03-14 at 3 30 52 PM" src="https://user-images.githubusercontent.com/5713670/225156761-a1377dbc-19c7-41a5-9051-5122c81a7644.png">

This PR https://github.com/open-sauced/insights/pull/995 deleted the work ins PR https://github.com/open-sauced/insights/pull/966

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5713670/225156746-2e0eab79-05c0-4a84-af68-37aa6b781dd7.png)

Topic thumbnails should be what appears above. The interest emojis should be different. 

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
```
git checkout -b good-icons-branch 6af4a5572e8fff14ba73d88b63a3a8156ac2efa8
```
