### ISSUE TITLE
Feature: Add context to the Insights Page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1012]
### Type of feature

🍕 Feature

### Current behavior

Today, no one knows what to do on the insights page. We need to add context. 

<img width="1447" alt="Screen Shot 2023-03-15 at 9 37 06 AM" src="https://user-images.githubusercontent.com/5713670/225378509-329b787b-7f87-42ce-899f-2d9a48454f44.png">

### Suggested solution

1. Add Copy "Welcome to your Insights Hub! Here, you can set up pages to view all of your insights or other open source insights in one place."
2. Change Link in Nav to "Insights" instead of "Insights Hub"
3. Header is "Insights"

![Screen Shot 2023-03-15 at 9 36 08 AM](https://user-images.githubusercontent.com/5713670/225379048-86ac090e-b9e0-4201-800c-8ba82f6b6e04.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nworiekingslee** [comment]
<img width="1507" alt="Screenshot 2023-03-15 at 22 59 04" src="https://user-images.githubusercontent.com/55883854/225453458-6ad6f362-0e7a-46de-9d3e-75b169e5a212.png">

@bdougie  I successfully set up the project on my local but couldn't find the 'Insight' page or the link to it on the Nav bar

**Comment by bdougie** [comment]
Click "complete onboarding"

**Comment by nworiekingslee** [comment]
I get a 404 error when I try to complete the onboarding or update my profile

**Comment by nworiekingslee** [comment]
Nevermind, it went through after several tries

**Comment by nworiekingslee** [comment]
<img width="1507" alt="Screenshot 2023-03-15 at 23 27 @bdougie 0" src="https://user-images.githubusercontent.com/55883854/225457547-7eca5333-4be6-4182-8e84-084098cf6ce3.png">

@bdougie is there anything I need to add?

I noticed there's a search on the screenshot you shared in the issue, do you need me to work the search feature as well?

**Comment by bdougie** [comment]
Nope, just the context you added. please open the PR when you have time.

**Comment by nworiekingslee** [comment]
PR created
