### ISSUE TITLE
Bug: Make `DELETE` word stand out in sentence

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1020]
### Describe the bug

<img width="615" alt="delete" src="https://user-images.githubusercontent.com/62995161/225825851-4b4c160a-04f7-43af-9a21-9c6a1b1ef0ba.png">

The word delete should be made bolder or if possible styled to be red

### Steps to reproduce

- Go to insights page
- Create an insight page if you don't have one
- Navigate to edit insights page
- Scroll down and click the delete button
- Read the message

### Affected services

insights.opensauced.pizza

### Platforms

Desktop, Mobile

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by diivi** [comment]
.take
