### ISSUE TITLE
Bug: reports page button text alignment

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1024]
### Describe the bug

<img width="580" alt="reports" src="https://user-images.githubusercontent.com/62995161/225841109-7d3d29be-cc52-495c-9ddd-549f6659fb32.png">

### Steps to reproduce

- Go to reports page

### Affected services

insights.opensauced.pizza

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Pratham-19** [comment]
.take
