### ISSUE TITLE
Bug: highlight overflows outside of modal

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/insights#1031]
### Describe the bug

![image](https://user-images.githubusercontent.com/42211/226362427-6e169d39-939d-4a00-9657-e0cf78718f8f.png)

### Steps to reproduce

Navigate to https://insights.opensauced.pizza/feed/13

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
This probably should be fixed by #999
Will test again after it’s merged 👀
