### ISSUE TITLE
Bug: Updating profile on Insights page results in an error

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/insights#1033]
### Describe the bug

Updating your user settings, e.g. bio, LinkedIn url etc results in an error.

### Steps to reproduce

1. Navigate to your user settings, https://insights.opensauced.pizza/user/settings
2. Add some info you want to update to your profile, e.g. bio, LinkedIn url etc.
3. Click the Update Profile button
4. A toast message appears saying "An error occured!!!"

![CleanShot 2023-03-20 at 22 46 06](https://user-images.githubusercontent.com/833231/226507045-eb9c4e91-d790-4fbe-ab05-4da01c38bdc4.png)

Additional context:
The preflight request appears to run, but then the actual request gives a 404

![CleanShot 2023-03-20 at 22 52 37](https://user-images.githubusercontent.com/833231/226507566-c4b54448-f3f6-4fe6-b14f-bd94587aae6a.png)

Here is the payload response:

```
{"statusCode":404,"message":"Unable to update user","error":"Not Found"}
```

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Other (add additional context)

### Environment

Production

### Additional context

I'm using the Chromium based browser Arc, although.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Thanks for digging into this Nick

**Comment by doaortu** [comment]
Can I take this issue, please? @brandonroberts

**Comment by TAKANOME-DEV** [comment]
Feel free to assign it to yourself, see https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by doaortu** [comment]
.take

**Comment by doaortu** [comment]
Ok, thanks @TAKANOME-DEV , I'm working on it.
