### ISSUE TITLE
Unable to click on the discord and dev link-buttons as Help icon covers them

### ISSUE THREAD

**Issue by parmishh** [open-sauced/insights#1038]
### Describe the bug

Unable to click on the discord and dev link-buttons as Help icon covers them 

Desired state: Should be visible so That it can be clicked.

@bdougie I can help solve this issue I have solved similar issue for Layer5.io repo. I have couple of ideas.
If this issue needs to be solved You can assign me 😊

<img width="960" alt="image" src="https://user-images.githubusercontent.com/91942072/226973479-d4affcfb-417c-40e0-baee-59ea54675dc3.PNG">

https://user-images.githubusercontent.com/91942072/226973666-26bd644d-5f1e-4d3d-8eed-cf0137c2b3a9.mp4

### Steps to reproduce

Can be viewed on site

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Well spotted! Assigned you

**Comment by takanome-dev** [comment]
Closing this one out as it was fixed.
