### ISSUE TITLE
bug: add more spaces between highlights

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/insights#1057]
### Type of feature

🍕 Feature

### Current behavior

![close-edit](https://user-images.githubusercontent.com/79809121/228054621-617454c8-b607-4658-b24b-d62afb4171a1.png)

### Suggested solution

Add more space between highlights.
@open-sauced/triage Thoughts?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by parmishh** [comment]
@TAKANOME-DEV I would like to work on it.

**Comment by TAKANOME-DEV** [comment]
Feel free to take it :+1:

**Comment by shamimbinnur** [comment]
hey, @parmishh are you still on it?

**Comment by parmishh** [comment]
@shamimbinnur the issue is not visible on my device feel free to work on this if its visible on your device
