### ISSUE TITLE
Bug: Insights creation don't use selected repos `(beta)`

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1058]
### Describe the bug

When creating a new insight, The selected repositories are ignored and replaced with a bunch of random repositories 

https://user-images.githubusercontent.com/62995161/228157539-03f55e54-c750-4cd1-a917-d5f7d61cc5a3.mov

### Steps to reproduce

1. Goto insights page https://beta.insights.opensauced.pizza/hub/insights
2. Click on add insights page
3. Select repos and add the page title
4. Click on the create page button and you'll be redirected to the insights home page
5. Edit the same created page 

### Affected services

insights.opensauced.pizza

### Environment

Development, Testing

### Additional context

This bug can only be found in the beta environment

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Is the bug happening during the creation or editing of the page? It's important to understand if the database insert is accurate. Can look into specific insight pages if you give me some IDs 🍕

**Comment by OgDev-01** [comment]
I look closer and found out that for some reason, repo.host_id is not a valid key in the repo object when creating and updating an insights page, and the backend did not guard against creating insights with `id` of `undefined` or `null`
```
 const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/user/insights`, {
      method: "POST",
      headers: {
        "Content-type": "application/json",
        Authorization: `Bearer ${sessionToken}`
      },
      body: JSON.stringify({
        name,
        repos: repos.map((repo) => ({ id: repo.host_id, fullName: repo.full_name })),
        // eslint-disable-next-line
        is_public: isPublic
      })
    });
```

**Comment by 0-vortex** [comment]
That is a known issue, our api uses repo.id similar to github; gitsense was using host_id; however, because you can create insight page repos without having any repos in the database, for creating and editing those pages the public github api is required. Please refer to the unfinished work in the alpha branch for this, I have personally fixed adding insight pages/repos but not fixed editing.

@brandonroberts made some beta changes but i doubt any of the work is finished - you can however take it to beta ❤️

**Comment by OgDev-01** [comment]
> you can however take it to beta ❤️

yeah... Just tested using `repo.id` and it worked as espected 🍕
