### ISSUE TITLE
Bug: logo is missing in header on mobile

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1068]
This was removed in the #1063 fix but I'd like us to keep the logo there.

On beta
![image](https://user-images.githubusercontent.com/5713670/228879803-f2dac716-653d-49f8-a5f1-13881a7743e1.jpeg)

On production

![image](https://user-images.githubusercontent.com/5713670/228879948-2b7e6d2f-b8ab-461f-b108-6129c2cc88b6.png)

**Comment by Pranav-yadav** [comment]
@bdougie 
I would be happy to help w/ this one, provided no one is already implementing it.

**Comment by Pranav-yadav** [comment]
Oops, seems like bot even scans the inline `code` in the comment. We should skip inline-code and code-block in comments.

**Comment by ashutosh887** [comment]
@bdougie Should I work on this?

**Comment by bdougie** [comment]
> @bdougie Should I work on this?

I'd ask @Pranav-yadav who has it assigned. I know it was an error, but you did comment first.

**Comment by Pranav-yadav** [comment]
> I know it was an error, but you did comment first.

Yup. I was waiting for your permission.
Thanks.
Pushing the fix soon.
