### ISSUE TITLE
Feature:  redirected user's back to where they were before authenticating

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1075]
### Type of feature

🍕 Feature

### Current behavior

Users are taken back to the root `"/"` after authenticating which is not an ideal experience 

### Suggested solution

Users should be redirected back to where they were before authenticating

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
@brandonroberts I went through the supabase docs on redirect Url [here](https://supabase.com/docs/guides/auth#redirect-urls-and-wildcards) and understood that the `redirectTo` key can be used to set a redirect Url on signIn. 

But i've tried testing with out current implementation but i doesn’t seem to work as describe in the docs
<img width="710" alt="redirect" src="https://user-images.githubusercontent.com/62995161/231594822-2d326ce2-5f5b-4508-9a55-ed518dbcedf9.png">

Am i missing something?

**Comment by 0-vortex** [comment]
> @brandonroberts I went through the supabase docs on redirect Url [here](https://supabase.com/docs/guides/auth#redirect-urls-and-wildcards) and understood that the `redirectTo` key can be used to set a redirect Url on signIn.
> 
> But i've tried testing with out current implementation but i doesn’t seem to work as describe in the docs <img alt="redirect" width="710" src="https://user-images.githubusercontent.com/62995161/231594822-2d326ce2-5f5b-4508-9a55-ed518dbcedf9.png">
> 
> Am i missing something?

Yes, the supabase docs have changed very much this year, with them generally not mentioning any of the auth changes as breaking. They suggest making wrappers around this now: https://supabase.com/docs/guides/auth#redirect-urls-and-wildcards, while setting different redirect URLs for them to actually work:

<img width="885" alt="Screenshot 2023-04-14 at 11 23 42" src="https://user-images.githubusercontent.com/237133/232004278-a75fec02-241c-4271-8708-ef37ad52b128.png">

With the above being done on both dev and the production database, you should now be able to properly redirect anywhere!
