### ISSUE TITLE
Bug: Copy Link button in Highlights is misaligned

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#1078]
### Describe the bug
![image](https://user-images.githubusercontent.com/52013393/229913050-59d00ad6-52e6-460e-961a-8419089d73a2.png)
![image](https://user-images.githubusercontent.com/52013393/229912700-7349b9ba-3473-4488-a386-485de45a35d2.png)

The button of "copy link" in the options of a highlight is misaligned with the rest.

### Steps to reproduce

.

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by therajatrai** [comment]
@OgDev-01 Can you assign ? I would love to take this issue.

**Comment by OgDev-01** [comment]
> @OgDev-01 Can you assign ? I would love to take this issue.

Sure!, Thanks for accepting to work on this 🍕

**Comment by ozgursar** [comment]
Event though this issue is assigned, It is not fixed for more than a month. Can I work on this If @therajatrai accepts?

**Comment by therajatrai** [comment]
I am working on this and will wrap this as soon as possible.

**Comment by ozgursar** [comment]
Sorry @therajatrai , I started working on it after getting assigned

**Comment by therajatrai** [comment]
Oh okay no problem, actually I got stucked with my exams which made it
late. I'll try to work on another issue 😊
