### ISSUE TITLE
Feature: highlight.new path

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1079]
### Type of feature

🍕 Feature

### Current behavior

We own the [highlight.new](https://highlgiht.new) and got a note from the register. In order to compliant, we linking to the insights page.

## Note from registry

Domain Name | Non Compliant Policy
-- | --
highlight.new | Does not take the user directly into the action generation or content creation flow.

<p style="box-sizing: content-box; letter-spacing: normal; margin: 1em 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: -apple-system, &quot;system-ui&quot;, &quot;segoe ui&quot;, roboto, oxygen, ubuntu, cantarell, &quot;fira sans&quot;, &quot;droid sans&quot;, &quot;helvetica neue&quot;, sans-serif; vertical-align: baseline; display: block; color: rgb(0, 0, 0); orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We would like to clarify that for highlight.new, the policy violation is due to the additional click "Create/Add insight Page" (see image 1) before entering the content creation flow. If the user is brought directly into the creation page screen (see image 2) after login, the website would be compliant.<br style="box-sizing: content-box; letter-spacing: initial;"><br style="box-sizing: content-box; letter-spacing: initial;">Please update your website to be compliant with the above policy.<br style="box-sizing: content-box; letter-spacing: initial;"><br style="box-sizing: content-box; letter-spacing: initial;">If the website is still not compliant in the next 14 days, your domain will be suspended. Suspended domains do not resolve, and cannot be transferred or deleted.<br clear="none" style="box-sizing: content-box; letter-spacing: initial;"><br clear="none" style="box-sizing: content-box; letter-spacing: initial;">Regards,<br clear="none" style="box-sizing: content-box; letter-spacing: initial;">Google Registry</p>Dear Registrant,

Google Registry conducts a weekly analysis of .new domains to verify compliance with our [.new Registration Policies](https://www.registry.google/policies/registration/new/#!/). On April 5, 2023, the following domain that you manage was determined non-compliant with the following policy:

Domain Name 

Non Compliant Policy

highlight.new

Does not take the user directly into the action generation or content creation flow. 

We would like to clarify that for highlight.new, the policy violation is due to the additional click "Create/Add insight Page" (see image 1) before entering the content creation flow. If the user is brought directly into the creation page screen (see image 2) after login, the website would be compliant.

Please update your website to be compliant with the above policy.

If the website is still not compliant in the next 14 days, your domain will be suspended. Suspended domains do not resolve, and cannot be transferred or deleted.

Regards,
Google Registry

### Suggested solution

@getaheaddev need a highlights/new page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
14 days sounds like a deadline

![IMG_2916](https://user-images.githubusercontent.com/237133/230186365-a052f763-4809-4506-96eb-de161e8e8316.png)

**Comment by bdougie** [comment]
> 14 days sounds like a deadline

Correct, but we are in compliance now based on my redirect change.to create an insight page. Ideally, we can get a design for the page next week and implement the UI the week after. 

But to be clear, the solution doesn't need to be perfect, just work. We have not shared the existence of this URL outside of this issue.

**Comment by bdougie** [comment]
Got confirmation via email that we are  ow in compliance today.

I would still like this to redirect to a designed highlight creation page and not the current insight creation page.

**Comment by getaheaddev** [comment]
Note to self: remove shopping cart look in the design

**Comment by bdougie** [comment]
This route is currently broken and puts out at risk again per the above. @OgDev-01, can you do the following:

Create a new route for highlights to redirect to a highlight creation page. You can use the existing creation form, it just needs to force the user to authenticated if not already auth'd
