### ISSUE TITLE
Feature: the textArea to add highlight should be resizable

### ISSUE THREAD

**Issue by VenomFate-619** [open-sauced/insights#1081]
### Type of feature

🍕 Feature

### Current behavior

The text box is a little bit small, when typing more text into it, it becomes difficult to view and manage it.

![image](https://user-images.githubusercontent.com/67755128/230281999-a08fbd40-6e4d-4bcb-a92e-71246e1530c6.png)

### Suggested solution

That input area should be resizable same as GitHub have.
That textArea can have min-height, also we can make it a self-growing text area

![image](https://user-images.githubusercontent.com/67755128/230282578-751beba5-60a0-4ea6-9969-4c595ded1c90.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Thanks for opening this feature request, @VenomFate-619 

+1 to make it resizable.

Would love to hear from @open-sauced/triage team about this.

**Comment by VenomFate-619** [comment]
I would like to implement this

**Comment by takanome-dev** [comment]
> I would like to implement this

see https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by VenomFate-619** [comment]
sorry for the delay in the update was stuck somewhere

there are some UX concerns that I want to make clear.

At the present version, there is no resize in the text area as it is made to be self-growing

```typescript
  const handleTextAreaInputChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setBodyText(e.target.value);
    if (row < rowLomit && textAreaRef.current && textAreaRef.current?.scrollHeight > messageLastScrollHeight) {
      setRow((prev) => prev + 1);
    } else if (row > 1 && textAreaRef.current && textAreaRef.current?.scrollHeight < messageLastScrollHeight) {
      setRow((prev) => prev--);
    }
  };
``` 

but it is not working because the textArea component had a **fixed height,** which is why increasing the row does not change the height.

```html
 <textarea
      className={clsx(
        "flex h-20 w-full rounded-md  py-2  text-sm placeholder:text-slate-400    disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}
      ref={ref}
      {...props}
    />
``` 

So, this is the present implementation.

My question is should we have a resize or not? (seeing this, it seems that resize was not that much needed )

we can go with both options also.

there is one more bug in the current version, is if we paste a longer text the box size does not increase.
