### ISSUE TITLE
Bug: getting 0% of all dashboard percentages

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/insights#1083]
### Describe the bug

All the percentages displayed in the dashboard are 0.

![opensauced-dash-bug](https://user-images.githubusercontent.com/79809121/230749091-ec091eb5-0b5f-43b2-a21f-e041403587e5.png)

### Steps to reproduce

1. Go to [insights.opensauced.pizza](https://insights.opensauced.pizza)
2. Notice all percentages are 0%

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
I can confirm the same in Chrome: 
![image](https://user-images.githubusercontent.com/18273833/233496781-60e54e17-96ca-4f3e-ad82-57e1da816a52.png)


Plus, on slow network I got this message: 
![image](https://user-images.githubusercontent.com/18273833/233496727-9da2d259-11d1-4f00-9557-cfd7c14477b1.png)
Is this expected or should we have a place holder here?

**Comment by takanome-dev** [comment]
It's back to normal. I guess it might be some caching issues...
