### ISSUE TITLE
Feature: Add following and home tab on highlights

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1088]
### Type of feature

🍕 Feature

### Current behavior

@OgDev-01 can we add the following tab to the highlights feed.

### Suggested solution

I think this is commented our code. 

https://github.com/open-sauced/insights/blob/beta/pages/feed/index.tsx#L113-L214

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Sure we can. But first, we need to be sure of what we are displaying in that tab. To my understanding, we should be displaying highlights of people you follow _(needs API updates)_ . Is that correct? @bdougie

**Comment by bdougie** [comment]
That is correct.

**Comment by bdougie** [comment]
Assigned this to @OgDev-01. I believe this is just commented out.

**Comment by OgDev-01** [comment]
This needs `API` updates to get highlights of only followed users...
