### ISSUE TITLE
Feature: Remove negative and redundant reactions

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1100]
### Type of feature

🍕 Feature

### Current behavior

We have too many reactions. We should remove some.

### Suggested solution

<img width="386" alt="Screen Shot 2023-04-17 at 6 15 55 AM" src="https://user-images.githubusercontent.com/5713670/232495626-f4d728d8-30ee-4b4b-ada2-706b1adf791f.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
IMO, the +1 thumbs up reaction` 👍 ` is a positive reaction and shouldn’t be removed

**Comment by bdougie** [comment]
I see it as redundant to ♥️ and 😃

**Comment by OgDev-01** [comment]
This fix should be done from the API side of things, and we won't have to do any extra work from the frontend
cc: @brandonroberts

**Comment by OgDev-01** [comment]
> Can you open that as an issue and close this one out.

Sure..

**Comment by OgDev-01** [comment]
Great
