### ISSUE TITLE
refactor: update implementation of current select to be more flexible in usage

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1101]
### Type of feature

🍕 Feature

### Current behavior

The select needs a bit of work to be responsive atm... It overflows on mobile. We need to replace the select with Radix select that we already have in the design system. I'll open an issue on this to refactor the current radix implementation

_Originally posted by @OgDev-01 in https://github.com/open-sauced/insights/pull/1080_

### Suggested solution

Follow the approach from [shadcn](https://ui.shadcn.com/docs/components/select) and break all select particles into primitives that can be easy reused and customised

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
There is a similar issue on this https://github.com/open-sauced/insights/issues/756

**Comment by OgDev-01** [comment]
> There is a similar issue on this #756

Thanks for mentioning this... I'll close this and work with #756 👍
