### ISSUE TITLE
Bug: Use HTML form elements on the Highlights 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1103]
### Describe the bug

<img width="629" alt="Screen Shot 2023-04-18 at 7 26 37 AM" src="https://user-images.githubusercontent.com/5713670/232808365-f1132080-70ae-4957-9124-673062671895.png">

### Steps to reproduce

Form elements was suggested in slack. Make the box expand based on its contents.

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
There is a similar issue on this https://github.com/open-sauced/insights/issues/1081

**Comment by bdougie** [comment]
> There is a similar issue on this https://github.com/open-sauced/insights/issues/1081

Good catch. I need to go back and triage a bunch tonight.

Closing as duplicate of https://github.com/open-sauced/insights/issues/1081

**Comment by bdougie** [comment]
This resolution should be making the input expandable. 

![ezgif com-crop](https://github.com/open-sauced/insights/assets/5713670/c2e6a453-b526-4b95-a525-1ebac896e735)
