### ISSUE TITLE
Bug: Error on insight pages with 404 users

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1119]
### Describe the bug

When trying to view an insight page: https://insights.opensauced.pizza/pages/bdougie/5/dashboard

I get a client exception.

<img width="676" alt="Screen Shot 2023-04-24 at 9 39 28 AM" src="https://user-images.githubusercontent.com/5713670/234062274-09b2fda5-053f-42b7-a88a-c373130919bd.png">

### Steps to reproduce

Error message 

```
statusCode":404,"message":"You are not following this user","error":"Not Found"}
```

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@bdougie is this bug still present? I couldn't reproduce it :thinking:

**Comment by bdougie** [comment]
It's not I believe it was fixed in an api update
