### ISSUE TITLE
Feature: Force login when checking the box

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1132]
### Type of feature

🍕 Feature

### Current behavior

<img width="255" alt="Screen Shot 2023-05-01 at 9 06 47 AM" src="https://user-images.githubusercontent.com/5713670/235484444-a1804774-d07c-469b-81a6-8d3e8eda8fc0.png">

Today when a user is logged out, we do not allow them to check a box. Instead we make this an allowed action. When the user clicks "Create Insight," that should logged them in and present them with an insight page with the items selected in the cart.  

### Suggested solution

<img width="1241" alt="Screen Shot 2023-05-01 at 9 08 44 AM" src="https://user-images.githubusercontent.com/5713670/235485260-09f055c5-95ce-4f91-b8da-d411a0ebe2e4.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
This is challenging, but I would like to work on it. If it's not urgent, I will work on the weekend. 
.take

**Comment by a0m0rajab** [comment]
As first insights: 

The login can be done with the Supabase auth: https://github.com/open-sauced/insights/blob/beta/pages/hub/insights/%5BinsightId%5D/accept.tsx#L16 

The selected repo is being handled in the repo table: 
https://github.com/open-sauced/insights/blob/beta/components/organisms/RepositoriesTable/repositories-table.tsx

The check box is disabled in the table row:  
https://github.com/open-sauced/insights/blob/beta/components/molecules/RepoRow/repo-row.tsx#L211

What's the next step: 
- we should enable the checkbox in the table row. 
- Add the login logic to the add to insight page button based on the connect one (from the first link)

**Comment by a0m0rajab** [comment]
I could not open the list of the repos
![image](https://user-images.githubusercontent.com/18273833/236887093-7fbc2291-f261-4495-b2c6-9d047c7696fc.png)

I got this issue: 
![image](https://user-images.githubusercontent.com/18273833/236887857-e38bad93-22aa-4687-8320-d590e5a72d93.png)

is it related to the .env file or something else? @takanome-dev

**Comment by OgDev-01** [comment]
@takanome-dev and @a0m0rajab 
Auth in `beta` is currently down and will be fixed soon. That is the reason you get the error `524`

**Comment by a0m0rajab** [comment]
@OgDev-01 @0-vortex just thought, if the fix could take time, is there any dummy data been used before for such a situation?

**Comment by bdougie** [comment]
@a0m0rajab beta is fixed.

**Comment by a0m0rajab** [comment]
Opened a PR. There are two things I noticed here I am not sure if I should do in this PR or create a new one: 

1. The redirect option in the sign-in logic is not redirecting to the same page, it's going to the main page: https://github.com/open-sauced/insights/blob/beta/lib/hooks/useSupabaseAuth.ts#L43 
2. The logic we have right now does not keep track of the selected repos. It's just forcing sign-in, should we keep track of the repos and use that when we force the user to sign in?

From my perspective, I think both of them need to be done, but wanted to get your input.

**Comment by brandonroberts** [comment]
1. The redirect URL after login is something we still need to handle. I think we solved the issue with the config, but need to verify.
2. If we force login as soon as they try to check one of the boxes, tracking the repos isn't going to help much there. If we let them check the repositories, and force login when they click to create a page, then we could store them in the redirect URL for when they come back after login. This is what we do currently if they are already logged in

**Comment by takanome-dev** [comment]
I think there is an open issue about the redirect after login here -> https://github.com/open-sauced/insights/issues/1075

**Comment by a0m0rajab** [comment]
@takanome-dev Thank you for that! it helped me! 

I added redirect in the last commit that I have but there is only one issue, when I add the query data to the redirect it's just not being sent to the redirect.
