### ISSUE TITLE
Refactor: Replace supabase typography with native paragraph 

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/insights#1133]
### Type of feature

🧑‍💻 Refactor

### Current behavior

Based on #338 this issue should replace Supabase UI typography with Radix UI but Radix UI doesn't have a text component. So I think we can replace it with a native paragraph.
Thoughts? 
cc @0-vortex @OgDev-01 @Deadreyo

### Suggested solution

The component can be found here -> https://github.com/open-sauced/insights/blob/beta/components/atoms/Typography/text.tsx

### Additional context

We can also replace the [Title](https://github.com/open-sauced/insights/blob/beta/components/atoms/Typography/title.tsx) component with a native HTML header as well in the same fix.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Agreed, tailwind prose is the way to go: https://tailwindcss.com/docs/typography-plugin

**Comment by babblebey** [comment]
I'll .take this
