### ISSUE TITLE
Bug: feed is retrying requests indefinitely

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#1139]
### Describe the bug

The [feed](https://insights.opensauced.pizza/feed) page is checking whether the logged-in user is following other members - because this returns 404 when that happens, the default behaviour swr implies is to retry fetching the resource. 

That leads to a permanent API rate depletion and potentially spam, depending on how many feed tabs are left open.

<img width="1782" alt="Screenshot 2023-05-03 at 12 32 51" src="https://user-images.githubusercontent.com/237133/235893586-6cc931f1-2126-4bac-ae9b-bb0080f22ff5.png">

### Steps to reproduce

1. Don't follow anyone
1. Go to https://insights.opensauced.pizza/feed
1. Check console/wait

### Affected services

insights.opensauced.pizza

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
.take  
This is happening due to the call of useFollowUser when the app opens the highlight, it can be solved by turning the logic into a functional component.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/open-sauced/insights/pull/1164
