### ISSUE TITLE
Feature: redirect the user back to profile after onboarding.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1140]
### Type of feature

🍕 Feature

### Current behavior

<img width="1469" alt="Screen Shot 2023-05-03 at 6 51 39 AM" src="https://user-images.githubusercontent.com/5713670/235936064-fd5d62df-d5c3-4031-ab83-61ac4427a3e7.png">

### Suggested solution

~This is needed today for the Reactathon event today.~

This was a missed opportunity. However we should still start redirecting to a new page when onboarded is true.

The suggestion is redirecting to a topic/interest. Similar to the below:

https://github.com/open-sauced/insights/blob/4382e007590dcfa784319de4615a533e8918b404/components/organisms/TopNav/top-nav.tsx#L36

### Additional context

Attempted in https://github.com/open-sauced/insights/pull/1141

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@brandonroberts assigned to you to see if you can unblock. From talking to @BekahHW, the best place is to redirect the user to their own profile when "onboarding: true"

**Comment by brandonroberts** [comment]
Is this just the onboarding, or if they go to the homepage when logged in?

**Comment by brandonroberts** [comment]
Closed via https://github.com/open-sauced/insights/pull/1173
