### ISSUE TITLE
feat: add url box to highlight form

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1142]
My advice is to: 

- add url box as it is not evident on mobile how to add it if you start writing any text (as separate issue)

_Originally posted by @0-vortex in https://github.com/open-sauced/insights/issues/1137#issuecomment-1532572862_
            

I agree with @0-vortex on this. The Url should be a separate input field at the bottom of the text area preferably.

### Reasons (my opinion)

- It is a little difficult on mobile to know that the PR link will go in same field as the body once a user starts typing
- Adding this field will improve UX in general for technical and non-technical users

What are your thoughts on this? cc: @bdougie @getaheaddev

**Comment by bdougie** [comment]
I think your suggestion would be helpful @OgDev-01 

Making it clear for users is a step in the right direction.

**Comment by getaheaddev** [comment]
Can I get a link or a visual example of what's being talked about here @OgDev-01

**Comment by OgDev-01** [comment]
This has been addressed here https://github.com/open-sauced/insights/pull/1381
