### ISSUE TITLE
feat: Implement collaboration user & collaborator workflow

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1159]
## Collaborations tab with requests
<img width="872" alt="Screen Shot 2023-05-08 at 10 22 25 PM" src="https://user-images.githubusercontent.com/5713670/237001424-5e1f6293-e323-4005-a9fc-e50625d072cb.png">

## Collaborations tab with no requests
<img width="826" alt="Screen Shot 2023-05-08 at 10 22 10 PM" src="https://user-images.githubusercontent.com/5713670/237001398-44dd8be2-c45f-4034-80a7-7b34c81c5a42.png">

## Collaboration button and form
<img width="768" alt="Screen Shot 2023-05-08 at 10 23 51 PM" src="https://user-images.githubusercontent.com/5713670/237001605-f73a7d9e-8ad5-4780-a8f6-5c0324efea83.png">

## Design 
[Figma](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?type=design&node-id=120-2&t=eleETzJqGQfeLI12-0)

**Comment by a0m0rajab** [comment]
If I want to contribute on this should I work on the backend as well or is it implemented?

**Comment by bdougie** [comment]
We can only take contributions from OpenSauced Triage, Committers, and Maintainers **for now**. We suggest folks not on the team open issues and take a look at the [Bugs](https://github.com/orgs/open-sauced/projects/6) or [Papercuts](https://github.com/open-sauced/insights/issues?q=is%3Aopen+is%3Aissue+milestone%3APapercuts). If you would like to find **good first issues**, please check out the companion project to this, [open-sauced/hot](https://github.com/open-sauced/hot/issues)._

**Comment by a0m0rajab** [comment]
Thank you for the information!
