### ISSUE TITLE
Feature: Make reaction and repo list tooltips

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1183]
### Type of feature

🍕 Feature

### Current behavior

There are places in the app that do not show context

## Display the list of people that reacted

<img width="117" alt="Screen Shot 2023-05-16 at 6 11 15 AM" src="https://github.com/open-sauced/insights/assets/5713670/11e2a7ba-f7b6-4146-b1ea-438c724a65c7">

## Show the other repos that are listed

<img width="431" alt="Screen Shot 2023-05-16 at 6 10 56 AM" src="https://github.com/open-sauced/insights/assets/5713670/48e62173-3df4-4fd6-92ba-2bc150579f25">

### Suggested solution

This might need api-updates. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Lucif3r-in** [comment]
@bdougie Can you guide mw where to look into?

**Comment by bdougie** [comment]
Look for the ToolTip component and how it's implemented. Use that component as a wrapper for the reaction.

I not entirely sure the data is provided from the API, I'd check that and look at the api to confirm.

**Comment by takanome-dev** [comment]
There is an issue about showing a tooltip in highlight reactions https://github.com/open-sauced/insights/issues/1092
