### ISSUE TITLE
Feature: add check GitHub on profile page?

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1199]
### Type of feature

🍕 Feature

### Current behavior

Right now the profile page is getting information from GitHub but it does not allow to visit the github website,
![image](https://github.com/open-sauced/insights/assets/18273833/1e273c8f-4362-46e7-8934-b70b9b3176fd)

Should we have a button to check GitHub?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
the profile has been updated and this is no longer relevant.

**Comment by a0m0rajab** [comment]
@OgDev-01 I was expecting to click on the mention under the profile to open my GitHub: 
![image](https://github.com/open-sauced/insights/assets/18273833/51e0ba30-1f31-4e28-9a39-5e209cfd2b1b)

**Comment by a0m0rajab** [comment]
The solution would converting this to <a> 

https://github.com/open-sauced/insights/blob/932568ffe78b810b68fa0f053e62c87f7f9ceb9d/components/molecules/ContributorProfileInfo/contributor-profile-info.tsx#L57

**Comment by bdougie** [comment]
@a0m0rajab the way this issue was written it is not clear what you were asking.

Are you asking to link to your github profile from you OpenSauced profile?

**Comment by a0m0rajab** [comment]
@bdougie that's what I am asking, this was one of my first issues (in OSS) though. 
I was thinking to have a link to GitHub profile from my OpenSauced profile. 

If it's okay, I can open the PR right now

**Comment by bdougie** [comment]
Yes go ahead and open the pr

**Comment by a0m0rajab** [comment]
Pr Opened, thank you for the follow up!
