### ISSUE TITLE
Bug: missing counts of merged PRs

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1200]
### Describe the bug

In the dashboard when you hover on a user the counts of a merged PRs is shown as zero. 
![image](https://github.com/open-sauced/insights/assets/18273833/86a4c713-944c-4260-bc02-a06e2db30a9d)

### Steps to reproduce

1. go to the dashboard https://insights.opensauced.pizza/pages/YOURUSERNAME/NUMBER/dashboard
2. I tried with one repo - related to open sauced insights. 
3. hover on a user 

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
@a0m0rajab I tried to reproduce this on my public OSS page

https://insights.opensauced.pizza/pages/brandonroberts/1/dashboard

I hovered over my avatar

![image](https://github.com/open-sauced/insights/assets/42211/9eb626bd-3985-4e13-8bbf-b06c5ff134b3)

**Comment by a0m0rajab** [comment]
I could not reproduce this again, it might have been resolved. 

One minor thing: @takanome-dev has changed his profile picture but it seems not to be changed in the website. 

![image](https://github.com/open-sauced/insights/assets/18273833/32f8280b-9e91-41fb-83cd-e44dac11acaa)

https://insights.opensauced.pizza/pages/a0m0rajab/279/dashboard

**Comment by takanome-dev** [comment]
> One minor thing: @takanome-dev has changed his profile picture but it seems not to be changed in the website.

That was a caching issue, seems to be updated now
