### ISSUE TITLE
Bug: unnecessary API call highlight page

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1202]
### Describe the bug

When opening the highlight page it's calling the API for all the people showing their highlights and checks if they are been followed or not. I think this is not necessary and it can generate an unneeded load on the server, it could be fixed by turning the user menu to a function component. 

Like the PR: https://github.com/open-sauced/insights/pull/1197

The user menu:
![image](https://github.com/open-sauced/insights/assets/18273833/55911a27-2f58-4905-8e21-3489f8549afa)

Related to: https://github.com/open-sauced/insights/issues/1139

### Steps to reproduce

1. https://insights.opensauced.pizza/feed
2. open console and check the logs
![image](https://github.com/open-sauced/insights/assets/18273833/d06c8750-1b9a-4eb2-bcf6-062c369c2370)

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Lucif3r-in** [comment]
@a0m0rajab Hey can you guide me where to look into so that I can resolve the issue.

**Comment by a0m0rajab** [comment]
@Lucif3r-in thank you for the comment, I opened a PR related to this but it was for another issue, you might like to check it to see what approach I used to solve it, and comment on it if you like :)

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in thank you for the comment, I opened a PR related to this but it was for another issue, you might like to check it to see what approach I used to solve it, and comment on it if you like :) 

Sure @a0m0rajab 😄

**Comment by brandonroberts** [comment]
Fixed in https://github.com/open-sauced/insights/pull/1197
