### ISSUE TITLE
Feature: Highlight date should be from now

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1225]
### Type of feature

🍕 Feature

### Current behavior

The highlight feed shows the full date, but the user needs to know how long ago this highlight is from. 

 
<img width="701" alt="Screen Shot 2023-05-26 at 6 37 48 AM" src="https://github.com/open-sauced/insights/assets/5713670/12fbd04e-97e9-4962-bb6a-742cb434025b">

### Suggested solution

<img width="867" alt="Screen Shot 2023-05-26 at 6 42 59 AM" src="https://github.com/open-sauced/insights/assets/5713670/9187e11a-28ee-4b88-bdb7-33703a84a3f1">

## Date on highlight feed
https://github.com/open-sauced/insights/blob/36bba958584cb9f40ce184e154c8bee3c8492ced/components/organisms/HomeHighlightsWrapper/home-highlights-wrapper.tsx#L45

## single highlight
https://github.com/open-sauced/insights/blob/36bba958584cb9f40ce184e154c8bee3c8492ced/pages/feed/index.tsx#L135-L137

### Additional context

This was fixed previously by @OgDev-01, but there seems to be something that made this regress back to the original.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
This fix was only applied to the highlights on the user's profile page... Will update to reflect in the feeds to shortly
