### ISSUE TITLE
Feature: Hide Highlights on profiles that have not connected their github

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1227]
### Type of feature

🍕 Feature

### Current behavior

There are no highlights, so let's cross these out.

### Suggested solution

![Screen Shot 2023-05-26 at 8 58 35 AM](https://github.com/open-sauced/insights/assets/5713670/4f7c8f2b-6b37-44f3-8466-d99d87e3167e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Very well @bdougie 

I'll .take that
