### ISSUE TITLE
Feature: Footer location on small screens

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1230]
### Type of feature

🎨 Style

### Current behavior

The style of the footer on the small and medium screens is broken, it would be great to solve it. 

![image](https://github.com/open-sauced/insights/assets/18273833/80b3cc77-fc14-4293-8593-2eec6881ff24)

### Suggested solution

Create the design from [figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=1058-1622&t=TcN1oi6miw4IK9YT-0)

![image](https://github.com/open-sauced/insights/assets/18273833/5ad7792b-bee5-4ba8-92c1-670bad3051c9)

### Additional context

The figma file link is available on readme as well. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bpirrocco** [comment]
Hello! Just attempted a fix for this. Hope it helps!

**Comment by a0m0rajab** [comment]
@bpirrocco Thank you for working on this! 😄 

Pro tip: if you want to take other issues feel free to check this [documentation](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues), 
not: it has a great self assigning automation 👍
