### ISSUE TITLE
Bug: 404 when adding a new repo to the insight page.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1245]
### Describe the bug

While adding a few repositories to my insight page, I noticed it is returning a 404 on the following repositories. 

<img width="804" alt="Screen Shot 2023-06-05 at 10 23 50 AM" src="https://github.com/open-sauced/insights/assets/5713670/ca021522-5c17-48a6-b736-72494a1e1e91">

https://insights.opensauced.pizza/pages/bdougie/348/repositories

https://github.com/capitalone/synthetic-data
https://github.com/capitalone/rubicon-ml
https://github.com/capitalone/locopy 
https://github.com/capitalone/edgetest

## Error
<img width="531" alt="Screen Shot 2023-06-05 at 10 23 48 AM" src="https://github.com/open-sauced/insights/assets/5713670/ed0484db-19fb-45fa-a325-8099618b4758">

### Steps to reproduce

1. Create an insight page
2. Add one of the above repos
3. Note the error in the console.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
My disconnect is after 24hrs capitalone/rubicon-ml and edgetest are both not in my list and I still can't add them.

![image](https://github.com/open-sauced/insights/assets/5713670/70335fec-505a-4d42-ae6b-94ecc7e32b60)

![image](https://github.com/open-sauced/insights/assets/5713670/b4118265-5b71-4d86-a692-751ba7e67514)

**Comment by brandonroberts** [comment]
I see. I'll take a look at the ETL and data

**Comment by brandonroberts** [comment]
This issue should be resolved now. There was an issue in the ETL with the repository queue
