### ISSUE TITLE
Bug: Dependabot is showing up multiple times in the contributor list view

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/insights#1246]
### Describe the bug

1. I'm not sure if dependabot should even be considered a user
2. Dependabot is listed multiple times in the list view.

### Steps to reproduce

1. Go to [https://insights.opensauced.pizza/javascript/contributors/filter/recent](https://insights.opensauced.pizza/javascript/contributors/filter/recent)
2. See the bots.

![image](https://github.com/open-sauced/insights/assets/34313413/7a80bd3d-21c9-420c-855f-9b029f96d148)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This is resolved in https://github.com/open-sauced/insights/pull/1238 and will go out with the next release today

**Comment by brandonroberts** [comment]
This issue is resolved in the latest release
