### ISSUE TITLE
Language update: change developer to contributor

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/insights#1247]
- To be inclusive of non-developers, I suggest that we standardize our language and use "contributor" rather than developer. 

For example, [here](https://insights.opensauced.pizza/javascript/contributors/filter/recent), we use contributor most of the time, but at the top of the table, in the first column, we use Developer.

![image](https://github.com/open-sauced/insights/assets/34313413/f68680eb-cc72-4e06-8762-7247b7996122)

**Comment by a0m0rajab** [comment]
We only using developer in this table: https://github.com/search?q=repo%3Aopen-sauced%2Finsights%20developer&type=code 


And the SEO, not sure if we need to change the SEO, but this can be good first issue for anyone who want to work on it.

**Comment by babblebey** [comment]
Hi @a0m0rajab, great community here!

My name is Olabode, bringing the sauce from Lagos, Nigeria! I'm super excited to be here, credits and all thanks to @bdougie for gracing the stage at OSCAFest!

I am learning about the project, I should obviously start contributing from here.

Kindly assign me to this.
