### ISSUE TITLE
Bug: user profile local time minute is not properly formatted

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1275]
### Describe the bug

![Screenshot_20230618-110920_Chrome](https://github.com/open-sauced/insights/assets/62995161/2e814d1d-fa04-4d8b-9aaa-6a7be001ee4c)

This should be `11:08am` instead

### Steps to reproduce

Visit a user profile when thier local time is minute value is not up in `tens`

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by codewithshariq** [comment]
I would like to work on this bug.

**Comment by OgDev-01** [comment]
Great!... feel free to pick it up by commenting `.take`

**Comment by codewithshariq** [comment]
.take

**Comment by satyavalli5408** [comment]
I want to solve this bug.

**Comment by jpmcb** [comment]
Hi @satyavalli5408 - looks like this was already fixed in #1282. Be sure to [keep an eye on the "good first issue" label ](https://github.com/open-sauced/insights/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)for other issues that would be ideal for new comers to work on!
