### ISSUE TITLE
Bug: can't view highlight authors profile from single highlights dialog

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1276]
### Describe the bug

Clicking on the user's avatar at the top of a highlight does not take me to the user's profile
![highlight-single](https://github.com/open-sauced/insights/assets/62995161/ce14d1a0-ffdc-4ad2-a8bc-8e801bd3a461)

This behavior works on the feeds page and should be extended to the single highlight dialog

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Click to view a single highlight
3. Try clicking on the author's avatar to view their profile

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Yo @OgDev-01, most especially because this has my face in the screenshot.

I'll just .take it 😁

Thank you || Danke || O ṣeun

**Comment by OgDev-01** [comment]
> Yo @OgDev-01, most especially because this has my face in the screenshot.
> 
> I'll just .take it 😁
> 
> Thank you || Danke || O ṣeun

Excellent!... let me know if you have any questions around the fix 🤝
