### ISSUE TITLE
Feature: Bilboard component

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/insights#1292]
### Type of feature

🍕 Feature

### Current behavior

This feature request is not related to any problems, it is part of the Highlights page redesign.

### Suggested solution

The billboard component is meant to provide maintainers and companies with a space to show their project to the community. Until we figure out the full interaction for maintainers that wish to show their projects, we will ask them to provide us with the content and imagery to post in the component manually.

[Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=9002%3A16522&mode=design&t=nVDT2ovkFo1cL7LU-1)

![image](https://github.com/open-sauced/insights/assets/27322879/1944c697-28db-43da-a7c4-f20de61d706f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by codewithshariq** [comment]
``` .take ```
