### ISSUE TITLE
Feature: Newsletter subscription component

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/insights#1294]
### Type of feature

🍕 Feature

### Current behavior

This feature request is not related to any problems, it is part of the Highlights page redesign.

### Suggested solution

This component will allow users to subscribe to OpenSauced newsletter directly from the Highlights page.

[Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=9002%3A16522&mode=design&t=nVDT2ovkFo1cL7LU-1)

![image](https://github.com/open-sauced/insights/assets/27322879/0fb7bb8a-8357-4997-9b90-e5bbba60257e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Rather than the pizza, could we use this pizza element for the "You're Subscribed?"
![IMG_2977](https://github.com/open-sauced/insights/assets/5713670/c16b4cad-b07a-4d3f-93cc-c1a142f4bd6e)
