### ISSUE TITLE
Bug: Recommended Repos are undefined

### ISSUE THREAD

**Issue by codewithshariq** [open-sauced/insights#1296]
### Describe the bug

I tried to run the project locally and when I tried to go to the user details page the app crashed with the following error message:

<img width="1062" alt="Screenshot 2023-06-24 at 12 19 14 PM" src="https://github.com/open-sauced/insights/assets/67257981/95d0ba52-3e84-44f8-afb0-e1a49d19fb3d">

I tried to debug the issue and learned it occurred due to the user's interests string received from the backend. The string received is the following:

`",javascript,typescript"`

Due to the comma at the start of the string when we convert the interests string into an array using `array.split(",")` the first element of the array becomes `undefined` which causes the app to crash.

### Steps to reproduce

1. Clone the repository.
2. Run the project locally using `npm run dev`.
3. Authenticate the user using your GitHub account.
4. Visit your own profile from the dropdown in the top right corner.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
I could not reproduce this, yet when I went to your profile I found a the empty interests: 

![image](https://github.com/open-sauced/insights/assets/18273833/1699a1ed-6928-4e44-8b2f-154af9c89a4e)

Do you know how the empty interest got into your profile? did you add it manually?

**Comment by codewithshariq** [comment]
No, I did not add it manually. I just followed the Sign-In steps.

**Comment by a0m0rajab** [comment]
Yes, the issue is that I could not reproduce it, not sure how the first element got empty.

**Comment by codewithshariq** [comment]
Yes, the API response is strange. The interests string should not start with a comma sign, to avoid this issue.
