### ISSUE TITLE
Bug: CORS in update interests

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1309]
### Describe the bug

Updating interests is not working and I am getting a cors issue.

```
Access to fetch at 'https://api.opensauced.pizza/v1/auth/profile/interests' from origin 'https://insights.opensauced.pizza' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
settings-fa2409f6637d763f.js:1     PATCH https://api.opensauced.pizza/v1/auth/profile/interests net::ERR_FAILED
```

### Steps to reproduce

1. go to: https://insights.opensauced.pizza/user/settings
2. choose new interests 
3. press update. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @a0m0rajab, I have tried reproducing this in production and beta... But both seem to work well. Are you getting the error in local dev?

**Comment by a0m0rajab** [comment]
@OgDev-01 I am getting it in both beta and production: 

https://github.com/open-sauced/insights/assets/18273833/699e1778-4546-4c44-b436-c0e4f2b06032

**Comment by takanome-dev** [comment]
@a0m0rajab are you still having this issue?

I tried it but working fine for me :thinking:

**Comment by a0m0rajab** [comment]
@takanome-dev yes, it's still there!

**Comment by a0m0rajab** [comment]
I just updated the link in the issue description

**Comment by takanome-dev** [comment]
@open-sauced/triage anyone having CORS issues updating their interests?

**Comment by a0m0rajab** [comment]
Right now, I can not update anything on the profile, though, not just the interests, it's giving the same issue.

**Comment by a0m0rajab** [comment]
Based on @NsdHSO and @jpmcb, I was the only one who ran into this issue: 

Related comments: 

https://github.com/open-sauced/insights/issues/1446#issuecomment-1662454501
https://github.com/open-sauced/insights/issues/1446#issuecomment-1662481901
