### ISSUE TITLE
Feature: implement featured highlights in feeds

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#1312]
Can you open a corresponding issue for the implementation of this? 

Featured highlights can be the ones with the most reaction count. We should also enable the ability to manually select highlights to be featured as well.

Would love to start seeing these components start making on the page.

_Originally posted by @bdougie in https://github.com/open-sauced/insights/pull/1307#pullrequestreview-1503173689_
            

This feature requires the completion of https://github.com/open-sauced/ops-backend/issues/73 to be implemented

**Comment by babblebey** [comment]
Hey @OgDev-01

Following merging of the https://github.com/open-sauced/api/pull/198 that implements the required api-endpoint and ready state of `FeaturedHighlightPanel` component in the design system merged in issue #1307  

This feature is prime for implementation.

**Comment by takanome-dev** [comment]
Fixed by https://github.com/open-sauced/insights/pull/1337
