### ISSUE TITLE
feat: first contribution should be in years

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1317]
![image](https://github.com/open-sauced/insights/assets/5713670/9c4ae7dc-91dc-4acb-84bd-1426c4d94f4b)

Looking gr2m in the card and we should display years here instead of days.

**Comment by babblebey** [comment]
I'll .take this

**Comment by a0m0rajab** [comment]
This is the related code: 

https://github.com/open-sauced/insights/blob/9275dfeaaf95696d31d1ba83f91050ce621ac59c/components/molecules/DevCard/dev-card.tsx#L238

If you like you can change this directly within the browser (no need to run local environment) if you like, just press `.` to open the GitHub dev environment. 
Or change the `github.com` to `github.dev` to get to the same environment.
