### ISSUE TITLE
feat: Contributions should be Repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1318]
The label is contributions, but it should be Contributed repos.

<img width="304" alt="Screen Shot 2023-06-28 at 9 35 43 PM" src="https://github.com/open-sauced/insights/assets/5713670/4f0a1f4f-c390-418d-9ceb-0b5de6d6c838">

https://github.com/open-sauced/insights/blob/beta/pages/api/card.png.tsx#L63

**Comment by babblebey** [comment]
Umm, I'll .take that

**Comment by OgDev-01** [comment]
> Umm, I'll .take that

Lets goooo... 🍕

**Comment by a0m0rajab** [comment]
There is three parts of the code that you might need to change here, 

1. the link that @bdougie mentioned. 
2. those two next: 

https://github.com/open-sauced/insights/blob/9275dfeaaf95696d31d1ba83f91050ce621ac59c/pages/api/card.png.tsx#L142-L145


Besides that you can do this with `.` or `github.dev` it should not take much time and it could save you time from checking locally.
