### ISSUE TITLE
Bug: Devcard carossel animation stutter on Firefox

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/insights#1319]
### Describe the bug

Related to #1278

I've noticed a few bugs with the devcards carousel on FireFox. Here's a video. The left is firefox, the right is chrome:

https://github.com/open-sauced/insights/assets/23109390/bbf2767d-0e1e-4236-8122-62e3951b44f4

A few things i noticed:
- When clicking a card in firefox, if I wiggle my mouse, the card stales and stutters in its flipping over animation.
- The movement/shimmer animation isn't working on firefox

### Steps to reproduce

1. Open FireFox
2. Go to https://beta.insights.opensauced.pizza/user/jpmcb/card
3. Click card and wiggle mouse right away

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This was resolved in https://github.com/open-sauced/insights/pull/1335
