### ISSUE TITLE
Feature: Add posthog tracking on every share button

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1324]
### Type of feature

🍕 Feature

### Current behavior

I'd love to start tracking shares on platform properly and driving more engagement around those features. Today we have one place where we track the clicks on projects but we need to track the following other places. 

- [ ] Highlights Shared
- [ ] Insights Shared

https://github.com/open-sauced/insights/pull/1250

https://github.com/open-sauced/insights/blob/beta/components/molecules/ContributorProfileHeader/contributor-profile-header.tsx#L93-L95

### Suggested solution

Each link should follow the same pattern of "profile copied" or "profile tweeted" "highlight shared on linkedin"

We will want to see how many posts were shared on LinkedIn vs Twitter 

```
    posthog!.capture("clicked: profile copied", {
      profile: user?.user_metadata.user_name,
    });
```
#### Highlights

<img width="626" alt="Screen Shot 2023-06-30 at 1 03 48 PM" src="https://github.com/open-sauced/insights/assets/5713670/de25ffea-d483-42ed-a63c-772575dd7b4b">

#### Insights
<img width="1440" alt="Screen Shot 2023-06-30 at 1 04 04 PM" src="https://github.com/open-sauced/insights/assets/5713670/0b03aa3f-702b-40e1-a6db-55c1923fb768">

#### Profiles
<img width="1551" alt="Screen Shot 2023-06-30 at 1 04 18 PM" src="https://github.com/open-sauced/insights/assets/5713670/65c57d3b-8876-44a7-ad6c-61abe1736cf0">

### Additional context

Please reach out if you have questions. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
https://www.loom.com/share/41267ce0affa41d883091dad7829e96c?sid=7593064e-4293-45a2-8024-f2050221990d

**Comment by ThePromiseBenard** [comment]
can i .take?

**Comment by bdougie** [comment]
Yes
