### ISSUE TITLE
Bug: unnecessary scroll

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1325]
### Describe the bug

There is an unnecessary scroll in the large screens on the contributor's page. 

![image](https://github.com/open-sauced/insights/assets/18273833/3f7778a1-589f-48a3-a27e-0ab0a2c885ff)

### Steps to reproduce

1. go to the contributor page: https://insights.opensauced.pizza/user/a0m0rajab/contributions
2. Check the tabs area. You can see the scroll. 

Suggested solution: 

You can add `overflow:hidden` in the CSS. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by hritikchokker** [comment]
hi @a0m0rajab , i have reproduced this , scroll is there 
this class is responsible for the overflow,
.overflow-x-scroll 
overflow: hidden would not be a suitable solution for this, 
i think this class should be removed (.overflow-x-scroll ), and added dynamically in case there is a need for horizontal scroll if there are more tabs

![image](https://github.com/open-sauced/insights/assets/26836794/45dd66e6-9bec-4f2e-8c1a-e02b97a82552)

**Comment by a0m0rajab** [comment]
Would you like to open a PR for this?

Sent from mobile device


________________________________

**Comment by Lucif3r-in** [comment]
@a0m0rajab overflow-auto would resolve this. Should I raise a PR?

**Comment by a0m0rajab** [comment]
Thank you for the PR.
