### ISSUE TITLE
bug: Remove visibility page divider

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1343]
This change introduce another visual bug. The <hr />  divider was left on the page. 

![Screen Shot 2023-07-10 at 4 20 21 PM](https://github.com/open-sauced/insights/assets/5713670/7db0bfb6-cda9-4329-80ef-53d6d9df539c)

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1331#issuecomment-1629862048_
            
## Solution

Remove the lower divider

**Comment by bdougie** [comment]
FYI @Lucif3r-in

**Comment by NsdHSO** [comment]
I think this is better for `good first issue` https://github.com/open-sauced/insights/blob/88ef8ac0c5c6746f2b89ced31d899923d78f1441/components/organisms/SuggestedRepoList/suggested-repo-list.tsx#L18, must add specific display when we want to see the [divider](https://tailwindcss.com/docs/responsive-design).

**Comment by Lucif3r-in** [comment]
@bdougie I tried reproducing the page but I am getting a single divider. 
![image](https://github.com/open-sauced/insights/assets/85403534/40b46d93-c55a-415a-a389-7d58f7480760)

**Comment by LadegbayeStella** [comment]
I will like to .take this
