### ISSUE TITLE
Feature: Swap out the last commit date icon with a calendar

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1346]
### Type of feature

🍕 Feature

### Current behavior

The icon used is the same as the GitHub Issues icon and should be replace with the calendar. 

![Screen Shot 2023-07-11 at 1 11 42 PM](https://github.com/open-sauced/insights/assets/5713670/b64e00a3-2d94-46d3-942d-8fe83029b79c)

![Screen Shot 2023-07-11 at 1 11 50 PM](https://github.com/open-sauced/insights/assets/5713670/1f868176-0e54-4d57-a521-a92852b6e830)

### Suggested solution

The calendar we use in the highlight input is `BsCalendar2Event`. There might a simpler version. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by deepakrudrapaul** [comment]
.take
