### ISSUE TITLE
bug: error encountered after running `npm ci` 

### ISSUE THREAD

**Issue by babblebey** [open-sauced/insights#1348]
> I will assume you already have fork of the repo on your profile and it's cloned on your computer.
> 
> Start by Updating this branch in your fork, and re-pull it onto your computer.
> 
> > Hint
> > `git pull`
> 
> Then Follow the steps below.
> 
> * Open the project i.e. 'insights' in VSCode
> * Look for the `node_modules` folder, if you find it within your folder structure, **delete it**, if you cannot find it, ignore this step.
> * Open a new Terminal from VSCode 'Terminal' menu
> * Run the command `npm ci` and wait for the process to complete.
> * Then Run `npm run dev`
> 
> That should be everything.
> 
> Kindly Note: This Instruction assumes you already have NodeJS installed on your computer. If not, download NodeJS.

I had tried above steps but i encountered Error After Performing `npm ci` Command and Then i am getting This Error

![Screenshot 2023-07-12 191507](https://github.com/open-sauced/insights/assets/55046031/6c8dcea1-6117-4f28-bf9a-2e33eebfdd5f)

Is There any solution Could you Recommend to Resolve above Error

_Originally posted by @Shivam7-1 in https://github.com/open-sauced/insights/pull/1340#issuecomment-1632564262_

**Comment by babblebey** [comment]
Hi @Shivam7-1

Update your fork (.i.e. copy) of the repository, I can see here that your copy is atleast 11 commits behind - [Shivam7-1/insights](https://github.com/Shivam7-1/insights)

Get a copy of it locally on your computer and follow the steps again.

- Open the project i.e. 'insights' in VSCode
- Look for the `node_modules` folder, if you find it within your folder structure, delete it, if you cannot find it, ignore this step.
- Open a new Terminal from VSCode 'Terminal' menu
- Run the command `npm ci` and wait for the process to complete.
- Then Run `npm run dev`

**Comment by takanome-dev** [comment]
> Hii @babblebey Thanks Now it worked and I am able to run locally

https://github.com/open-sauced/insights/pull/1340#issuecomment-1636709417
