### ISSUE TITLE
Bug: User card not in screen on iPad

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1352]
## portrait
![image](https://github.com/open-sauced/insights/assets/5713670/13205b3d-f186-40da-9609-cc9d8f993a0a)

## landscape
![image](https://github.com/open-sauced/insights/assets/5713670/f205ada0-30d3-42bd-8fcf-a6de16a6f972)

## suggestion
You can test iPad screens in safari if you do not have an iPad.

**Comment by jpmcb** [comment]
I think this may actually be a duplicate of https://github.com/open-sauced/insights/issues/1336 ? (see my video where I shrink my browser window and get similar results)
