### ISSUE TITLE
Feature: Add new topics to the list

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1355]
### Type of feature

🍕 Feature

### Current behavior

Vue was requested as well as Kubernetes

https://github.com/orgs/open-sauced/discussions/11

## Add to the topics list
<img width="477" alt="Screen Shot 2023-07-14 at 7 34 01 AM" src="https://github.com/open-sauced/insights/assets/5713670/86c1a279-030e-4cdb-89e2-ecc6ab35cdc3">

## Add to the interests list
<img width="334" alt="Screen Shot 2023-07-14 at 7 34 08 AM" src="https://github.com/open-sauced/insights/assets/5713670/e3a09902-bf82-4354-9020-e762f9244ecc">

https://github.com/open-sauced/insights/blob/86824c217733f322b931f7f33d25b70600049737/components/atoms/LanguagePill/LanguagePill.tsx#L19

### Additional context

Previous PR https://github.com/open-sauced/insights/pull/877

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
@bdougie what icons should I use?

**Comment by bdougie** [comment]
Vue 🔎
K8s 👀
