### ISSUE TITLE
feat: Add discord as a link on the profile settings.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#1358]
Pretty straight forward ask. We will need an open-sauced/api update for this. 

![Screen Shot 2023-07-14 at 11 09 52 AM](https://github.com/open-sauced/insights/assets/5713670/f615cb3a-74b7-48b8-a6e3-e90d7146143e)

## User Settings
![Screen Shot 2023-07-14 at 11 10 15 AM](https://github.com/open-sauced/insights/assets/5713670/0fdf2698-5155-4fb2-98b3-685c56ab9c9c)

**Comment by takanome-dev** [comment]
Hey @bdougie, should the discord URL be like `https://discord.gg/opensauced` or `https://discordapp.com/users/{USER_ID}`?

**Comment by bdougie** [comment]
> Hey @bdougie, should the discord URL be like `https://discord.gg/opensauced` or `https://discordapp.com/users/{USER_ID}`?

Should be the second. The user is linking to their personal discord for DMs, friend request, etc.

**Comment by takanome-dev** [comment]
Okay, one way for users to add their discord link is by copying their ID and then updating their settings
![acreenshot](https://user-images.githubusercontent.com/79809121/253768678-12de9f97-b71f-4ee6-89b7-686b3be4916d.png)

But we don't want to display the full URL in their profile or just the ID. 
Displaying the user handle is what we want to do. 

We can do that by hitting the discord API (providing an API key) to get the username. But I'm looking for another way to get the username without making a fetch request.

I tried `discordapp.com/users/{username}` but it doesn't seem to be working.

Any ideas @open-sauced/triage?

**Comment by diivi** [comment]
Maybe just don't redirect this field anywhere if you want to display the username with the #tag.
This is what discord does with xbox ids (see my profile).



I also don't know of a way to get the username from the id without an API key.

**Comment by a0m0rajab** [comment]
Discord will not use the #tag anymore, they are going to use a normal username so we can ignore that idea now. (I might share the related link and read the full issue later)

Sent from mobile device


________________________________

**Comment by bdougie** [comment]
More context on this decision. https://discord.com/blog/usernames

**Comment by diivi** [comment]
This doesn't change the original suggestion though, are we fine with a non redirecting label on the profile is the question here.
