### ISSUE TITLE
Bug: text inputs colors are not consistent

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/insights#1359]
### Describe the bug

The text inputs have changed and now are not consistent in terms of background color

### Steps to reproduce

Beta vs Prod

![image](https://github.com/open-sauced/insights/assets/42211/5ec80241-ab90-4848-a60b-358010a4e28a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
@brandonroberts Hey! I have made a pull request for this issue can you please review it.
