### ISSUE TITLE
Bug: Unable to close modal

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1364]
### Describe the bug

I'm unable to close the "Complete the onboarding" modal. Clicking outside the modal or pressing the `Esc` key doesn't close it. It only get closed when the home link in the navbar is clicked.

### Steps to reproduce

- Go to [https://insights.opensauced.pizza/](https://insights.opensauced.pizza/)
- Authorize your GitHub account
- If our account is new, then you will have the `click the onboarding` button on the navbar
- ![Screenshot (771)](https://github.com/open-sauced/insights/assets/70102539/a5bff151-1657-4a66-bcca-c57c43ba844e)
- Now press `Esc` key or click outside the modal.
- ![Screenshot (772)](https://github.com/open-sauced/insights/assets/70102539/513a95cf-a252-46ce-9258-b1229f02a8ce)

### Browsers

Other (add additional context)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Hey @Olaleye-Blessing, that onboarding UI is not a modal but a different page for the onboarding steps. You should complete it and then move to the dashboard. Not sure if you can skip it though

**Comment by Olaleye-Blessing** [comment]
Oh! I see. I didn't notice the change in the URL. Thanks.
