### ISSUE TITLE
Feature: Improve colors ratio

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1367]
### Type of feature

🍕 Feature

### Current behavior

The selected option(s) in interests section do not have sufficient Background and foreground contrast ratio. 
![Screenshot (774)](https://github.com/open-sauced/insights/assets/70102539/f5b08435-1412-45de-a727-a0ac9039d56b)

### Suggested solution

Using "#fff" or "#000" foreground could be a solution.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @Olaleye-Blessing, thanks for taking the time to open this issue. I think a PR is already up that fixes this [here](https://github.com/open-sauced/insights/pull/1360)
