### ISSUE TITLE
Feature: Improve request actions on profile setting page

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1369]
### Type of feature

🍕 Feature

### Current behavior

On the settings page([https://insights.opensauced.pizza/user/settings](https://insights.opensauced.pizza/user/settings)), users can click the submit buttons multiple times, there by sending multiple request to the API.

![Screenshot (775)](https://github.com/open-sauced/insights/assets/70102539/dd362992-535b-45a4-8609-e09a5ca1deb0)

As seen in the screenshots, I was able to able to click `update interests` button multiple times within seconds. The same thing happens with other update buttons on the page.

### Suggested solution

Disable the update button when the request is loading.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Well spotted! Do you want to work on it, @Olaleye-Blessing?
[Contributing guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) can be found [here](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues)

**Comment by Olaleye-Blessing** [comment]
I thought this repo doesn't allow outsider's PRs, [https://github.com/open-sauced/insights#-contributing](https://github.com/open-sauced/insights#-contributing), but yea, I will work on it.

**Comment by takanome-dev** [comment]
> I thought this repo doesn't allow outsider's PRs,

I think most of the issues in [papercuts](https://github.com/open-sauced/insights/issues?q=is%3Aopen+is%3Aissue+milestone%3APapercuts) are up for grab

**Comment by babblebey** [comment]
> I thought this repo doesn't allow outsider's PRs, https://github.com/open-sauced/insights#-contributing, but yea, I will work on it.

That line only said "Unsolicited Contribution", but all contributors are encouraged to create an Issue first, then proceed with a PR after some comment(s). Just like you've done here @Olaleye-Blessing 

Welcome to the community.
