### ISSUE TITLE
Feature: Change "Delete page" to "Delete highlight" on highlights feed

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/insights#1382]
### Type of feature

🍕 Feature

### Current behavior

Currently, when editing a highlight, it says "Delete page"

<img width="529" alt="Screenshot 2023-07-17 at 10 15 56 AM" src="https://github.com/open-sauced/insights/assets/23109390/412a2f93-9fed-452d-acbb-6fc4c2f59740">

which is abit confusing to me (since I won't be deleting the whole Insights page! Just a single post).

### Suggested solution

Maybe instead it should say "Delete Highlight"? See below (edited in browser via web dev console:

<img width="528" alt="Screenshot 2023-07-17 at 10 18 13 AM" src="https://github.com/open-sauced/insights/assets/23109390/dbd9addf-8acb-48b9-b48c-996c9b0c30de">

Curious what others think or if this makes sense!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by LadegbayeStella** [comment]
I will .take this

**Comment by kakashi2020** [comment]
@LadegbayeStella , let me know if you by any chance stop working on this so I can take over :)

**Comment by bdougie** [comment]
> @LadegbayeStella , let me know if you by any chance stop working on this so I can take over :)

This is as straight forward as it gets for a contribution. 

https://github.com/open-sauced/insights/blob/beta/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L475

That line needs a change. I have confidence that @LadegbayeStella will be able to do it and suggest looking for another open issue here or take a look at this project that less contributors. 

https://github.com/open-sauced/ai

Would love some help there.

**Comment by kakashi2020** [comment]
I'll do that, @bdougie . Thanks!
