### ISSUE TITLE
Bug: Auto-Scroll Not Triggered Upon Clicking 'Next Page' in Highlights Page

### ISSUE THREAD

**Issue by chhristopher** [open-sauced/insights#1386]
### Describe the bug

Currently, when a user clicks the next page icon, the auto-scroll feature is not being activated on the new page. This results in the user being left at the same scroll position they were in on the previous page. This bug requires users to manually scroll back to the top of the page each time they navigate to a new page, which is not the intended behavior. Ideally, upon clicking the next page icon, the system should automatically scroll the user to the top of the new page to provide a seamless browsing experience.

![Issue-Bug-](https://github.com/open-sauced/insights/assets/48575398/aee7e609-05b4-4353-ab47-5a89c16057d5)

### Steps to reproduce

1. Go to [https://insights.opensauced.pizza/feed](https://insights.opensauced.pizza/feed)
2. Scroll down to the end of the page and click next page icon

### Browsers

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by aryanas159** [comment]
@bdougie Can you please review the PR. Thanks

**Comment by bdougie** [comment]
@aryanas159 no need to ping. We have a team of reviews. My suggestion is pinging the author of the issue for reviews instead to ensure you solved the problem.
