### ISSUE TITLE
Feature: Add upgrade access button to user settings page

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/insights#1394]
### Type of feature

🍕 Feature

### Current behavior

This would add a button in the user settings page to upgrade the user to get go through the checkout process and get access to reports. This is currently only available on the `Reports` tab for logged in users. 

### Suggested solution

Add the button under the email preferences.

<img width="420" alt="image" src="https://github.com/open-sauced/insights/assets/42211/f945ea3b-88e7-4d12-b56c-9bbf63afdca8">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
I'll .take it
