### ISSUE TITLE
Bug: misaligned chat close button icon 

### ISSUE THREAD

**Issue by wasimapinjari** [open-sauced/insights#1407]
### Describe the bug

The icon of the chat close button is misaligned. 

The close icon should be in the center of the circle.

![Screenshot (167)](https://github.com/open-sauced/insights/assets/95426296/7d3cea25-1f12-48e7-a92f-2ee7d69e55d2)

### Steps to reproduce

1. Click on the chat button

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Good catch! That chatbot is injected into the app. Not sure if it should be fixed in the configs of sitegpt or using dom selectors
https://github.com/open-sauced/insights/blob/1f231c9d282a80f56ad89af5845ff18ad5a66c75/pages/_app.tsx#L170-L174

cc @bdougie

**Comment by bdougie** [comment]
It's either a css collision with us and the service or the service has broken css upstream. 

We need someone to triage this with a new next app injecting the sitegpt service.

If anyone has bandwidth to check and report back that would be helpful. 

@open-sauced/triage

**Comment by NsdHSO** [comment]
Duplicate #1416

**Comment by wasimapinjari** [comment]
@bdougie problem is from our end.

![Screenshot (177)](https://github.com/open-sauced/insights/assets/95426296/257f884e-5fc7-49b3-8d77-4736e0376fe7)

**Comment by wasimapinjari** [comment]
I fixed it. Yeh! 😎

![Screenshot (181)](https://github.com/open-sauced/insights/assets/95426296/7e652702-ad5c-4aee-ba47-5c1b0c606090)
