### ISSUE TITLE
Bug: Flash of 'test content' while dashboard page loads

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1408]
### Describe the bug

![Screenshot (807)](https://github.com/open-sauced/insights/assets/70102539/f99ea624-6a6a-4899-81f7-0f8a6f2b3d03)

The above content shows briefly while the page is loading.

### Steps to reproduce

- Go to [https://insights.opensauced.pizza/javascript/dashboard/filter/recent](https://insights.opensauced.pizza/javascript/dashboard/filter/recent)
- Notice error while the page is loading

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by deepakrudrapaul** [comment]
.take
