### ISSUE TITLE
Bug: highlights in contributor-profile-tab

### ISSUE THREAD

**Issue by NsdHSO** [open-sauced/insights#1410]
### Describe the bug

After I create a highlight, I go to `contributor-profile-tab' and see that they are not aligned.

### Steps to reproduce

1. Create new highlights 
2. Open in the profile section 
3. And you will see the new highlights.

[Here](https://github.com/open-sauced/insights/blob/35cfd222a31fb6dc3aa2cef7cd6aacb1c0ef1f57/components/organisms/ContributorProfileTab/contributor-profile-tab.tsx#L147 
) You must add `max-width` and `width` =>> `w-28`

### Browsers

Chrome, Other (add additional context)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
> After I create a highlight, I go to `contributor-profile-tab' and see that they are not aligned.

@NsdHSO What do you mean about `they are not aligned`?
I tried to reproduce it but everything looks good. Do you mind providing some visual feedback?

**Comment by NsdHSO** [comment]
Yes,  I uploaded a screenshot.
![Screenshot 2023-07-25 at 09 11 48](https://github.com/open-sauced/insights/assets/37635083/185b5da7-b297-4114-b933-bf7ec545643a)

**Comment by bdougie** [comment]
> Yes, I uploaded a screenshot.

Hard to tell because the first highlight has no title.

**Comment by NsdHSO** [comment]
> > Yes, I uploaded a screenshot.
> 
> Hard to tell because the first highlight has no title.

I update the highlight with a title. 
![image](https://github.com/open-sauced/insights/assets/37635083/3d2a37f9-fcec-4736-b024-e5d812aa2328)
