### ISSUE TITLE
Feature: Add Conditional Routing for Single Highlight Dialog Close Button

### ISSUE THREAD

**Issue by babblebey** [open-sauced/insights#1414]
### Description

Currently, when a user clicks on a single highlight from a user profile, a dialog opens on the `/feed/[id]` route. However, when the user clicks on the close button of the dialog, it routes back to the `/feed` page, displaying the general highlights. This behavior can be confusing and requires the user to go back to the user profile page again to view their highlights.

To enhance the user experience, I propose adding a conditional routing feature to the close button of the dialog. The idea is to route to the `/feed` page only when the dialog is opened from the `/feed` page. If the dialog is opened from a user profile page, the close button should simply close the dialog without any additional routing.

### Steps to reproduce

1. Go to the a user profile highlights page (user/[username]/highlights) where a list of their highlights is displayed.
2. Click on one of the highlights to view more details. Notice that a dialog opens showing additional information about the selected highlight.
3. In the dialog, you can see the close button (usually represented by an 'X' or a close icon).
4. Click on the close button in the dialog.
5. Observe that the page navigates back to the main highlights page (/feed) instead of staying/returning to the user's profile page if the dialog was opened from there.

**Expected Behavior:**

When clicking the close button in the dialog, it should close the dialog and return to the user's profile page if the dialog was opened from there. However, if the dialog was opened from the main highlights page, clicking the close button should navigate back to the main highlights page (/feed).

[screencast-insights.opensauced.pizza-2023.07.14-13_53_47.webm](https://github.com/open-sauced/insights/assets/25631971/951325f5-041c-41bd-b4ac-6da5d044ac86)

### Browsers

Chrome, Firefox, Safari, Edge, Opera

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Make sense :+1: Let's make it a feature request :pizza:

**Comment by babblebey** [comment]
I'll just .take it 🍕
