### ISSUE TITLE
Feature: Allow use of full repository URL when adding a repository to an insights page

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/insights#1415]
### Type of feature

🍕 Feature

### Current behavior

If I try to copy/paste a repository URL from github.com into the field for adding it to my insights page, I get an error message. I am instead required to use only the part of the URL that is repository's full name.

![2023-07-24 19 29 03 insights opensauced pizza f17067e3cb76](https://github.com/open-sauced/insights/assets/26224873/e7a0a3be-0fca-4d4d-860b-7af1a51e0bf7)

### Suggested solution

I would like to be able to just enter the full URL in this field. This could probably be achieved by having a script on the frontend that recognizes Github URLs and can pull from it the information that the field requires.

I'd be happy to work on this if this repository is looking for contributions from the community.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Hey @dominicduffin1, thanks for taking the time to file this issue.
Contributions are welcomed. See [docs.opensauced.pizza](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues)

Let's first hear about @open-sauced/triage and @bdougie what do they think about this feature request?

**Comment by a0m0rajab** [comment]
I think this might have a smoother user experience.

**Comment by dominicduffin1** [comment]
`.take`

**Comment by bdougie** [comment]
@dominicduffin1 we have a solution for this in another repo. https://github.com/open-sauced/open-sauced/blob/main/src/lib/util.js#L1

This is a common request, but we never had time to add.

Would really appreciate tests in the PR as well.
