### ISSUE TITLE
Feature: Add navigation to improve accessibility

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1433]
### Type of feature

🍕 Feature

### Current behavior

In relation to #358, the website currently has navigation links, but they are wrapped in a `div` element, which is not the most semantically appropriate approach for implementing navigation.

Using a `div` element makes it harder for search engines to understand the website's structure, and might not adhere to web standards.
![Screenshot (818)](https://github.com/open-sauced/insights/assets/70102539/3d8e69de-5ffb-43ff-a092-bb8e8d402b85)

### Suggested solution

Use the `nav` element to group the navigation links.

- [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav)
- https://www.w3.org/TR/2011/WD-html5-author-20110809/the-nav-element.html

Also, they could further be rendered as list of links, wrapped with a `ul` element like so: `nav > ul > li > a`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take
