### ISSUE TITLE
Feature: Improve Keyboard Accessibility for Notification Icon

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/insights#1434]
### Type of feature

🍕 Feature

### Current behavior

In relation to #358, the website's notification icon is currently rendered using a `div` element, which presents accessibility challenges as it is not interactive by default, causing difficulties for keyboard users to access and interact with it.

While navigating through the website using the keyboard, I noticed that the notification icon was not included in the navigation flow, due to its use of a div element.

![Screenshot (819)](https://github.com/open-sauced/insights/assets/70102539/2b656554-4ddd-49b8-9c58-122e426cb912)

### Suggested solution

Change the `div` element to a `button` element. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take
