### ISSUE TITLE
Bug: Onboarding Button Breaks UI on Mobile Screen

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/insights#1442]
### Describe the bug

Here is the screenshot of the issue:

![A51E9791-9830-4800-BD4A-D526B80D892D](https://github.com/open-sauced/insights/assets/106407013/26de47a6-3e27-48eb-ac49-37618cbc01d3)

### Steps to reproduce

Sign up without completing the onboarding flow and resize to mobile.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Jittojoyes98** [comment]
Can i work on this issue ?

**Comment by OgDev-01** [comment]
Hey @Jittojoyes98, Yes you can 👌.  you can comment with `.take` to assign issue to youself.

Also for the future could you check this little [doc](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

**Comment by Jittojoyes98** [comment]
.take

**Comment by bdougie** [comment]
My suggestion is hiding the the "complete your onboarding" on mobile. Most users are on desktop.

@Jittojoyes98, can you provide an update on this and how it is going?

**Comment by Jittojoyes98** [comment]
Working on it.Can you please mention the code too of the same.

**Comment by OgDev-01** [comment]
> Working on it.Can you please mention the code too of the same.

Here is the line That needs updating in the `onboardingButton` component

adding `hidden md:flex` classNames to the button should fix this.
https://github.com/open-sauced/insights/blob/31a9a6abda62c84475266e602ad95a5b62ab5fab/components/molecules/OnboardingButton/onboarding-button.tsx#L8

You can find this component in the `molecules` directory in `components`

**Comment by dev-phantom** [comment]
This issue has been fixed
@RitaDee can you kindly close this

**Comment by takanome-dev** [comment]
fixed in https://github.com/open-sauced/insights/pull/1460
