### ISSUE TITLE
Bug: Feed Page is not responsive

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/insights#1453]
### Describe the bug

https://github.com/open-sauced/insights/assets/62995161/41e11c94-257f-40ee-8955-2e00d10cc036

### Steps to reproduce

Go to https://insights.opensauced.pizza/feed

Resize your browser to check responsiveness.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
I will love to work on this.

.take

**Comment by babblebey** [comment]
Duplicate to Issue #1336 

Do well to reference it in your PR @RitaDee

PS: You can also find some fine resources to guide Responsive in the [comment](https://github.com/open-sauced/insights/issues/1336#issuecomment-1636044806) from @NsdHSO there too.

**Comment by RitaDee** [comment]
Noted with that thanks @babblebey
