### ISSUE TITLE
Bug: items on highlight feed looks tilted to the left

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#1479]
### Describe the bug

the items on the highlight feed is tilted to the left 
here is a screenshot:

![image](https://github.com/open-sauced/insights/assets/72051159/88fb3398-79b6-4943-b324-82d692ca218b)

_for some reason i guess am the only one encountering this error_

### Steps to reproduce

1. go to https://insights.opensauced.pizza/feed
2. see error

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
move conversation to https://github.com/open-sauced/insights/issues/1353
