### ISSUE TITLE
Bug: I can't see anything on my profile?

### ISSUE THREAD

**Issue by andersonjoseph** [open-sauced/insights#1480]
### Describe the bug

My profile seems empty, is not showing my profile pic/bio/languages/interests/twitter 

I have all of those in my settings page but still not showing in my profile 

![image](https://github.com/open-sauced/insights/assets/22438127/978815c1-ca8a-4d2e-a190-af7f26f746b6)

![image](https://github.com/open-sauced/insights/assets/22438127/c141b1b7-6ec2-4982-a4e1-745b646f3ad1)

### Steps to reproduce

Go to: https://insights.opensauced.pizza/user/andersonjoseph

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by Jittojoyes98** [comment]
Can you explain more ?

**Comment by brandonroberts** [comment]
@andersonjoseph for some reason, your username was under `hateablestream`. Was this a previous alias? I updated your username to match, so it displays correctly now.

<img width="1349" alt="image" src="https://github.com/open-sauced/insights/assets/42211/6df84105-7301-4c6f-8c93-dfa9a9be8e0d">

**Comment by andersonjoseph** [comment]
oh yeah! It was my previous username on GitHub. Now everything is working, thanks 👍👍

El 4 ago. 2023 a las 8:14, Brandon Roberts ***@***.***> escribió:

@andersonjoseph for some reason, your username was under hateablestream. Was this a previous alias? I updated your username to match, so it displays correctly now.

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>

-- Sent with https://mailfence.com  Secure and private email
