### ISSUE TITLE
Bug: no space between the buttons and the profile picture 

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#1491]
### Describe the bug

In the insights user profile on mobile phone, the share and get card button are squashed with the user profile picture
Here's a screenshot
![Screenshot_20230805-122449](https://github.com/open-sauced/insights/assets/72051159/395d8d71-0495-4131-b2e3-78c304dace4f)

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/user/dev-phantom on mobile 
2. See error 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
@OgDev-01 can you label this a good first issue

**Comment by DevPres** [comment]
i would like work on this! .take

**Comment by bdougie** [comment]
Adding context here, that a simple fix to padding is not enough here. We may want to consider. a dropdown (design system supports this in the highlights).

https://github.com/open-sauced/insights/pull/1492#issuecomment-1667184262

**Comment by DevPres** [comment]
ok,

Do you have any ideas on how to integrate a dropdown graphically?

And does it need to be a dropdown only in mobile view?

**Comment by RitaDee** [comment]
@DevPres, here is an implementation of the dropdown on the design system:

https://github.com/open-sauced/insights/blob/a159943ad8accce0fd5daf7fbcb3d8eb1b5211a3/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L288

I hope this helps.
