### ISSUE TITLE
Feature: Make deleting highlights more intuitive

### ISSUE THREAD

**Issue by diivi** [open-sauced/insights#1495]
### Type of feature

🍕 Feature

### Current behavior

After struggling to find a delete button and deleting the highlights I created for testing through the API 😓, while working on the edit highlight modal, I realised that's the place you delete a highlight from.

https://ux.stackexchange.com/a/104755

### Suggested solution

Add a delete option to the context menu directly?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
I thought it was intentional to prevent deleting highlights, if that's not the case I can .take it.

**Comment by diivi** [comment]
Yeah, it's intentional. I'm just reporting what I felt, if the team thinks there's no need to work on it, it's fine. So let's wait😁

**Comment by brandonroberts** [comment]
I think its fine for now. On initial design, the delete is meant to be inside the edit.
