### ISSUE TITLE
Bug: middleware odd behaviour

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1503]
### Describe the bug

If you update the page when you are on the insight page the middleware will send you again to the dashbaord. 

https://github.com/open-sauced/insights/assets/18273833/857ac609-8b91-4bab-a6a1-fbbd9cf7b147

### Steps to reproduce

1. go to https://insights.opensauced.pizza/hub/insights
2. refresh the page when you are on the page
3. you will find yourself on the dashbaord

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by deepakrudrapaul** [comment]
.take
