### ISSUE TITLE
Bug: the highlights tab selection get unselected when we use filters

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1511]
### Describe the bug

the highlights tab selection get unselected when we use filters

https://github.com/open-sauced/insights/assets/18273833/645af6b6-f041-4f84-bb66-15dde667bc04

### Steps to reproduce

1. go to highlights https://insights.opensauced.pizza/feed?repo=griff-m001/Data-Collection-Project
2. check the highlight tab on the top, the color is orange
3. select a filter, 
4. check the tab again, the color is black.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
May I please work on this issue?

**Comment by ThePiyushAggarwal** [comment]
.take
