### ISSUE TITLE
Bug: margin removed from the titles! 

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/insights#1526]
### Describe the bug

If you open insight page on small screens the titles will not be shown: 

![image](https://github.com/open-sauced/insights/assets/18273833/78220868-b614-4773-a47e-789db02ff433)

On large screens the titles will be close to the header:

![image](https://github.com/open-sauced/insights/assets/18273833/2f7be8f0-fb77-443e-af89-b3b3ccb1eb08)

### Steps to reproduce

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
.take

**Comment by dev-phantom** [comment]
.take
