### ISSUE TITLE
Bug: Left sidebar on highlights page is cut off on big screen

### ISSUE THREAD

**Issue by adiati98** [open-sauced/insights#1530]
### Describe the bug

On big screen (laptop 15 inch), the left sidebar on the highlights page is cut off, and there's more space on the right side.

#### Screenshot

![highlights page opensauced](https://github.com/open-sauced/insights/assets/45172775/f7848a15-78fc-4352-a43f-0a9acb049672)

### Steps to reproduce

1. On your computer, go to the Highlights page.
2. You can see the left sidebar is cut off.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Hmmm this looks like a lingering problem that we thought was fixed in: https://github.com/open-sauced/insights/issues/1336

Closing this one as a duplicate but can you read that issue and provide any additional information there? Thanks so much and thanks for raising this problem!!
