### ISSUE TITLE
Bug: Single Highlight Dialog Close Button not Working in new Browser Tab

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/insights#1544]
### Describe the bug

When clicking a single highlight link from an external webpage, the close button within the dialog does not respond as expected to the close action. The issue can be traced back to a specific code block within the repository:

[Link to the Code Block](https://github.com/open-sauced/insights/blob/a7b0c3bb95e76e2d0e700265ac405e8a71b3c97a/pages/feed/index.tsx#L163)

This problem appears to stem from the routing behaviour of the application. When the router attempts to route to a specific page, it fails to do so when the page is opened in a new tab. This is because there are no browsing history entries to navigate back to in the new tab instance.

### Proposed Solution

To address this issue, we need to consider the routing behaviour when allowing the dialog to close and route to the `/feed` page. The current condition for closing the dialog may need to be modified to account for scenarios where the page was opened in a new tab. By factoring in this behaviour, we can ensure that the dialog behaves as expected even when accessed through external highlight links.

### Steps to reproduce

https://github.com/open-sauced/insights/assets/106407013/b9051be5-2694-4265-abd6-90f2a6daed7c

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Hey @RitaDee 

Thank you for picking this one out, I worked on a PR that introduced that part to the code base, this is some case I would've sworn was already addressed in the routing conditions. 

Thank you once again for pointing this out, I will patch a fix for it.

.take
