### ISSUE TITLE
Bug: navbar is hiding other content

### ISSUE THREAD

**Issue by joe-shajan** [open-sauced/insights#1546]
### Describe the bug

navbar is hiding other content 

![image](https://github.com/open-sauced/insights/assets/69904519/75321f89-3d30-4f2b-9a18-c88618678f8a)

### Steps to reproduce

1. go to https://insights.opensauced.pizza/javascript/dashboard/filter/recent

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Thanks. This has been resolved in the latest release
