### ISSUE TITLE
Feature: horizontally align toggle options on mobile

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/insights#1572]
### Type of feature

🍕 Feature

### Current behavior

![2023-08-18_07-37](https://github.com/open-sauced/insights/assets/79809121/67b2988c-402a-42f9-9d33-1894996ef603)

### Suggested solution

![solution](https://github.com/open-sauced/insights/assets/79809121/fde789e9-3e50-48b3-9862-5f0deb2e8622)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by himanshumalviya15** [comment]
.take
