### ISSUE TITLE
Bug: `UserCard` leaves the viewport on sticky sidebar

### ISSUE THREAD

**Issue by babblebey** [open-sauced/insights#1579]
### Describe the bug

The `UserCard` component hits the page boundary and leaves viewport on page scroll when sidebar is sticky.

It seem the initial set-up was developed factoring in only case where a user is not logged in (at this point, the `UserCard` component is not rendered) because the `top` position property seem to work just fine when a user is not logged in.

### Suggested Solution

The `top` position property should be set based on the condition of `user authentication` i.e.
- When user is logged in, `top` should be of a value higher than it currently is maybe `top-12`
- When user is not logged in, `top` can be as currently is. i.e. `top-8`

### Steps to reproduce

[screencast-insights.opensauced.pizza-2023.08.19-17_04_16.webm](https://github.com/open-sauced/insights/assets/25631971/9f2f7c0f-9896-4c33-9462-7482b1240f5f)

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
.take
