### ISSUE TITLE
[Refactor] Investigate directly adding Octicons to project to better match design.

### ISSUE THREAD

**Issue by chadstewart** [open-sauced/insights#259]
## Summary

The current icons are inconsistent. They vary with stroke width, which makes it hard for developers to implement them without any back and forth from design.

### Possible Solutions:
1. Try updating **Octicons** from `v8` to `v17` in React Icons. _If that doesn't work... try solution 2_
2. Install **Octicons** directly, and replace the icons.

### Solution 01:

> **Note**
> Make sure to lock the version once it's updated, so it becomes future proof.

- [ ] Check if there's a way to update **Octicons** version from `v8` to `v17` on **React Icons** `package.json`.
- [ ] Update and lock the version.
- [ ] Replace icons for Octicons

_If that didn't work, use solution 2:_

### Solution 02: 

Follow the steps here: https://primer.style/octicons/packages/react.

- [ ] **Install:** `npm install @primer/octicons-react`
- [ ] **Search the icon:** https://primer.style/octicons/
- [ ] **Import:** eg: `import {IssueOpenedIcon} from '@primer/octicons-react'`
- [ ] **Replace old icons with Octicons**

---

### Context:

> Currently React Icons uses v8 of Octicons and the latest version is v17. This means that there are several Octicons that is not available through React-Icons.
> 
> This issue is exploring the idea of using the Octicon package directly to get access to the latest Octicons.
>
> It's looking better, but still, I think we should use the updated version of Octicons, because they will certainly render better.
> 
> I checked, and React Icons is using `v8` of Octicons ([see package.json](https://github.com/react-icons/react-icons/blob/master/packages/react-icons/package.json)), while they're at `v17` ([see octicons repo](https://github.com/primer/octicons)).
> 
> Can we update the version we're using to be the latest?
> 
> [**React Icons Package.json:**](https://github.com/react-icons/react-icons/blob/master/packages/react-icons/package.json)
> ![Screen Shot 2022-08-23 at 5 32 50 PM](https://user-images.githubusercontent.com/101464991/186260026-862209c3-a063-4bd6-b480-7863be83a2ca.png)
> 
> [**Octicons:**](https://github.com/primer/octicons)
> ![Screen Shot 2022-08-23 at 5 33 14 PM](https://user-images.githubusercontent.com/101464991/186260087-f0f3ad09-b8e0-47b8-b948-0bb2de75eac4.png)

_Originally posted by @pixelsbyeryc in https://github.com/open-sauced/insights/pull/243#discussion_r953084951_

**Comment by 0-vortex** [comment]
This has been implemented!
