### ISSUE TITLE
[Design] User settings page or panel

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#382]
As a user I want to be able to do the following
- opt-in to providing location (we can grab this from github)
- ~~update my PAT github token~~
- ~~generate an API or JWT for building with the public API (cc @0-vortex)~~ 
- update the provide email
- opt-out of marketing communications (emails).

**Comment by bdougie** [comment]
While using Reddit, I noticed their version of the topic picking in modal form.

<img width="849" alt="Screen Shot 2022-12-22 at 12 22 25 PM" src="https://user-images.githubusercontent.com/5713670/209221860-b3701d0b-6b3f-42a1-9386-24ea914ef4f4.png">

**Comment by getaheaddev** [comment]
Done. @bdougie @chhristopher let me know if you saw the campsite screen grab
