### ISSUE TITLE
enhancement: Animate the `CardHorizontalBar` component

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/insights#412]
## Summary

Improve the hover state of `<CardHorizontalBar>` component, used for displaying languages.

- [Follow the Figma Prototype](https://www.figma.com/proto/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?page-id=3758%3A4361&node-id=3758%3A4410&viewport=-939%2C1085%2C2&scaling=contain&starting-point-node-id=3758%3A4384)

### Functionality

1. When mouse enters
    * Bar on hover increases in size 2px in height, 4px in width.
    * Other bars will be pushed to the side by 2px on each side.
    * Update the text to match the hovered
2. When mouse leaves
    * Return bar to original state
    * Update text to original text

**IMPORTANT:** Component should maintain its size and position on the page (no jumping down or increasing width). 

For that to happen, it might be necessary to duplicate the bars and use position absolute for bars that will increase (without affecting the entire component).

We can also use `flex: <PERCENT>;`, or `flex-[<PERCENT>]` on the bars to define their width instead of `width`.

https://user-images.githubusercontent.com/101464991/191607778-6dab0697-5836-4f07-a502-7cb0429e0747.mov

**Comment by bdougie** [comment]
Simplifying this with https://github.com/open-sauced/insights/issues/412
