### ISSUE TITLE
bug: Contributor languages should be relative to the amount of code (in that language) they've written in last 30 days

### ISSUE THREAD

**Issue by pixelsbyeryc** [open-sauced/insights#531]
## Summary

This is most likely to do with how the API is sending us data...

Our current implementation of the Contributor Languages seems a bit off to me. If we compare it to other services, like the one TED uses on his README, or the UI GitHub uses for repositories, ours seems off.

| @0-vortex's Profile | From Insights Repo | Our implementation |
| --- | --- | --- |
| ![Screen Shot 2022-10-12 at 3 57 19 PM](https://user-images.githubusercontent.com/101464991/195425545-3e87104a-c017-4667-bfe9-593965967170.png) | ![Screen Shot 2022-10-12 at 3 57 31 PM](https://user-images.githubusercontent.com/101464991/195425580-cc03c5db-910f-479a-8c2b-26bb87ac439f.png) | ![Screen Shot 2022-10-12 at 3 56 00 PM](https://user-images.githubusercontent.com/101464991/195425294-cfea550e-6ced-4793-964d-dce11e988e8a.png) |
| Shows percentages on each language relative by what the user has written in X amount of time | Shows the percentage of languages relative to all of the files available in the repo | Shows top 5 languages equally distributed |

I'm not sure why this is happening, but it seems to be due to how the API is giving us the data.

I would expect something like:
- User has edited 32 javascript files, 10 markdown files, and 5 html files in all of his PRs in the last 30 days.
  - `javascript`: 68%
  - `markdown`: 22%
  - `html`: 10%
- User has edited 20 javascript files, 15 typescript files, 5 html files, 5 css files, 1 C# files, 1 markdown file, in all of his PRs in the last 30 days.
  - `javascript`: 42%
  - `typescript`: 31%
  - `html`: 10%
  - `css`: 10%
  - `other`: 7%

**Comment by chhristopher** [comment]
Bumping this for visibility.

**Comment by bdougie** [comment]
The languages should display a legend show the color and language. We should remove the hover to show. It is confusing users.

The colors and example is from GitHub. 
![image](https://user-images.githubusercontent.com/5713670/223118740-36287c8f-2719-49e7-a810-4ed4d4b5a3b5.png)

**Comment by 0-vortex** [comment]
> The languages should display a legend show the color and language. We should remove the hover to show. It is confusing users.
> 
> The colors and example is from GitHub. ![image](https://user-images.githubusercontent.com/5713670/223118740-36287c8f-2719-49e7-a810-4ed4d4b5a3b5.png)

On hover it should highlight/backdrop the language hovered over in the textual flex list, not sure this effect is present on github but I think I saw it somewhere 🍕

**Comment by OgDev-01** [comment]
This needs a new component to actually reduce getting scope creep... We have this in the contributor's card, and I'm sure the current version will remain as is on the contributor's card
