### ISSUE TITLE
Constrain available topics to predefined list

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/insights#533]
> From talking with @bdougie there would be an "official" list of around 7 topics, but I think the goal is to always be specific and not be a wildcard search.

On top of my head, the topics would be ideal defaults
- JavaScript
- Rust
- Python
- ml (machine-learning)
- ai
- React

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/528#issuecomment-1276506004_

**Comment by bdougie** [comment]
Suggesting that we have a similar dropdown as the filters

![Screen Shot 2022-12-14 at 1 52 45 PM](https://user-images.githubusercontent.com/5713670/207722955-18b6742a-1da1-4665-bece-0c126d82e4a4.png)

**Comment by bdougie** [comment]
@Deadreyo let me know if you have enough to get started on this or do you need a design. The task is create a dropdown for the topics. Users are manipulating the URL to do this today and we should provide help to switch topics using the dropdown.
