### ISSUE TITLE
bug: Click to un-filter by repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#592]
### Describe the bug

This was reported by @sw-yx. When clicking a repo it filters, but he mentions its unintuitive. Perhaps this easter needs more context. 

![Screen Shot 2022-11-14 at 2 20 43 PM](https://user-images.githubusercontent.com/5713670/201783280-5f658f46-eda1-463d-94d0-ba4d241d4159.png)

### Suggested Solution
When a repo is filter, clicking that repo again should remove the filter. 

### Environment

Select the places where the issue can be reproduced (that you know of).

- [ ] Local
- [ ] Testing
- [ ] Development
- [ ] Production

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
The ask is to allow user to remove the filter when filter is applied. 

1. View repos tab
2. Click a name of a repo. 
3. note filters are applied
4. Click the name of the repo again.
5. note filters should be removed.

 
<img width="764" alt="Screen Shot 2022-12-18 at 7 04 39 AM" src="https://user-images.githubusercontent.com/5713670/208305647-ab2a85e9-b286-4e68-9395-9319eafdaf44.png">

**Comment by TAKANOME-DEV** [comment]
@bdougie something like this :arrow_down: 
You may want to mute the video because there is no sound, just noise. Sorry for that  :sweat: 
https://www.loom.com/share/ba8e93d47f5d457a8c22dadf22d7224d
