### ISSUE TITLE
feature: Save to dashboard feature

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#593]
![image](https://user-images.githubusercontent.com/5713670/208174623-096eaeb5-b6eb-44f9-b220-afcb6d8fde15.png)
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

When viewing the insights dashboard, a user should be able to click on a repo page to see more details.  Currently, we only show the repo tab, but it would be good to get custom page insights

### Suggested solution

We should nudge the user to create a custom dashboard by doing the following.

1. Sign in
2. Select a repo from the table or save to dashboard button

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

related https://github.com/open-sauced/insights/issues/592

**Comment by bdougie** [comment]
<img width="366" alt="Screen Shot 2022-12-16 at 11 31 39 AM" src="https://user-images.githubusercontent.com/5713670/208174763-7020f19e-29b2-4be8-ab21-f0e662c6a70f.png">

## filter selected

Currently, users can click the repo name to filter for a single repo. It applies a filter to the URL for the user. Link example below.

https://beta.insights.opensauced.pizza/javascript/repositories/filter/i18next/i18next

## Add to Insights Page

This should send the user to the "create insights" page with the repos selected added to the shopping cart. 
<img width="1309" alt="Screen Shot 2022-12-16 at 11 35 23 AM" src="https://user-images.githubusercontent.com/5713670/208175416-8f1addf5-ec17-4e8b-bbed-d76a1ddec056.png">

**Comment by Deadreyo** [comment]
@bdougie so how will the "Filter selected repositories" button work with multiple selections? Or do you just want the "Add to insight page" button?
