### ISSUE TITLE
feature: add last contribution date to the user profile

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#600]
https://github.com/open-sauced/ops-backend/issues/51

We need change this date to `first_opened_pr_at`
<img width="372" alt="Screen Shot 2023-05-16 at 10 32 14 AM" src="https://github.com/open-sauced/insights/assets/5713670/2d2d92f5-6d77-42a9-9dc8-df349fdb16d6">

**Comment by bdougie** [comment]
Thinking we can use a similar badge to what we have on the insights hub page. Something similar. 

![image](https://user-images.githubusercontent.com/5713670/209170805-2051a116-e682-46c1-9b77-09a3ad328daf.png)

**Comment by chhristopher** [comment]
@bdougie  Instead of “active” vs “whatever we label we use for casual” would it make sense if we put the number of days since last activity? Or somewhere along that line. I think that way we don't necessarily punish the casual contributor/user while also providing useful information. It's not perfect, but might be worth exploring?

**Comment by chhristopher** [comment]
Sorry, closed it. reopening

**Comment by bdougie** [comment]
That is a good idea. I think we can leverage last commit date per repo. Perhaps even "last seen"

**Comment by bdougie** [comment]
Here is a mock. The 🥤 should be replaced with a [commit icon](https://react-icons.github.io/react-icons/search?q=commit).

![e508b85a-fb22-4d9c-a529-e0e2aec626ba (2)](https://user-images.githubusercontent.com/5713670/209215677-e06ec1cd-5a19-4f81-8273-ea45f8064c58.png)

**Comment by chhristopher** [comment]
Yes! This is a great compromise between "active" and "casual".

**Comment by brandonroberts** [comment]
Fixed in https://github.com/open-sauced/insights/pull/1193
