### ISSUE TITLE
feature: Filter by column type on Repository screen

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#627]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Is your feature request related to a problem? Please describe.

When viewing the Repository page, it has been requesting users, the ability to filter by activity, pr count, etc.  

### Suggested solution

When the user clicks the column the data should sort ascending or descending. 

![Screen Shot 2022-11-30 at 4 27 14 PM](https://user-images.githubusercontent.com/5713670/204936738-2cbdd93c-44cd-4c6e-89d3-93c4acdd03a1.png)

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
@bdougie I would like to give it a shot

**Comment by bdougie** [comment]
Ok, still figuring out managing community contributions. Happy to assign this to you but this may need some API updates to filter the data. It might be best to take this in small steps and only sort by activity and repo name (alphabetically). You can do the UI (use clean design elements, i.e. Radix) to get UI up on a draft.

@brandonroberts what are your thoughts? Can we add sorting to the API?

**Comment by brandonroberts** [comment]
@bdougie @TAKANOME-DEV the API already supports sorting for the repos. You would need to provide an `orderBy` query param with one of the following values.

- stars
- owner
- name

`stars` is the default sort if none is provided

To provide a direction, provide an `orderDirection` query params with one of the following values

- ASC
- DESC

`DESC` is the default direction if none is provided

Let me know if you have any other questions.

**Comment by bdougie** [comment]
It looks like you can get started on this @TAKANOME-DEV. 

A user should be able to click on the column title and sort by ASC, when clicking again, it should be DSC. An arrow should appear next to the column indicating its ASC and DSC. It should also be added to the URL like `?sort=ASC`. 

Please note we use the design system to organize reusable components. https://github.com/open-sauced/insights#-storybook

**Comment by TAKANOME-DEV** [comment]
Hi, I need some help. I'm blocked by this.
The `onClick` handler that I passed to the `Tabletitle` component does not fire up at all when I click the colomn.
Draft PR -> https://github.com/open-sauced/insights/pull/662/files
```tsx
// components/organisms/Repositories/repositories.tsx
<TableTitle text="Repository" handleClick={() => console.log("clicked!")}  />

// components/atoms/TableTitle/table-title.tsx
interface TableTitleProps {
    text: string;
    className?: string;
    handleClick?: () => void;
}

const TableTitle: React.FC<TableTitleProps> = ({ className, text, handleClick }) => {

  return (
    <div className={`...`} onClick={handleClick}>
      {text}
    </div>
  );
};
```

**Comment by brandonroberts** [comment]
@TAKANOME-DEV are the click handlers working on the surrounding elements?

**Comment by TAKANOME-DEV** [comment]
Yeah @brandonroberts , it does work for the `setLimit` handler
```tsx
//components/organisms/Repositories/repositories.tsx
const {
    // this `setLimit` is working fine
    setLimit,
   // but not the orderBy
    setOrderBy
  } = useRepositoriesList(true, repositories);
...
return (
<TableHeader
         // pass down here
        updateLimit={setLimit}
        title="Repositories"
      />
)

// components/molecules/TableHeader/table-header.tsx
const TableHeader = ({
  updateLimit,
}: TableHeaderProps): JSX.Element => {
  return (
    <div className="...">
      <div className="...">
        <Select
          // used here
          onChange={function (limit: number): void {
            updateLimit(limit);
          }}
        ></Select>
      </div>
    </div>
  );
};
```

**Comment by brandonroberts** [comment]
@TAKANOME-DEV Ahh I see the issue. There repositories table has 2 different layouts for mobile/desktop. Your click handler is most likely on the mobile layout, the other one is here https://github.com/open-sauced/insights/blob/beta/components/organisms/Repositories/repositories.tsx#L79

**Comment by bdougie** [comment]
Reopening to try again. The first implementation was client side only and introduced unintentional bugs.

**Comment by nickytonline** [comment]
Relates to https://github.com/open-sauced/app/pull/2472/files#diff-9f367a6fd0d5a16b4c994858c85acc277de37bb7aac93e8ee5c336797ec82c27 where the new Table components were added. This was a starting point to integrate something like [TanStack Table](https://tanstack.com/table/latest) for sorting.

**Comment by brandonroberts** [comment]
To note, some of the columns we can't sort directly through the API, so we'll have to figure out which ones make sense
