### ISSUE TITLE
feature: Verified user profile

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#634]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

This needs hover cards before starting work on this.

https://github.com/open-sauced/insights/pull/607

### Suggested solution

![image](https://user-images.githubusercontent.com/5713670/209154859-a9cbd869-6fe7-4a42-ac56-42112da245b3.png)

Data for this profile page will be needed to be enhanced using api.opensauced.pizza. We will need to fetch the user's location and bio data securely.

https://app.campsite.design/opensauced/posts/txry47wjzpxf

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

### Roadmap

- [x] #713
- [x] #714
- [x] #715
- [x] #716
- [x] #717
- [x] #718
- [ ] #719
- [ ] #600
- [x] #837

**Comment by bdougie** [comment]
@SunGoldTech after #695 merges, we will need to add a check that confirms if the user has an opensauced account in the database. If yes, they will see this design, if not, they will see the generic design.

**Comment by brandonroberts** [comment]
The API end point for this is ready.

https://beta.api.opensauced.pizza/#/User%20service/findOneUserByUserame

It will return the user if found in our data, and returns a 404 error if not found
