### ISSUE TITLE
bug: Status button in footer leads to 404 location

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#656]
### Describe the bug

The status button in the footer leads to an endpoint in the api that returns 404.
### Steps to reproduce
Describe how to reproduce the behavior.

Click on "Status" button in the footer

### Environment

Select the places where the issue can be reproduced (that you know of).

- [ ] Local
- [ ] Testing
- [ ] Development
- [ ] Production
- [x] All

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This should also be opened in https://github.com/open-sauced/status.opensauced.pizza.

For now, we can link to the repo's [README](https://github.com/open-sauced/status.opensauced.pizza/blob/main/README.md)

**Comment by Deadreyo** [comment]
> This should also be opened in https://github.com/open-sauced/status.opensauced.pizza.
> 
> For now, we can link to the repo's [README](https://github.com/open-sauced/status.opensauced.pizza/blob/main/README.md)

But we have a status page service existing https://github.com/open-sauced/status.opensauced.pizza

**Comment by Deadreyo** [comment]
> This should also be opened in https://github.com/open-sauced/status.opensauced.pizza.
> 
> For now, we can link to the repo's [README](https://github.com/open-sauced/status.opensauced.pizza/blob/main/README.md)

shouldn't we link it to http://status.opensauced.pizza/ ?

**Comment by bdougie** [comment]
Yes

**Comment by 0-vortex** [comment]
> > This should also be opened in https://github.com/open-sauced/status.opensauced.pizza.
> > For now, we can link to the repo's [README](https://github.com/open-sauced/status.opensauced.pizza/blob/main/README.md)
> 
> shouldn't we link it to http://status.opensauced.pizza/ ?

Technically `https://open-sauced.github.io/status.opensauced.pizza/` but the end result is the same. The github pages sourced link is more FOSS 🍕

**Comment by ThePromiseBenard** [comment]
.take

**Comment by bdougie** [comment]
Hey @ThePromiseBenard. This is a quick fix, and I went ahead and assigned you. Please let me know if you are able to turn this around before Monday.

**Comment by ThePromiseBenard** [comment]
Hello, @bdougie. Thanks for assigning it to me, sure I will be able to turn it in before Monday.

**Comment by ThePromiseBenard** [comment]
Hello @bdougie, which is the correct link?

This  https://github.com/open-sauced/status.opensauced.pizza  or   http://status.opensauced.pizza/

**Comment by bdougie** [comment]
Lets go with http://status.opensauced.pizza/
