### ISSUE TITLE
bug: User shouldn't be asked to complete the onboarding when it's already done on the prod app

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#657]
### Summary
After I logged in with Github and completed the onboarding in the [insight plateforme](https://insights.opensauced.pizza), I cloned the project and start the dev server. Then, I connected with github **again** and after that, I'm asked to complete the onboarding one more time.

### Expectation
I expected to automatically get connected after I started the dev server and not asked to complete the onboarding step.

### Steps to reproduce

Describe how to reproduce the behavior.
1. Visit the insight plateforme at -> https://insights.opensauced.pizza
2. Click `connect with github` button to authenticate with Github
3. Clone, install the dependencies and start the project
4. Click the `connect` button to authenticate one more time
5. See the `Complete the onboarding` next to your avatar

### ScreenShots
| ![insights_1](https://user-images.githubusercontent.com/79809121/207655938-4294f756-2445-4f37-98ad-b8a1b401384d.png) | ![insights_2](https://user-images.githubusercontent.com/79809121/207661004-1c65bb44-ae9e-4e00-9fcf-b8d2c20b2814.png) |
| --------- | --------- |

### Environment

Select the places where the issue can be reproduced (that you know of).

- [x] Local
- [ ] Testing
- [ ] Development
- [ ] Production

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Prod and local development use different databases, which is why you wouldn't be onboarded using local development.
