### ISSUE TITLE
bug: Search box font size does not match

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#660]
### Describe the bug
![Screen Shot 2022-12-14 at 1 38 38 PM](https://user-images.githubusercontent.com/5713670/207720518-1be83fbd-4006-4081-9a56-8b8f0a7c7810.png)

Recommendation is that "Search Repositories" matches the font size of "Showing"

### Steps to reproduce

Describe how to reproduce the behavior.

Visit the repositories tab to find the search box.

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This was noticed on https://github.com/open-sauced/insights/pull/659 but it was present prior.

**Comment by favourite1975** [comment]
please has it been fixed?

**Comment by SunGoldTech** [comment]
> please has it been fixed?

Hey @favourite1975, this has not been fixed yet, Let me know if you wanna take this on 👍
