### ISSUE TITLE
feature: Add an "Explore" link in nav

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#661]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

![Screen Shot 2022-12-14 at 1 40 25 PM](https://user-images.githubusercontent.com/5713670/207721025-7bfef630-b523-49db-b6de-f1e501442993.png)

### Suggested solution

Link to "https://insights.opensauced.pizza/javascript/dashboard/filter/recent"

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by NsdHSO** [comment]
.take

**Comment by bdougie** [comment]
@NsdHSO because this project has a defined roadmap and team we are not enabling the .take command here. However, because you are on the @open-sauced/triage team you should be able to assign yourself using the GitHub feature. 

This is not documented yet, but we can only take contributions from OpenSauced Triage, Committers, and Maintainers **for now**. We suggest folks not on the team open issues and take a look at the [Bugs](https://github.com/orgs/open-sauced/projects/6) or [Papercuts](https://github.com/open-sauced/insights/issues?q=is%3Aopen+is%3Aissue+milestone%3APapercuts).
