### ISSUE TITLE
feature: Add Global hovercard support for avatars

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#664]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Is your feature request related to a problem? Please describe.

We have avatars of contributors across several pages and nothing happens when they are hovered on

### Suggested solution

Describe the solution you'd like.

TL;DR is to have a GitHub-like hover card display pieces of information about the contributor exactly as in the image below
<img width="422" alt="image" src="https://user-images.githubusercontent.com/62995161/207949248-275309ac-6f8e-43bf-80d3-5484606c2f00.png">

### Notes:

- The hovercard component is available in the design system from https://github.com/open-sauced/insights/pull/607 , a good approach will be to use Radix Ui [HoverCard](https://www.radix-ui.com/docs/primitives/components/hover-card) and customize to be reusable
- Similar implementation has been done https://github.com/open-sauced/insights/pull/501

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
@OgDev-01 doesn't this issue already resolved by https://github.com/open-sauced/insights/pull/742?

**Comment by OgDev-01** [comment]
This has been resolved @TAKANOME-DEV . I'm closing this right away
