### ISSUE TITLE
feature: active section link should be colored differently

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#671]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Follow-up of the issue: https://github.com/open-sauced/insights/issues/661
Currently there are 2 links in the nav, 1 for Insight Hub and 1 for Explore. They're both black all the time.

![image](https://user-images.githubusercontent.com/52013393/208173169-8ffaa226-cef9-465f-a0f8-a4927699433f.png)

### Suggested solution
When a user is in one of those sections, it's corresponding color should be highlighted.

![image](https://user-images.githubusercontent.com/52013393/208173221-3dc6987b-5f0d-43a9-98f1-f770090a8095.png)

**Comment by bdougie** [comment]
I'm afraid I have to disagree. I think the navigation between the Hub and Explore needs to be rethought. This Explore link is my design, but I'd like to see what @pixelsbyeryc's thoughts are on this. 

The Hub is a new page, but the Explore is not a new page but a new view of the Dashboard. 

How do we go from `pages` to `topics`?
