### ISSUE TITLE
Bug: overflow-x on the insights page

### ISSUE THREAD

**Issue by favourite1975** [open-sauced/insights#677]
### Describe the bug

![Screenshot from 2022-12-18 00-12-42](https://user-images.githubusercontent.com/72051159/208269528-468a868b-9ad8-4864-a046-de62a6f92371.png)
there is an overflow on the insight page for the large screen views

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/react/repositories/filter/recent
2. drag left and right to see the error

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@favourite1975 thanks for opening this issue. Can you record a video or gif showing the error?

**Comment by favourite1975** [comment]
[Screencast from 12-18-2022 01:40:47 AM.webm](https://user-images.githubusercontent.com/72051159/208271688-01ce39a3-017c-4a39-bcc4-0d7f6045751e.webm)

**Comment by payn33** [comment]
.take
