### ISSUE TITLE
Feature: Contributor Stack should include hover card and expand

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#683]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2022-12-19 at 7 25 39 AM](https://user-images.githubusercontent.com/5713670/208513023-41a018e2-5bd3-4a7a-a1ca-b44d593804dd.png)

### Suggested solution

This is a screen grab from hot.opensauced.pizza. The UI should match the Insights hovercard. 

https://www.loom.com/share/8632c42584a247fb904727e5df1e7c22

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by chhristopher** [comment]
Definitely agree with matching the animations of what is shown in the loom link above. In addition, I'd love to see the same treatment with our contributor's chart somehow. I understand that it may be difficult given the limited real estate (once we start hitting the edges) but especially under popular repos, there are a lot of avatar overlaps and folks who get pushed beneath others.

<img width="350" alt="Screen Shot 2022-12-22 at 7 27 55 PM" src="https://user-images.githubusercontent.com/48575398/209265263-b0585296-3f5c-4ab7-8625-1b893e3fb0b6.png">

**Comment by bdougie** [comment]
This should use https://www.radix-ui.com/docs/primitives/components/hover-card @TAKANOME-DEV
