### ISSUE TITLE
Feature: PR velocity should not be represented in a %

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#684]
### Type of feature

🍕 Feature

### Current behavior

Currently, everywhere you see PR velocity it shows as a green percentage. It should instead be accompanied with the merge icon. 

PR velocity is the percentage of PRs in the filtered date period that have been merged.

## Insights Hub
![Screen Shot 2022-12-19 at 7 25 54 AM](https://user-images.githubusercontent.com/5713670/208536884-f7137500-f074-4338-8ca7-381991b49557.png)

## Repository tab
![Screen Shot 2022-12-19 at 7 25 47 AM](https://user-images.githubusercontent.com/5713670/208536894-36f2cf5f-87f8-4bc1-a8b6-ad7bb5b1ef5e.png)

## Insights Hub
<img width="1413" alt="Screen Shot 2022-12-19 at 2 19 02 PM" src="https://user-images.githubusercontent.com/5713670/208537778-73a214ec-c856-48cc-ad0b-146a382afc6e.png">

1. Change from green to purple
2. Remove % and change to merge icon

merge icon can be found in the PR lists
![Screen Shot 2022-12-19 at 2 21 12 PM](https://user-images.githubusercontent.com/5713670/208538047-64820113-57ce-475b-8656-fd0e2be52acc.png)

## Repository list
![Screen Shot 2022-12-19 at 2 23 20 PM](https://user-images.githubusercontent.com/5713670/208538394-c8a87916-b64d-4bc4-81ab-78a9747999ee.png)

1. Remove the % and circle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Deadreyo** [comment]
@bdougie I think a better name should replace "PR velocity" since I would have never guessed it means accepted PRs

**Comment by mtfoley** [comment]
Another phrasing might be "hit rate".
