### ISSUE TITLE
Feature: Share button

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#686]
### Type of feature

🍕 Feature

### Current behavior

A user needs to copy the link the URL bar to share their insights page. 

### Suggested solution

The share button should show if the insights pages are marked as public. The functionality should copy the link to the clipboard for now (toast notification). In the future, we should open a settings window with options. 

This will also need a social card.

- [x] #687

![Insight Page - Repositories - Period v04](https://user-images.githubusercontent.com/5713670/208541966-67697b37-e8ed-41c8-a4f4-a57022f2951e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by payn33** [comment]
Hi @bdougie can i work on this?

**Comment by bdougie** [comment]
> Hi @bdougie can i work on this?

This needs a custom social card for pages. Linked in the OP.

I've added you to the @open-sauced/triage team allowing you to assign yourself to Papercuts.

Take a look at the [Bugs](https://github.com/orgs/open-sauced/projects/6) or [Papercuts](https://github.com/open-sauced/insights/issues?q=is%3Aopen+is%3Aissue+milestone%3APapercuts). If you would like to find **good first issues**, please check out the companion project to this, [open-sauced/hot](https://github.com/open-sauced/hot/issues)._

**Comment by bdougie** [comment]
The share icon should be https://primer.style/octicons/copy-16

Other than that, this is ready to work on. Clicking the button should copy the link to the user's clipboard and present a toast message stating "Link Copied"

**Comment by Themesses** [comment]
.take

**Comment by bdougie** [comment]
So this has evolved now that we have sharing in highlight and #687. The ask is to add a button (ellipsis on mobile) that shows the sharing list.  

## Highlights

![Screen Shot 2023-04-11 at 2 02 36 PM](https://user-images.githubusercontent.com/5713670/231287881-a237f002-95f7-479d-8a6b-8e7d7f10f251.png)

## Dev.to

Forem uses a share button on their pages as well. Another place to reference the use case.

![Screen Shot 2023-04-11 at 2 02 59 PM](https://user-images.githubusercontent.com/5713670/231287994-8857c7c4-3586-496a-80ae-15d5ec5e7668.png)

https://github.com/forem/forem/blob/main/app/javascript/packs/articlePage.jsx#L58-L83

**Comment by takanome-dev** [comment]
@bdougie isn't this issue supposed to be fixed by #1126?

![share-btn-2](https://user-images.githubusercontent.com/79809121/235537606-3ea91021-76f4-4aa8-95bb-2dabae36d5ed.png)

**Comment by bdougie** [comment]
Yes.
