### ISSUE TITLE
Feature: Public/Private insights badge

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#688]
### Type of feature

🍕 Feature

### Current behavior

There is no badge identifying if a dashboard is public or private

### Suggested solution

Add a badge that checks and displays if a hub page is public or private

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5176%3A6423&t=jZIlELgoFGnOMY8Y-0

<img width="1440" alt="Insight Page - Repositories - Period v04@2x" src="https://user-images.githubusercontent.com/5713670/208544051-dc71f66b-6df9-4b86-a3d7-74819b6b1462.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by payn33** [comment]
@bdougie can I work on this?

**Comment by bdougie** [comment]
I went ahead and added you to the @open-sauced/triage team. If you are able to assist in triaging and fixing future bugs, I would love your assistance. 

For this feature, please ensure to leverage the design system and ask questions. I have assigned you to the issue.

**Comment by payn33** [comment]
Alright i'll be sure to ask questions on anything I'm not clear on, thanks.

**Comment by bdougie** [comment]
Can you also me a message in the discord, so I can coordinate your roles there?

**Comment by payn33** [comment]
> Can you also me a message in the discord, so I can coordinate your roles there?

Hi @bdougie, i've opened a pr for this issue and sent a message on discord.
