### ISSUE TITLE
feature: close select limit modal when the outside is clicked 

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#689]
### Type of feature

🍕 Feature

### Current behavior

Currently, when the button `Showing: 10 per page` is clicked, it shows different options to choose.
When clicking outside of that select options (or modal), it doesn't close it unless an option is selected or the button is clicked again.

![select](https://user-images.githubusercontent.com/79809121/208548727-6bf30f97-99fd-4408-a9b0-c468073db59f.png)

### Suggested solution

Adding an event listener to check if the menu is open and the clicked target is not within the menu.
Here is an example of integration: https://github.com/open-sauced/insights/blob/c7430d7265b5654e8ef65a83b1877f8a16bb7ac7/components/molecules/SuperlativeSelector/superlative-selector.tsx#L26-L47

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
The current implement is not accessible, and this solution prescribed would work, but seems like a band-aid. I'd suggest introducing an accessible component from Radix-UI

https://www.radix-ui.com/docs/primitives/components/dropdown-menu

**Comment by TAKANOME-DEV** [comment]
@SunGoldTech do you think the `@supabase/ui` Select is needed or it can be removed?
The `custom-select`  atom should probably be updated  by using `radix/dropdown`

**Comment by SunGoldTech** [comment]
It should be replaced with radix component on this issue

**Comment by TAKANOME-DEV** [comment]
What about Supabase select?
