### ISSUE TITLE
Feature: Generic OpenSauced profile needs to match design

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#692]
### Type of feature

🍕 Feature

### Current behavior

Current:

<img width="1840" alt="Screen Shot 2022-12-20 at 7 52 14 AM" src="https://user-images.githubusercontent.com/5713670/208709029-d46d2230-e5c3-4064-a76e-ce5db16aa779.png">

### Suggested solution

Design:

![image](https://user-images.githubusercontent.com/5713670/208709068-80514563-a25f-4b05-8e72-eb16fd3f2d57.png)

### Additional context

@SunGoldTech can you assist in increasing the contribution calendar's width and height? https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5206%3A5781&t=VyhaHubG5373bwBm-0

We also need to figure out how to get that roll up data in the element as well

<img width="523" alt="Screen Shot 2022-12-20 at 7 58 01 AM" src="https://user-images.githubusercontent.com/5713670/208710271-4dda6b93-87a4-4217-a570-c62c32f0dd81.png">

I don't think we will need to do "PRs reviewed"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by SunGoldTech** [comment]
@brandonroberts mentioned on slack that the data needed for that row is now available from the API. Implementation will be done separately from this issue
