### ISSUE TITLE
Bug: Broken User Avatar On Nav

### ISSUE THREAD

**Issue by ThePromiseBenard** [open-sauced/insights#694]
### Describe the bug

Below is a screenshot of how it looks currently.

<img width="159" alt="image" src="https://user-images.githubusercontent.com/87343924/208782699-effdbda9-e138-419c-997c-b40b4cc135d1.png">

### Steps to reproduce

1. Go to https://beta.insights.opensauced.pizza/
2. Click on connect to GitHub on the top nav
3. Approve connection
4. Once approved, check the top nav to see the broken avatar

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile, Tablet

### Browsers

Chrome

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
@ThePromiseBenard  Did you try to reconnect after disconnecting the GitHub account? Still, getting the issue?

**Comment by ThePromiseBenard** [comment]
@shamimbinnur yes I did. It still gives the same issue.

**Comment by OgDev-01** [comment]
I'm closing this as it has been resolved in https://github.com/open-sauced/insights/pull/755
