### ISSUE TITLE
Feature: Add PR details row data to generic profile page 

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#696]
### Type of feature

🍕 Feature

### Currently 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62995161/208791014-1aadc660-3366-4068-8631-1d4bed8c879b.png">

The PR details row was temporarily hidden due to shortage of data from the API, but the data needed for that row has been updated in the api and can be consumed from the frontend.

### Suggested solution

Unhide the row and implement the data features as seen in the image below
<img width="457" alt="image" src="https://user-images.githubusercontent.com/62995161/208791384-bd2f950e-74b0-4ffd-9c79-75aea3dd6f31.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SunGoldTech** [comment]
@bdougie , feel free to include more context on thia issue 🙏
