### ISSUE TITLE
Feature: Active nav link support

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#697]
### Type of feature

🍕 Feature

### Current behavior

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/62995161/208844216-73ea67f4-3e7a-4823-a6fd-59794863b1c4.png">

It's quite difficult for users to know where they currently are through the Nav links as they are no support for active link styles

### Suggested solution

Style the active link to be the brand's orange color, similar to the image below
<img width="794" alt="image" src="https://user-images.githubusercontent.com/62995161/208845459-037270ad-3478-4e2d-bff5-f8d2705d72fc.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by chhristopher** [comment]
Yes! This is a simple 'feature' but such an easy win and a QOL improvement

**Comment by SimranjitKaurMaan** [comment]
.take

**Comment by bdougie** [comment]
Checking in here @SimranjitKaurMaan. I think all we need to do is highlight the active link orange for now.

**Comment by enaughton** [comment]
On it.

**Comment by diivi** [comment]
take.

**Comment by diivi** [comment]
.take
