### ISSUE TITLE
Bug: generic profile page not displaying contributors contributions 

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#698]
### Describe the bug

Generic profile page showing no history of contributions from
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/62995161/208848733-b1317246-bbd4-4067-83d2-cb0fafa2ceb8.png">

And data is available in contributors page for same contributor
<img width="459" alt="image" src="https://user-images.githubusercontent.com/62995161/208848610-b35e5c34-b527-42c5-a961-aeb3e343d112.png">

### Steps to reproduce

1.  Connect to GitHub and create an insights page
2. open the insights page and select any contributor from the chart on the dashboard
3. cross-check contribution history with that on the contributions page

### Affected services

opensauced.pizza

### Platforms

Desktop, Mobile

### Browsers

Chrome

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This will be solved and be more consistent when we switch our infra
