### ISSUE TITLE
Feature: Make the entire 'next button/go to insight page' clickable, not the inner icon only.

### ISSUE THREAD

**Issue by shamimbinnur** [open-sauced/insights#701]
### Type of feature

🍕 Feature

### Current behavior

At the moment the entire "next/go to insight page" button is not clickable. I have to forcefully take the mouse pointer exactly on the inner icon to click. I think is kinda inconvenient for the user experience.

Steps to reproduce the scenario:

1. Connect with GitHub.
2. Click "Add insight page"
3. Fill up the form with a page and repository full name.
4. Add repository
5. Click "Create page".

Then you will get the "next button/go to insight page".

https://user-images.githubusercontent.com/48399373/208898264-5ab2ad13-8946-4e14-8e82-2f4c41815662.mov

### Suggested solution

1. Fill the blank space of the button with padding around the icon.
2. Set the onClick listener on the parent element that wraps the icon.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SimranjitKaurMaan** [comment]
.take

**Comment by bdougie** [comment]
Checking in on this @SimranjitKaurMaan. Let me know if you have bandwidth for this.
