### ISSUE TITLE
Bug: The per page dropdown does not work

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#704]
### Describe the bug

<img width="804" alt="Screen Shot 2022-12-21 at 1 42 07 PM" src="https://user-images.githubusercontent.com/5713670/209008518-7052679d-06cf-4ca9-9ac2-2cbfa970d73c.png">

### Steps to reproduce

1. Navigate to repo list
2. Select 30 per page
3. Note there are still 10 per page 

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This is only an issue in beta.insights.opensauced.pizza. Not sure it's worth looking into.

**Comment by TAKANOME-DEV** [comment]
I'm currently updating that select option on #705. I will look into it and see if it can be handled in one PR

**Comment by Deadreyo** [comment]
> This is only an issue in beta.insights.opensauced.pizza. Not sure it's worth looking into.

After some playing around, if you re-order the list by clicking on Repositories label or Activity or any of those, it will fix itself. I guess this issue is related to #662 and would propagate to production if kept without fixing

**Comment by TAKANOME-DEV** [comment]
> > This is only an issue in beta.insights.opensauced.pizza. Not sure it's worth looking into.
> 
> After some playing around, if you re-order the list by clicking on Repositories label or Activity or any of those, it will fix itself. I guess this issue is related to #662 and would propagate to production if kept without fixing

I did mention it here -> https://github.com/open-sauced/insights/pull/662#issuecomment-1358090062, I'm not sure though if I did change something that makes this happened, but I will try to switch to a previous commit before that PR and investigate on the issue

**Comment by bdougie** [comment]
I can confirm this is bug on production now.

**Comment by TAKANOME-DEV** [comment]
I think it was in beta, but was introduced in main -> https://github.com/open-sauced/insights/pull/723

**Comment by bdougie** [comment]
We did a revert. The sorting and query params were breaking quite a bit. Opening a new issue soon https://github.com/open-sauced/insights/commit/5436712ce203bdb43c5f6fec92751c0d2bf711e2
