### ISSUE TITLE
Feature: Add a Suggested Repos section when creating new insight page

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#711]
### Type of feature

🍕 Feature

### Current behavior

As suggested by @bdougie , a suggested repos section in `/hub/insights/new` that is based on the user's organization and have suggestions for repos to be added to the page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
We should use the github API to view the user's last three watched repos that are public.

Alternatively we just add OpenSauced repos to the list.

- open-sauced/hot
- open-sauced/api.opensauced.pizza
- open-sauced/insights

**Comment by bdougie** [comment]
This is in [Figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=7217-9531&t=7l6pqRX0ogV90mMD-0) and ready for dev. 

![Image](https://user-images.githubusercontent.com/5713670/223799886-da6990e0-d7f4-4732-9455-fc7551affaf0.png)

**Comment by bdougie** [comment]
update suggestions should be statice for now. 

- open-sauced/insights
- cli/cli
- denoland/deno
