### ISSUE TITLE
feature: Add follow button to all user pages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#715]
This feature will allow folks to save contributor repos. This feature should be available to logged in users and force login when clicked. 

## Things needed
- API needs to be update to include follow on user table and a list of hearted users.
- The button should turn to unfollow when clicked. 

cc @pixelsbyeryc 

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5204%3A6170&t=T8av4JLONEnmJyCa-0

![Screen Shot 2022-12-22 at 11 40 31 AM](https://user-images.githubusercontent.com/5713670/209213485-6e0b40db-7f01-4a4f-947e-5fd2faa506c0.png)

_update: Instead of the "heart button," that was previously scoped, we are making this a follow button._

**Comment by OgDev-01** [comment]
@bdougie, Should this completely replace the `View on Github` button? 
![image](https://user-images.githubusercontent.com/62995161/228326532-e81756a1-5493-4e04-8357-43733f1f8cf5.png)

**Comment by bdougie** [comment]
Yes. View on GitHub was the compromise to put a button there.
