### ISSUE TITLE
feature: PR social cards for displaying recent work.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#716]
![Screen Shot 2022-12-22 at 7 27 39 AM](https://user-images.githubusercontent.com/5713670/209167434-2aa636e3-99a5-4964-b143-1c8619a2cce7.png)

This should start as a design component. 

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5204%3A6170&t=T8av4JLONEnmJyCa-0

**Comment by Deadreyo** [comment]
Any details or limitations I need to be aware of?
Like I assume it would be limited to only 2 PRs.

**Comment by Deadreyo** [comment]
Also I wonder if it would be better if, -unlike the current way of designing components in which we pass every prop explicitly- we would pass the whole PR data object and the component would internally extract the data it needs from it. (Would be more developer-friendly)

**Comment by 0-vortex** [comment]
> Also I wonder if it would be better if, -unlike the current way of designing components in which we pass every prop/data piece explicitly- we would pass the whole PR data object and the component would internally extract the data it needs from it. (Would be more developer-friendly)

Maybe not wanted humour but that is called [vue](https://vuejs.org/guide/introduction.html), ideally, we should *only* pass around the data that we need, and settle organisms at the top. Different ways to separate building blocks from static component from dynamic data components. In theory, 2 organisms with different interaction could call the same hook and re-use the same data, albeit it being fetched only once tho - that is the current design system to the best of my knowledge! 🍕
