### ISSUE TITLE
Feature: Hover and highlight contribution graph

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#721]
### Type of feature

🍕 Feature

### Current behavior

Today the contribution graph is static. It would be nice to hover over a point and find out how many commits or lines contribution(s) are at a single point.

### Suggested solution

Here is a version of what I am looking for with [tabler](https://preview.tabler.io/). 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5713670/209207028-16db79cc-d50a-4a79-afcd-da895dd19a14.gif)

### Additional context

note: this should update for appearances of the contribution graph. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by chhristopher** [comment]
<img width="872" alt="Screen Shot 2022-12-26 at 11 28 06 AM" src="https://user-images.githubusercontent.com/48575398/209578452-70601cd1-c9ba-412f-9c09-8262b4a1794b.png">
I like how Soundcloud displays comments along the song where folks contributed (commented) at the exact second. If we did something similar to this, like you mentioned, and show avatars along the graph (like the comments along the song), I think that would be a great feature.

**Comment by Deadreyo** [comment]
Are these the contribution graphs that is the target of this issue?
![image](https://user-images.githubusercontent.com/52013393/221542166-1f9729d5-5bec-4dda-abef-e44652a88c90.png)

**Comment by bdougie** [comment]
Yes. Also the contributions on the user profiles.

**Comment by deepakrudrapaul** [comment]
Will this work ?
![CPT2307202248-832x404](https://github.com/open-sauced/insights/assets/25549935/5a5d78ce-db4a-426b-91b9-74bef09963fe)

**Comment by bdougie** [comment]
I like. I think instead of just the number, 3. It should be "3 days ago"

**Comment by brandonroberts** [comment]
I agree with "x days ago"

**Comment by chhristopher** [comment]
Aside from the "x days ago" I like it.

**Comment by bdougie** [comment]
Another potential way is 1-7 days ago. Then the actual date, "Jul 17," which is how GitHub does it for their graph.

**Comment by deepakrudrapaul** [comment]
Thank you for the feedback and suggestions!  I believe "x days ago" would be the better option. It provides a more precise and concise representation of the timeline, making it easier for users to understand their contributions at a glance.
 
 Shall i go ahead and implement ?

**Comment by bdougie** [comment]
> Shall i go ahead and implement ?

Yes. That date format is used in the highlights card. You can most likely reuse some of that code.

**Comment by deepakrudrapaul** [comment]
.take
