### ISSUE TITLE
Feature: Force login component

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#722]
### Type of feature

🍕 Feature

### Current behavior

We need a generic component to apply to any component that blurs the feature and ask for a login. This only needs to be added to the design system. We will add this as an experiment in the future. 

### Suggested solution

The example is the contribution scatter chart, but this component should be flexible enough to blur any child component. 

![Screen Shot 2022-12-22 at 11 37 14 AM](https://user-images.githubusercontent.com/5713670/209213226-dcc16692-a5fd-4b67-8037-e77b92bfd60c.png)

[[Figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=441-874&t=CSlobWSNVftBnjsN-0)]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This should be a wrapper around an existing component that blurs the view and applies a connect github button.

**Comment by Deadreyo** [comment]
@bdougie the figma link is outdated.

**Comment by bdougie** [comment]
[[Figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=441-874&t=CSlobWSNVftBnjsN-0)] has been updated

**Comment by babblebey** [comment]
🤔

**Comment by babblebey** [comment]
I'm .take -ing this
