### ISSUE TITLE
Bug: Cient-side exception has occured when changing repo filters

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#726]
### Describe the bug

![image](https://user-images.githubusercontent.com/5713670/209376061-480a35bc-0e3d-4b4c-b5f1-c6e53d3b4f64.png)

### Steps to reproduce

Per @chhristopher from slack

> If you go to repositories tab  and add filter of top 100 repos, it leads to this error screen. 

### Affected services

opensauced.pizza

### Additional context

https://user-images.githubusercontent.com/5713670/209376420-0c05cafa-b7e5-4092-a34e-13b46229ac95.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by chhristopher** [comment]
Update: Changing repo filters as a whole triggers this error, not just 'Top 100' -- this was not the case earlier.
