### ISSUE TITLE
Bug: Removing all filters renders no repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#730]
### Describe the bug

<img width="804" alt="Screen Shot 2022-12-23 at 10 34 26 AM" src="https://user-images.githubusercontent.com/5713670/209392503-fa199adf-5313-4095-a9e4-691884e323a3.png">

### Steps to reproduce

1. Navigate to the Repositories list
2. Remove recent filter.

Note that this error is inconsistent and will work after a refresh or two. 

### Affected services

opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
@TAKANOME-DEV just FYI, we reverted https://github.com/open-sauced/insights/pull/662 in 
https://github.com/open-sauced/insights/commit/5436712ce203bdb43c5f6fec92751c0d2bf711e2 so we can investigate more on a different solution. 

This was causing the repository list to not re-render when changing the filters. We'll look to see if we can re-apply the changes in a future PR

**Comment by bdougie** [comment]
With this fixed, going to close this out. We can include context in a new issue, outling a better approach for sorting data.

**Comment by TAKANOME-DEV** [comment]
Sure thing :+1:
