### ISSUE TITLE
Bug: AvatarProps cannot be static data

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#732]
### Describe the bug

The `AvatarProps` in `Avatar` and `CustomAvatar` component cannot be static since we are sending that data to cloudinary. This makes the component render at all times, since the second one is string, even for potentially broken images.

### Steps to reproduce

visit https://insights.opensauced.pizza/ and check the console for broken images

### Affected services

insights.opensauced.pizza

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I understand there is an issue, but what is the resolution here? Looking at the props, are you referring to `StaticImageData`?

https://github.com/open-sauced/insights/blob/beta/components/atoms/Avatar/avatar.tsx#L6-L14

**Comment by 0-vortex** [comment]
> I understand there is an issue, but what is the resolution here? Looking at the props, are you referring to `StaticImageData`?
> 
> https://github.com/open-sauced/insights/blob/beta/components/atoms/Avatar/avatar.tsx#L6-L14

The conditional in https://github.com/open-sauced/insights/blob/d8028e57bc88d762357a4490583ac47de1f7ed12/components/atoms/Avatar/avatar.tsx#L88 requires one additional check, here the check itself is flexible, however, would personally create a [`new URL()`](https://nodejs.org/api/url.html#new-urlinput-base) around the `avatarURL` to ensure it is a real URL; prefer this solution because assume this wrapper component will need more logic and URL query string manipulation for the custom size, for example when requesting a "small" avatar, we should trim down the size of the requested image, which in some cases is parametrized in the actual fetch URL.

Opened a separate issue for the follow-up broken avatar, #733, but they are 2 different issues 🍕
