### ISSUE TITLE
Bug: New insight repo form is case sensitive

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#734]
### Describe the bug

Discovered by a user in our discussions

https://github.com/open-sauced/feedback/discussions/2#discussioncomment-4488401

> Hiya Brian @bdougie It still does not show up and takes me back to this discussion page to ask for it to be added.
> 
> Do you mind checking please after the holidays.
> 
> Thanks, Warren 😄

We should make this not case sensitive.

### Steps to reproduce

![IMG_0208](https://user-images.githubusercontent.com/5713670/209404214-21c2d6e4-0514-4036-a921-1bce6d28599a.png)

1. navigate to insights hub
2. create insights page
3. add `umbraco/umbraco-cms` - it doesn't work
4. Now add `umbraco/Umbraco-CMS` to another new page - it works

### Affected services

insights.opensauced.pizza

### Additional context

the filtering on the repo is not sensitive.  ![IMG_0207](https://user-images.githubusercontent.com/5713670/209404157-b4878135-d9b6-42db-9e41-f7bab660eb02.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
While the frontend should search for case-insensitive repos, the backend should mirror the github api and provide the same functionality; for that purpose opened up an issue in the public backend: https://github.com/open-sauced/api.opensauced.pizza/issues/76

It's not blocking coding current issue but it does block testing it.

**Comment by brandonroberts** [comment]
This has been resolved in the API
