### ISSUE TITLE
Bug: All contributor's card expands when one of them is clicked

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#741]
### Describe the bug

 When one of the contributor's card is clicked, all of them expand

![contribution-edit-1](https://user-images.githubusercontent.com/79809121/209584998-a40e362d-e904-42e6-8c5a-4f5bb27d2ef9.png)

### Steps to reproduce

1. Go to insights.opensauced.pizza
2. Click on the contributors tab
3. Click on "show latest pr" on any of the cards

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Other (add additional context)

### Environment

Production, Development

### Additional context

Browser: Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
The min-height is not a bug and is intentional. What is a proposed solution?

The duplication is a known issue we can solve when requesting users to create custom profiles. Though that should be opened on a new issue and has. https://github.com/open-sauced/insights/issues/541 

Perhaps we reopen that issue

**Comment by TAKANOME-DEV** [comment]
> The min-height is not a bug and is intentional. What is a proposed solution?
> 
Oh make sense, I was thinking about only expanding the one who was clicked. But it doesn't seem a good solution.
I would say that we keep the current implementation until we have better approach.
> 
> The duplication is a known issue we can solve when requesting users to create custom profiles. Though that should be opened on a new issue and has. https://github.com/open-sauced/insights/issues/541 
> 
> Perhaps we reopen that issue
>
Yeah, reopening that issue seems a good idea.

**Comment by TAKANOME-DEV** [comment]
Closing this issue for now until we have a better approach to handle the card expansion
