### ISSUE TITLE
Bug: correct multiple react versions

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#745]
### Describe the bug

React `16.8.0` and `17.0.2` to the requested `>=18`

### Steps to reproduce

1. clone the repo
2. `npm ci`

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
I cannot reproduce the bug or see warnings about different react versions. @0-vortex is this still present?

**Comment by 0-vortex** [comment]
> I cannot reproduce the bug or see warnings about different react versions. @0-vortex is this still present?

Think it was fixed with the `nextjs@13` upgrade that was shipped by Brandon, we only have `v18.2.0` right now! 🚀 🍕
