### ISSUE TITLE
Bug: Notification button isn't clickable

### ISSUE THREAD

**Issue by mohamedAdhamc** [open-sauced/insights#747]
### Describe the bug

![bugOpenSauced](https://user-images.githubusercontent.com/100296264/210016946-a1ffcab4-5a0e-47a4-8d6c-9f404ab32e99.png)

The notification button in the top right isn't clickable, but it shows there is a notification.

### Steps to reproduce

1- open page shown in image
2- try to click on the notification button

p.s. I'm using a linux version of chrome, not sure if its reproducible in other systems/versions.

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Hey @mohamedAdhamc, thanks for opening this issue. 

I don't think that the notification button is a bug, but rather it was added intentionally.
I'm not really sure why it was added, maybe @bdougie can shed some light on this.

**Comment by mohamedAdhamc** [comment]
> Hey @mohamedAdhamc, thanks for opening this issue.
> 
> I don't think that the notification button is a bug, but rather it was added intentionally. I'm not really sure why it was added, maybe @bdougie can shed some light on this.

Hey, no problem. Yes, I think maybe the logic for the button is yet to be made. Regardless, if it's not yet implemented I think it would be a bit better to default the icon to the notification icon, but that is just my opinion. Thanks !

**Comment by TAKANOME-DEV** [comment]
Good point, thank you for your feedback. We will take it into consideration.

**Comment by Njong392** [comment]
Hey, I just realized this too, and was about to create the same issue. I think it makes for better UX because I too clicked multiple times.

**Comment by TAKANOME-DEV** [comment]
Thank you for bringing this issue to our attention again, Emy.

I agree that the current behavior of the notification button can lead to a poor user experience.
I would suggest opening a new issue (maybe a feature request) and proposing changes that you believe would improve the user experience. 

Thanks again for your feedback

**Comment by bdougie** [comment]
No need for a new issue. I think we can solve this by keeping the icon and connecting opensauced to https://changefeed.app/.

we can leverage this to provide a changelog and notify the user when the app updates.

I will do some planning to make this approachable.

**Comment by TAKANOME-DEV** [comment]
Sounds great!

**Comment by bdougie** [comment]
I did some discovery on Changefeed (dead project) and some other tool and they are all really clunky requiring you to add a script tag. 

Supabase offers a realtime service that can connect a Notification table. I think in this case we use Supabase directly than a script tag service. We already pay for Supabase.

For now, I will do a PR to hide the notification bell and put this issue back in the queue to implement.

**Comment by getaheaddev** [comment]
i'll start working on this in about an hour

**Comment by getaheaddev** [comment]
We now have a notification design!

[[Figma file](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=178%3A526&t=IggKgB5nBNUMShqz-1)]

**Comment by bdougie** [comment]
> We now have a notification design!
> 
> [[Figma file](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=178%3A526&t=IggKgB5nBNUMShqz-1)]

Think that this is the wrong link @getaheaddev. Can you also share screenshots for folks that don't have User Flow access?
