### ISSUE TITLE
Feature: rework link usage

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#748]
### Type of feature

🍕 Feature

### Current behavior

changes in https://github.com/vercel/next.js/pull/36436 require an opt-in to keep using anchors or switch to the new behaviour

### Suggested solution

remove the wrapped `<a>` tags :pizz

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Would also be great if we make a base Link component in our `atoms` to be used across the application 😇. This will help keep the link usage consistent.

**Comment by takanome-dev** [comment]
Fixed on https://github.com/open-sauced/insights/pull/758
