### ISSUE TITLE
Feature: Design a Loading component to be used in components waiting for data

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#751]
### Type of feature

🍕 Feature

### Current behavior

Currently how the system is designed is that if a component is waiting for data, it will not show anything till it retrieves the data. It's better to have a Loading Component and use it when data is loading to give feedback to the user.

We have started implementing error / loading handling in #738 , which displays `<div> Loading... </div>` in case the data is still loading.

Idea credits to @0-vortex 

### Suggested solution

Make a component that indicates to the user that this thing is still loading and add it to Design system. (Storybook)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
We're using skeleton components for these currently

Example: https://github.com/open-sauced/insights/blob/beta/components/organisms/RepositoriesTable/repositories-table.tsx#L85

**Comment by bdougie** [comment]
The skeleton wrapper is all that is needed here.
