### ISSUE TITLE
Feature: Design an Error component to be used in components in which an error occurs

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#752]
### Type of feature

🍕 Feature

### Current behavior

This is mostly related to errors that may occur while fetching data for a component. Currently, we don't have proper error handling in the components, if an error occurs, the affected parts will just not be rendered. There should be an indication at that place that an error occurred.

We have started implementing error / loading handling in #738 , which displays `<div>Error Occurred</div>` in case an error occurred while fetching data.

Idea credited to @0-vortex 

### Suggested solution

Make a component that indicates to the user that an error has happened and add it to Design system. (Storybook)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
duplicated here https://github.com/open-sauced/insights/issues/781
