### ISSUE TITLE
Feature: improve custom select usage

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/insights#756]
### Type of feature

🍕 Feature

### Current behavior

our custom select using [radix select](https://www.radix-ui.com/docs/primitives/components/select) functions like a [radix drop-down](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) right now

### Suggested solution

implement the full extent of select components including arrows, scroll, tabbing, and improve the css design

### Additional context

https://github.com/open-sauced/insights/pull/705#pullrequestreview-1232548680

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I added a link to the comment that spawned this issue in the additional context section. 

Also, some more context is that we need to be conscious of how we implement some of the basic web UI elements. Radix is a preferred source for accessible components. We should question any PR introducing custom UI elements. 

re: this solution
The code exists in the [custom-select.tsx](https://github.com/open-sauced/insights/blob/beta/components/atoms/Select/custom-select.tsx). 

The [anatomy section of the docs](https://www.radix-ui.com/docs/primitives/components/select#scrollupbutton) layout all the missing elements we are not using. 

```
import * as Select from '@radix-ui/react-select';

export default () => (
  <Select.Root>
    <Select.Trigger>
      <Select.Value />
      <Select.Icon />
    </Select.Trigger>

    <Select.Portal>
      <Select.Content>
        <Select.ScrollUpButton />
        <Select.Viewport>
          <Select.Item>
            <Select.ItemText />
            <Select.ItemIndicator />
          </Select.Item>

          <Select.Group>
            <Select.Label />
            <Select.Item>
              <Select.ItemText />
              <Select.ItemIndicator />
            </Select.Item>
          </Select.Group>

          <Select.Separator />
        </Select.Viewport>
        <Select.ScrollDownButton />
      </Select.Content>
    </Select.Portal>
  </Select.Root>
);
```
