### ISSUE TITLE
Feature: Update avatar caching

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#757]
### Type of feature

🍕 Feature

### Current behavior

Currently, avatars shown in the chart are cached in Cloudinary, while the ones in the hover card are cached in the API. 
This can result in mismatched avatars being displayed on different pages of the site.

| ![avatar_1_edit](https://user-images.githubusercontent.com/79809121/210548463-d614e1cc-94cf-449e-a76e-6b0ef187f48f.png) | ![avatar_2_edit](https://user-images.githubusercontent.com/79809121/210548497-ebd5a53f-d86b-48a2-ba01-c6eb72335868.png) |
| --------- | --------- |

### Suggested solution

Maybe having a sort of consistent caching strategy for avatars across all pages of the site may solve this issue :thinking: 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
@TAKANOME-DEV there is no API cache, both the chart and hover images should be the same (left screenshot), while the big profile image (right screenshot) should be uncached from github cdn 🍕

**Comment by TAKANOME-DEV** [comment]
> @TAKANOME-DEV there is no API cache
>
Oh, I thought that there is some kind of API caching :sweat_smile: thanks for the clarification.

> both the chart and hover images should be the same (left screenshot)
>
Yeah, I agree with that.
Do you think that the avatar on the hover card should use the cloudinary image or the other way around?

**Comment by 0-vortex** [comment]
> > @TAKANOME-DEV there is no API cache
> 
> Oh, I thought that there is some kind of API caching 😅 thanks for the clarification.
> 
> > both the chart and hover images should be the same (left screenshot)
> 
> Yeah, I agree with that. Do you think that the avatar on the hover card should use the cloudinary image or the other way around?

We should use the existing cached image for now 🍕

**Comment by TAKANOME-DEV** [comment]
Ok. What about the contributor highlight card?
Now that my avatar is updated, if I use the existing cached image for the hover card, I get this :arrow_down: :

![avatar_updated_annotated](https://user-images.githubusercontent.com/79809121/210634241-75314d78-fde7-42cb-aa5c-0b228c6764a2.png)

IMH, it's not a big deal but just want to know your take on this.
> **Note**
>
I tried using the existing cached image for the contributor highlight card but hit some issues

![avatar_updated_issues](https://user-images.githubusercontent.com/79809121/210633343-cb4a17ec-e3d6-4bb5-844c-0bcb4e900a8b.png)

**Comment by 0-vortex** [comment]
@TAKANOME-DEV the second screenshot shows the stacked avatars are broken, not the highlight; can help debug this if you open a draft PR so we can check the deployment preview ❤️ 🍕

**Comment by TAKANOME-DEV** [comment]
The reason why those avatars are broken is that the `getAvatarLink` function return the Github avatar link, but does not include `www` in front of `github.com`.
Example: it returns something like `https://github.com/<username>.png?size=<size>` instead of `https://www.github.com/<username>.png?size=<size>`

@OgDev-01 the `cachedImage` and `roundedImage` utilities return a cached avatar, but different (see image below). Is there a reason why you used `cachedImage` over `roundedImage` on https://github.com/open-sauced/insights/pull/691/ ?

![avatar_caching_issues](https://user-images.githubusercontent.com/79809121/210914650-368c7a64-421f-4069-a098-7af5f8c59fb8.png)

**Comment by 0-vortex** [comment]
> The reason why those avatars are broken is that the `getAvatarLink` function return the Github avatar link, but does not include `www` in front of `github.com`. Example: it returns something like `https://github.com/<username>.png?size=<size>` instead of `https://www.github.com/<username>.png?size=<size>`

Unfortunately that is not the case, can understand this bugging, but it is not because of the `www`; if you `curl` or `wget` that URL without following redirect headers you will have a clear understanding of the problem. The solution is avoiding the redirect and using the correct github avatar link! 🍕 

`cachedImage` and `roundedImage` should functionally be the same thing and be used in tandem; the improvement cloudinary needs is the loader prop, however, that gets benched in `next@13` which is just around the corner. To clarify, they are both meant to round the image on cloudinary, the "cache" there is elusive and not meant to be a global/longterm option.

**Comment by TAKANOME-DEV** [comment]
> Unfortunately that is not the case, can understand this bugging, but it is not because of the `www`; if you `curl` or `wget` that URL without following redirect headers you will have a clear understanding of the problem. The solution is avoiding the redirect and using the correct github avatar link! pizza
> 
By "using the correct github avatar link" you mean `https://avatars.githubusercontent.com/u/<user_id>?s=<size>&v=4`?

> `cachedImage` and `roundedImage` should functionally be the same thing and be used in tandem; the improvement cloudinary needs is the loader prop, however, that gets benched in `next@13` which is just around the corner. To clarify, they are both meant to round the image on cloudinary, the "cache" there is elusive and not meant to be a global/longterm option.
>
Sorry, I didn't quite understand what you mean by "the improvement cloudinary needs is the loader prop, however, that gets benched in `next@13`"

**Comment by 0-vortex** [comment]
> By "using the correct github avatar link" you mean `https://avatars.githubusercontent.com/u/<user_id>?s=<size>&v=4`?

Yes

> Sorry, I didn't quite understand what you mean by "the improvement cloudinary needs is the loader prop, however, that gets benched in `next@13`"

The cloudinary nextjs usage is a little bit more streamlined: reading  https://cloudinary.com/documentation/nextjs_image_component_tutorial and https://next-cloudinary.spacejelly.dev should make the loader limitation more clear 🍕
