### ISSUE TITLE
feat: Insights Hub page Improvements

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#760]
- [x] #853
- [x] #852
- [x] #854
- [x] #855
- [x] Manually typing a repository without getting suggestions related to your inputs is not ideal even for devs… If we can add this feature, it would be a huge turn-up - https://github.com/open-sauced/insights/issues/789

**Comment by bdougie** [comment]
Added issues to the suggestions. Some need more context or a discussion.

**Comment by takanome-dev** [comment]
Are there any additional steps that need to be done here? All the tracking issues seem to be resolved :eyes:

cc @bdougie @OgDev-01
