### ISSUE TITLE
Bug: broken avatar when no results on page 

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [open-sauced/insights#777]
### Describe the bug

The insights page is showing broken avatar when no results are present on the page. 
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/9392954/212467838-570fecca-f070-459d-aa3e-b7611eda945b.png">

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/kotlin/repositories
2. Filter based on Most Spammed 
3. Broken avatar shows on the row.
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/9392954/212467901-c914c189-11ff-40c7-b12b-88709b1d4d89.png">

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SimranjitKaurMaan** [comment]
.take

**Comment by bdougie** [comment]
@SimranjitKaurMaan, thanks for opening this issue. Let me know if you'd like to join the @open-sauced/triage team so you can open issues and assign yourself.

https://github.com/open-sauced/.github/blob/main/TRIAGE_GUIDE.md

**Comment by SimranjitKaurMaan** [comment]
@bdougie Yes sure, I would like to join the triage team. Already raised request for it in [discord](https://discord.com/channels/714698561081704529/1063726642700242964/1063795470054457484).

**Comment by SimranjitKaurMaan** [comment]
Reopening the bug as the fix for this #778 is reverted

**Comment by SimranjitKaurMaan** [comment]
@brandonroberts The earlier fix for this issue was reverted [here](https://github.com/open-sauced/insights/commit/f6e30e1b875b2423c5f002ee954a7da4d4a786c1) . For this issue of broken avatar on the row when there are empty repo results, we need to fix just the broken avatar right? Let me know the expected behaviour.

**Comment by takanome-dev** [comment]
Filtering by `most spammed` causes the app to crash (on my side) :eyes:


https://user-images.githubusercontent.com/79809121/230748468-8e4a6553-1fc3-4de2-8cfd-5fcc62fdcffc.mp4

**Comment by takanome-dev** [comment]
@brandonroberts, when `listOfRepositories` is empty and `isFilteredRepoNotIndexed` is true, a runtime error occurs. Wondering if there is something wrong with the fix applied earlier for this

![filtering-bug](https://user-images.githubusercontent.com/79809121/230799003-88607157-3e9b-4490-aba6-3e92afa69641.png)

**Comment by brandonroberts** [comment]
@takanome-dev possibly. Open a new issue and let's discuss there

**Comment by takanome-dev** [comment]
Closing this in favor of #1086
