### ISSUE TITLE
Bug: contributor hover-card is not clickable

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [open-sauced/insights#780]
### Describe the bug

The contributor hover-card is not clickable when tried to click in the dashboard view
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/9392954/212485757-0d12571d-f54e-4d4f-9b3c-aa857041ffb9.png">

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/javascript/dashboard/filter/recent
2. Click on the dashboard view
3. hover on a contributor and try clicking on the contributor hover card.
4. contributor hover card cannot be clicked as the card disappears
![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiOGI3ZTA3ZjAtMWFkZC00ZGQxLTliOGUtODViYzY1NGJhMjQyIiwiZGVwbG95X2lkIjoiNjNjMmRjNjI2MWQyMzcwMDA5YzZlNWE2IiwiaWQiOiIxYjBiYWM1Zi01ZDFkLTRkZjQtOWJiMC0yYzdlNTRlZDdhZjcifQ==)

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
I think this has something to do with the nivo chart :thinking: cc @OgDev-01

**Comment by OgDev-01** [comment]
> I think this has something to do with the nivo chart 🤔 cc @OgDev-01

Yes @TAKANOME-DEV , a ticket has been opened in respect of this limitation on [Nivo](https://github.com/plouc/nivo/issues/2201)

**Comment by SimranjitKaurMaan** [comment]
Sure. @OgDev-01  Please help close this issue once the limitation on `Nivo` is taken care.
