### ISSUE TITLE
Feature: Error messages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#781]
### Type of feature

🍕 Feature

### Current behavior

When a user submits a form and an error occurs. We do not have a consistent error message style. 

<img width="767" alt="Screen Shot 2023-01-14 at 9 20 52 AM" src="https://user-images.githubusercontent.com/5713670/212486584-cc03960b-43b0-4ad8-ade7-14ac33144ca6.png">

Screenshot above is from  https://github.com/open-sauced/insights/pull/725

<img width="380" alt="Screen Shot 2023-01-14 at 9 24 02 AM" src="https://user-images.githubusercontent.com/5713670/212486685-807d3f56-9b2c-4559-a75e-cba38d156b8a.png">

The above is from the new [user settings page](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5619%3A5814&t=455oLoVYAx3UF7mV-0). 

### Suggested solution

We need a consistent component for the entire app. My suggestion is using either red text or red underlined text. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
I updated the error message design

Here's the links:

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=6858%3A8837&t=jppuVXHeIlugLy6f-1

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5619%3A5814&t=jppuVXHeIlugLy6f-1

**Comment by bdougie** [comment]
Can we add the error message to the Insights Pages

![Image](https://user-images.githubusercontent.com/5713670/221713564-7c0ef0a8-ef3c-4e05-815d-54487f8e8dc8.png)
