### ISSUE TITLE
Feature: Create `UserSettings` page component

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#783]
### Type of feature

🍕 Feature

### Current behavior

<img width="381" alt="image" src="https://user-images.githubusercontent.com/62995161/212685208-db38a29e-9b7a-4b18-a453-c32e16d55cf7.png">

<img width="173" alt="image" src="https://user-images.githubusercontent.com/62995161/212685740-2c103f7b-910a-4e1f-9b63-c1f9212d1ab2.png">

### Suggested solution

This should start on the design system first

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This is related and the interests (topics in the api) should mirror the list. https://github.com/open-sauced/gs-api.opensauced.pizza/issues/73
