### ISSUE TITLE
Feat: Search functionality to search repositories

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [open-sauced/insights#789]
### Type of feature

🍕 Feature

### Current behavior

1. Currently the search on repositories is not working, we need to be able to search for repositories.
2. Try searching for any repository in the search field, it should show the searched repository info.

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/9392954/212805267-acc4dd5f-1978-4a04-9fc7-c7af3349b200.png">

### Suggested solution

The way we can make it work is use the GitHub GraphQL or REST api to search for the repo, then once the user clicks on it, it would filter the search results.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SimranjitKaurMaan** [comment]
@0-vortex The specific search functionality seems to have been already present. Ref PR: #580 
But since there is no visual cue to add org/repo name, users will not be aware of this. 
I was thinking if we can add a placeholder like `org/repo` or something, it will help users to search. Please share your suggestions on this?

**Comment by brandonroberts** [comment]
Add a placeholder in the input for a full repo name, such as `open-sauced/insights` is a good idea

**Comment by bdougie** [comment]
Not advocating for Algolia usage, but they have an excellent example of this working. 

https://codesandbox.io/s/github/algolia/autocomplete/tree/next/examples/github-repositories-custom-plugin

**Comment by 0-vortex** [comment]
> Not advocating for Algolia (they are expensive) usage, but they have an excellent example of this working.
> 
> https://codesandbox.io/s/github/algolia/autocomplete/tree/next/examples/github-repositories-custom-plugin https://www.algolia.com/developers/code-exchange/frontend-tools/autocomplete-to-retrieve-github-repositories/

[GitHub search API](https://docs.github.com/en/rest/search?apiVersion=2022-11-28) !!! :D

**Comment by bdougie** [comment]
@SimranjitKaurMaan going to get design to assist on the visual for this.

**Comment by Deadreyo** [comment]
Search results must be related to the chosen topic though right? Like not just showing any repository

**Comment by Deadreyo** [comment]
![image](https://user-images.githubusercontent.com/52013393/217776250-222011ef-3e56-4040-ade6-591f8fd9e39a.png)
Wouldn't this limit apply to all of the unsigned insights users? Like 10 per minute shared across any users active simultaneously.

**Comment by 0-vortex** [comment]
> ![image](https://user-images.githubusercontent.com/52013393/217776250-222011ef-3e56-4040-ade6-591f8fd9e39a.png)
> Wouldn't this limit apply to all of the unsigned insights users? Like 10 per minute shared across any users active simultaneously.

That is correct, however the rate limit is per request, not per result, so we could likely get all the search results in 1 request, the user would have to complete a search every 5 seconds to actually trigger a rate limit and that is not accounting for server delays; a properly implemented type-ahead like in hot open sauced would do the trick! 🍕

**Comment by Deadreyo** [comment]
> That is correct, however the rate limit is per request, not per result, so we could likely get all the search results in 1 request, the user would have to complete a search every 5 seconds to actually trigger a rate limit and that is not accounting for server delays; a properly implemented type-ahead like in hot open sauced would do the trick! 🍕

but if we had for example 30 users using the website at once, if they all try to search, only 10 of them would get results, and would be just 1 time per minute.

**Comment by getaheaddev** [comment]
Does this still not work as desired?

**Comment by 0-vortex** [comment]
> Does this still not work as desired? @bdougie Everything seems to be working though I'm wondering if you're seeing something I'm not.

Display-wise it's good, the data is just not fetched from the correct endpoints :D

**Comment by Deadreyo** [comment]
Do we have a component that shows suggestions for a text input? We need to implement such feature in the Search component to show up the suggestions. @bdougie

**Comment by bdougie** [comment]
> Do we have a component that shows suggestions for a text input? We need to implement such feature in the Search component to show up the suggestions. @bdougie

Currently being worked on by @getaheaddev.

**Comment by 0-vortex** [comment]
> Do we have a component that shows suggestions for a text input? We need to implement such feature in the Search component to show up the suggestions. @bdougie

Copy from https://hot.opensauced.pizza

**Comment by bdougie** [comment]
@getaheaddev is working on this

**Comment by 0-vortex** [comment]
Saw the figma template, the search functionality is very on point even in the github API: https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-by-when-a-repository-was-created-or-last-updated

We can improve the dropdown by making repo details bigger or more visible in the dropdown, but the way we granulate it is pretty fixed :D

**Comment by chhristopher** [comment]
Bumping this @bdougie @brandonroberts. Says it has been resolved but we are still having the same issues with our search function.

**Comment by bdougie** [comment]
We just need a better search UI. We are fetching the wrong data when searching. 

This is something we can potentially solve with Elastic or similar https://github.com/open-sauced/ops-backend/issues/32
