### ISSUE TITLE
feat: implement `UserSettings` page

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#794]
> We should provide the list of timezones in the dropdown.
> 
> This should be in a lib - https://stackoverflow.com/questions/38399465/how-to-get-list-of-all-timezones-in-javascript
> Perhaps it can be done in a new PR though

Opening a new issue to implement the form functionality, and this can be included also🍕

_Originally posted by @OgDev-01 in https://github.com/open-sauced/insights/issues/788#issuecomment-1397268784_

**Comment by 0-vortex** [comment]
push back on timezones, we need to ensure we can use the location of the user, not enable them to pursue a job in their local timezone and select different time zone to pursue another. 

it has no value until we can safely translate the existing location information into timezones, and adjust the information displayed on website to match the selected timezone.
