### ISSUE TITLE
Dark pattern: User cannot not navigate to their profile.  

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#798]
### Type of feature

🍕 Feature

### Current behavior

<img width="306" alt="Screen Shot 2023-01-26 at 5 33 31 AM" src="https://user-images.githubusercontent.com/5713670/214848637-77272b2c-ffbd-4f7e-b185-ea2a63d2b076.png">

### Suggested solution

<img width="306" alt="Screen Shot 2023-01-26 at 5 33 31 AM" src="https://user-images.githubusercontent.com/5713670/214848847-c0892767-b54d-4e5a-9180-c2f5ac22e766.png">

This is a quick fix. A design is not needed. We need the link with the user name there. 

cc @OgDev-01 @getaheaddev 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
How about this?

| | |
| --- | --- |
| ![profile-normal](https://user-images.githubusercontent.com/79809121/214882023-8296b65d-7447-49f8-a3b0-55055b8db547.png) | ![profile-hover](https://user-images.githubusercontent.com/79809121/214882086-16fcfb1a-3f3e-4331-a57e-6b05ec70e71c.png) |
