### ISSUE TITLE
Feature: Onboarding needs interests instead of repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#801]
### Type of feature

🍕 Feature

### Current behavior

The current onboarding asks for repos and an org to be selected.  

<img width="525" alt="Screen Shot 2023-01-26 at 6 10 32 AM" src="https://user-images.githubusercontent.com/5713670/214857680-35054fbc-688c-4658-bcb2-1a20d90f9c44.png">

### Suggested solution

We should ask for interests from a predefined list. A user should be able to skip this step.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
I'll add interests to the design for onboarding

**Comment by bdougie** [comment]
once https://github.com/open-sauced/insights/pull/838 is merged, I would love to update the onboarding next

**Comment by Deadreyo** [comment]
There doesn't seem to be a "skip" button in the designs.
Also how can I view what's currently present? What's the url or how to reach that?

**Comment by bdougie** [comment]
> There doesn't seem to be a "skip" button in the designs.

Do you think skip is needed?

> Also how can I view what's currently present? What's the url or how to reach that?

/start change onboarded flag to false

**Comment by Deadreyo** [comment]
> Do you think skip is needed?
Quoting from the solution: > A user should be able to skip this step.
And in my personal opinion yes

**Comment by Deadreyo** [comment]
I am not sure what needs to be done. The current onboarding page and the stages are different from those in the designs.

**Comment by bdougie** [comment]
> I don't know what needs to be done. The current onboarding page and the stages are very different from those in the designs. Would love more clarification

Steps 2 and 3 are being updated to new questions. Step 1 should no longer ask for the "org"
