### ISSUE TITLE
Feature: Repo recommendations

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#802]
### Type of feature

🍕 Feature

### Current behavior

When a user shows up on their profile, they see 0 contributions. It would be nice to show recommendations for projects to contribute to. This should appear like an ad for folks with no or low contributions. 

We can show some up-and-coming projects and/or sell this as space for companies to highlight projects that need contributions. 

### Suggested solution

The goal here is to give a user with no contributions something to contribute to. 

GitHub's home page example lists projects with details. I am open to ideas, but this is a good patter to call out recommendations for contributions unobtrusively. 

I think we may want to list repos similarly with some copy. 

"Want to contribute to more places? Check out these trending repositories."

Above can be a link to a video or blog post on how to contribute for the first time.  

<img width="1548" alt="Screen Shot 2023-01-26 at 6 39 10 AM" src="https://user-images.githubusercontent.com/5713670/214864785-f3124f4b-c0e2-4743-943e-96e796b86c4d.png">

## Work

- [x] #1000
- [x] #1001

**Comment by 0-vortex** [comment]
IMHO Don't design this, leave it open for multiple contributions testing potential AI tools, before we roll our own relevancy system. Going the "see what works" route first would simplify design and limit lost features! 🍕

**Comment by getaheaddev** [comment]
This is not quite ready to be handed off but the design can be viewed on figma right now. Leave your comments.

[[Figma: Repo Recommendations](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=139%3A537&t=B0fmUuiTTS4HUVTm-1)]
