### ISSUE TITLE
Bug: Mobile view - context filter button has max-w-max, breaks out of container on long repo names and removes the cancel button

### ISSUE THREAD

**Issue by Themesses** [open-sauced/insights#805]
### Describe the bug

Long repo names cause the context filter button to break out of its container and lead to unintended horizontal scroll. Also, the cancel button is inaccessible when the component reaches the right margin. 
![IMG_3533](https://user-images.githubusercontent.com/43274289/214890192-4a6f95ee-97c3-4d99-ac55-7bd257d13ab7.PNG)

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/hot/repositories/filter/JoshuaKGoldberg/expect-no-axe-violations on mobile
2. Look at the header filter component and swipe sideways

### Affected services

insights.opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Nice catch @Themesses :clap: Feel free to give it a shot :rocket: 
I think the `take` action is available :thinking:

**Comment by Themesses** [comment]
.take

**Comment by bdougie** [comment]
@Themesses checking in to see if you have questions

**Comment by Themesses** [comment]
> @Themesses checking in to see if you have questions

@bdougie thanks for checking in. Just opened a PR. Apologies for the delay.
