### ISSUE TITLE
Bug: Mobile view - context filter button filter menu opens off-screen

### ISSUE THREAD

**Issue by Themesses** [open-sauced/insights#806]
### Describe the bug

When trying to access the filter menu on mobile, the menu opens off to the side - hiding most of the options

![IMG_C453C4A97F38-1](https://user-images.githubusercontent.com/43274289/214891774-61d24c3a-33ec-435a-837f-624c88493421.jpeg)

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/hot/repositories/filter/FeroxFoxxo/MQReawaken
2. Click on context filter button in the header
3. filter menu should be partially visible

### Affected services

insights.opensauced.pizza

### Platforms

Mobile

### Browsers

Chrome

### Environment

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Themesses** [comment]
Something I can take?

**Comment by TAKANOME-DEV** [comment]
Sure :)

**Comment by Themesses** [comment]
.take
