### ISSUE TITLE
Feature: add Toast support to application

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#809]
### Type of feature

🍕 Feature

### Current behavior

We have no toast implemented on the insights app

### Suggested solution

Just like we have in https://github.com/open-sauced/hot/blob/beta/src/lib/reactHotToast.ts... This should be added to the insights.

designs will be needed for the popup in four states: 

- success
- error
- warning
- and default

cc: @getaheaddev 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@OgDev-01 was this comleted?
