### ISSUE TITLE
Bug: Languages on profiles does not work

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#810]
### Describe the bug

Notice on @OgDev-01 latest PR when demoing at Techstars. When hovering on a language, there is no description. 

production:

<img width="348" alt="Screen Shot 2023-01-28 at 11 40 51 AM" src="https://user-images.githubusercontent.com/5713670/215287680-32a893b0-2293-4fdf-859a-ba492c116e85.png">

beta:

<img width="338" alt="Screen Shot 2023-01-28 at 11 41 55 AM" src="https://user-images.githubusercontent.com/5713670/215287687-3fcd0d9a-bd3d-429a-9a2b-cfb900f4a815.png">

### Steps to reproduce

Navigate to a profile and hover over a language. 

### Affected services

insights.opensauced.pizza

### Additional context

Probably something similar with the divs. It is not the data from the API though. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Changing the value of `withDescription` prop to `true` will fix this https://github.com/open-sauced/insights/blob/4a232c9b817de0b00711f9d7f3a3e294aeb6208c/components/organisms/ContributorProfilePage/contributor-profile-page.tsx#L93
