### ISSUE TITLE
Feature: Microformat SEO data per page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#814]
### Type of feature

🍕 Feature

### Current behavior

We are not making User profiles and Insight Pages friendly with SEO. 

related, https://github.com/open-sauced/insights/issues/687

### Suggested solution

Set up search engine enrichment data. Not sure what the solution is in next.js, but would love thoughts. 

Here is an article for Next.js - https://nextjs.org/learn/seo/introduction-to-seo

Context from Google - https://developers.google.com/search/docs/appearance/structured-data/search-gallery

### Additional context

cc @0-vortex 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
This needs implementing in every page, SEO + microformats 🍕
