### ISSUE TITLE
Feature: Beta tag

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#821]
### Type of feature

🍕 Feature

### Current behavior

We should add a beta tag on the profiles while they are still in progress. 

<img width="1543" alt="Screen Shot 2023-01-31 at 9 13 09 AM" src="https://user-images.githubusercontent.com/5713670/215834339-4a3e0dae-3af9-426b-822e-35b52de80f6f.png">

### Suggested solution

@getaheaddev and throw together a quick mock. We have two options 

1. use the same topic tag
2. use the pill selector

<img width="116" alt="Screen Shot 2023-01-31 at 9 16 30 AM" src="https://user-images.githubusercontent.com/5713670/215834838-63275986-8e0b-43db-86d5-c9f16b8b1563.png">

It should be grey and not red
<img width="125" alt="Screen Shot 2023-01-31 at 9 16 39 AM" src="https://user-images.githubusercontent.com/5713670/215834813-168370a9-b41d-443c-94b4-6d8e51bd1981.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
This is a nice catch 🍕

**Comment by getaheaddev** [comment]
Done ✅ @bdougie 
![Screenshot 2023-01-31 at 11 16 10 AM](https://user-images.githubusercontent.com/122071536/215847770-a4392cc3-8641-42b5-9f77-98a35454f4fc.png)

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5876%3A7583&t=R24oIhwcD3cC7R9s-1

**Comment by TAKANOME-DEV** [comment]
I have looked into the `pill` atom and I think maybe we should choose an alternative to how the colors are handled.
https://github.com/open-sauced/insights/blob/050a4b499380895926e759bf13ea87c5ab96713a/components/atoms/Pill/pill.tsx#L16-L24

if we want to use the pill atom to display this beta tag, another condition will be added, and the next time also, and so on...
Maybe defining some default styles and overriding them when needed would be a good approach or using [cva](https://github.com/joe-bell/cva#readme) to add different variants...

**Comment by OgDev-01** [comment]
Should this tag also display for non-open-sauced user's profiles?
cc: @bdougie

**Comment by bdougie** [comment]
no, only logged in users will see this.
