### ISSUE TITLE
Bug: Unable to edit my own insights page due to an unauthorized error.

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/insights#833]
### Describe the bug

I'm unable to edit my own insights page. It says I'm not authorized.

### Steps to reproduce

1. Create a new insights page
2. Once it's been created (public or private), click on the pencil button (edit)
 
![CleanShot 2023-02-03 at 11 09 46](https://user-images.githubusercontent.com/833231/216651935-2b060b33-d110-47c9-a2a5-ba428ad240cb.png)

3. The page loads with an unauthorized message.

![CleanShot 2023-02-03 at 11 13 21](https://user-images.githubusercontent.com/833231/216652189-c86ecdfb-c3bf-41d6-bcee-535ecd523cad.png)

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Other (add additional context)

### Environment

Production

### Additional context

Arc browser (Chromium based)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@nickytonline are you able to try logging out and logging back in? Might be a JWT thing.

**Comment by nickytonline** [comment]
I figured out what the issue is @bdougie. The user ID is a number, but in the meta data, it's a string, so the `!==` is true and that's why I'm getting the unauthorized.

![CleanShot 2023-02-03 at 11 22 17](https://user-images.githubusercontent.com/833231/216654438-2f1b69b7-1eec-4619-a8f2-5a540a84c90d.png)

**Comment by nickytonline** [comment]
I figured out what the issue is @bdougie. The `insight.user_id` is a number, but in the meta data, it's a string, so the `!==` is true and that's why I'm getting the unauthorized.

![CleanShot 2023-02-03 at 11 22 17](https://user-images.githubusercontent.com/833231/216654438-2f1b69b7-1eec-4619-a8f2-5a540a84c90d.png)

**Comment by nickytonline** [comment]
https://github.com/open-sauced/insights/blob/5bd4e48576d5f59b27d32eed4471f58c40a96082/pages/%5BfilterName%5D/insights/%5BinsightId%5D/edit.tsx#L28-L30

**Comment by nickytonline** [comment]
If it's a bigger job to rework the user metadata, you could do this for now with a TODO to fix metadata. If there is no user data, `Number(user?.user_metadata.sub)` will result in `NaN`, so still all good for the condition.

```jsx
if (insight && insight.user_id !== Number(user?.user_metadata.sub)) { 
   return <>Unauthorized</>; 
 } 
```

**Comment by brandonroberts** [comment]
@nickytonline That's a reasonable change to me

**Comment by nickytonline** [comment]
If that's the case, I think this would make for a great first PR. I'm not sure about the testing story though as I haven't dipped my toes in the Insights project yet.If tests are required, happy to pair with someone if they want.

**Comment by brandonroberts** [comment]
Agreed! No additional tests would be required in this case

**Comment by brandonroberts** [comment]
Just heads up @nickytonline as we had to push this through because of the production impact. Please follow-up with other findings!
