### ISSUE TITLE
feature: Make All Settings Editable

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#837]
Noticing that the user cannot update bio, twitter, etc. Also email & timezone does not stay updated when saved. 

All fields should be able to be updated.

<img width="1015" alt="Screen Shot 2023-02-07 at 7 12 32 AM" src="https://user-images.githubusercontent.com/5713670/217284585-29223f9a-52f8-4567-bf8a-7b3fc29905d4.png">

**Comment by bdougie** [comment]
@Deadreyo assigned you to this. If you could work on this next when you get a chance.

**Comment by Deadreyo** [comment]
Name field seems to be intentionally disabled. Is that intended? @bdougie

**Comment by Deadreyo** [comment]
- For email updating: A request is sent successfully to the server but still the email doesn't get updated in there.
- The current profile update endpoint doesn't take name, bio, url, twitter username, company or location.

**Comment by bdougie** [comment]
> Name field seems to be intentionally disabled. Should I keep it like that? @bdougie

Every input should be editable. Nothing should be disabled.
