### ISSUE TITLE
Bug: user profile page returns 404

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#844]
### Describe the bug

When i try to visit my profile, i get an error
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/62995161/217594089-8a834b53-4f78-4d57-a44b-9b4b6952f47d.png">

but if I change the username on the URL to all lowercase, I get to see the profile
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/62995161/217594466-51974b21-e056-4cce-ab03-5583c9601101.png">

### Steps to reproduce

Click and visit a user profile from the user whose username is not all lowercase

### Affected services

insights.opensauced.pizza

### Platforms

Desktop, Mobile

### Environment

Production, Development, Testing

### Additional context

converting users username to lowercase before plugin to any link will solve this issue :pizza:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Can confirm `https://insights.opensauced.pizza/user/0-Vortex` works ... my username doesn't have a capital V even :D

**Comment by TAKANOME-DEV** [comment]
Same here, notice how the ui looks different from mine (Firefox) :thinking: 

![Screenshot from 2023-02-08 21-31-53](https://user-images.githubusercontent.com/79809121/217655853-940d864a-bac4-47a6-8e9a-e98e4350517d.png)

**Comment by 0-vortex** [comment]
```const isError = contributorError || userError;``` could solve it, tho there are multiple inconsistencies on that page, router query username should also be lowercased, meta needs canonical tags for the actual user login in its original form 😅 

For not let's focus on just the bare minimum! 🍕

**Comment by OgDev-01** [comment]
i still get this error in production

**Comment by bdougie** [comment]
Try logging out and logging back in.

related? https://github.com/open-sauced/ops-backend/issues/27

**Comment by OgDev-01** [comment]
Still the same behavior
![image](https://user-images.githubusercontent.com/62995161/222460593-b42016e5-3ab3-4153-bd5a-ba6c03ad55d5.png)
I manually need to change the username in the URL to all lowercase for it to work
![image](https://user-images.githubusercontent.com/62995161/222461106-768433ae-de44-4225-83ee-2302bab2d9bc.png)

**Comment by brandonroberts** [comment]
I can't reproduce yet it with an incognito window. Both versions work.

![image](https://user-images.githubusercontent.com/42211/222467831-eae7b193-890e-4154-bf47-a01e0e5f54fc.png)

@OgDev-01 are you seeing any error messages in the browser console?

**Comment by OgDev-01** [comment]
I have confirmed in production 👍

**Comment by brandonroberts** [comment]
Confirmed fixed for me also
