### ISSUE TITLE
feature: Validations when creating a page, make the page title required with at least one repo

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#852]
<img width="804" alt="Screen Shot 2023-02-09 at 4 51 42 AM" src="https://user-images.githubusercontent.com/5713670/217818013-50fdd197-4a2b-46c1-9cb1-a169cc979716.png">

Solution:
- Make the page name a required field
- Disable the create page button until a name is added

<img width="1368" alt="Screen Shot 2023-02-09 at 4 54 16 AM" src="https://user-images.githubusercontent.com/5713670/217818494-3ccca0eb-0658-49fd-8e3c-3a77fdabe542.png">

**Comment by TAKANOME-DEV** [comment]
@bdougie is it necessary to add a red asterisk at the top right hand of the label?
