### ISSUE TITLE
feature: Delete options for created pages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#853]
Delete exist in the API for insights pages. We should add that to the UI.

related https://github.com/open-sauced/insights/issues/840 - @getaheaddev could use your help on this. But this is ready to dev now, we can update the design later.

## Solution
- Only the owner can delete. The delete link should only show for them, similar to the edit button. 
- The X should be replaced with a trashcan

<img width="1324" alt="Screen Shot 2023-02-09 at 4 56 47 AM" src="https://user-images.githubusercontent.com/5713670/217819302-668a90ee-150c-46a6-86bb-c2ca1990a30e.png">

<img width="1406" alt="Screen Shot 2023-02-09 at 4 58 59 AM" src="https://user-images.githubusercontent.com/5713670/217819608-8daaa13c-2cf4-4349-b70b-ebaddd592591.png">

**Comment by enaughton** [comment]
What Page or Route is this screenshot from? Just trying to get familiar with the repo.

**Comment by fmerian** [comment]
> What Page or Route is this screenshot from? Just trying to get familiar with the repo.

@enaughton when logged in, you should see it on https://insights.opensauced.pizza/hub/insights

**Comment by getaheaddev** [comment]
I can do this today

**Comment by bdougie** [comment]
This was designed here https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/Product-Flows?node-id=7%3A234&t=071F6GX8F1nrSnLi-0

![image](https://user-images.githubusercontent.com/5713670/221377000-1839ab20-a808-449d-a550-fdfd2e8d44ef.png)

**Comment by brandonroberts** [comment]
The API is ready for this also

https://beta.api.opensauced.pizza/#/User%20Highlights%20service/deleteHighlightForUser
