### ISSUE TITLE
feature: Add pagination to the user insights page list

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#856]
Increased the limit to 35 insight pages for now in https://github.com/open-sauced/insights/pull/841. We'll need another issue to add pagination to the user insights page list

_Originally posted by @brandonroberts in https://github.com/open-sauced/insights/issues/840#issuecomment-1422942376_

## Problem

Adding the 36th insights page will not show. This page needs pagination. 
    
## Solution           
<img width="1496" alt="Screen Shot 2023-02-09 at 5 09 38 AM" src="https://user-images.githubusercontent.com/5713670/217821676-c4131046-991d-40d8-a88a-4e8016cf5dcc.png">

We can use the existing pagination component.

<img width="1356" alt="Screen Shot 2023-02-09 at 5 10 25 AM" src="https://user-images.githubusercontent.com/5713670/217821876-ebb39824-6500-4382-ac21-ac5a9ecf05fd.png">

**Comment by TAKANOME-DEV** [comment]
@brandonroberts I'm only getting 7 insights pages instead of 10 (the limit)

![Screenshot from 2023-02-12 14-33-19](https://user-images.githubusercontent.com/79809121/218317294-b4bbd83a-377e-4db1-9ba9-88e7dd844c83.png)
