### ISSUE TITLE
Bug: resetting an input is not working as expected

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#858]
### Describe the bug

When you fill an input and reset it using the `red X` button and focus on another input, the cleared value comes back (it will make sense after watching the loom below)
> **Note** I only tested it in `hub/insights/new` page
>
https://www.loom.com/share/d9f56da22fe64c828527e14cb4bd868d

### Steps to reproduce

1. Go to insights.opensauced.pizza
2. Create a new insight page
3. Add a page name, reset it with the close button and focus the add repo input
4. Notice some weird things happening

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox, Other (add additional context)

### Environment

Production, Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Nasty bug, marked high prio :D

**Comment by TAKANOME-DEV** [comment]
@Deadreyo do you think that the `innerRef` prop you added in #838 will also fix this issue?

Right now, the input is reset using `useRef`. Since the component won't rerender, the state is not completely reset to an empty value.

**Comment by Deadreyo** [comment]
> @Deadreyo do you think that the `innerRef` prop you added in #838 will also fix this issue?
> 
> Right now, the input is reset using `useRef`. Since the component won't rerender, the state is not completely reset to an empty value.

Not related to the refs.
If you track the `name` state in InsightPage component, you will find that it does not reset on clicking the X, meaning that the logic that resets the text doesn't send an event to the component to clear the state.
What you need to do is make clicking the X in TextInput component also clear the state of the parent component.

**Comment by TAKANOME-DEV** [comment]
> What you need to do is make clicking the X in TextInput component also clear the state of the parent component.
>
Yeah, that's exactly what I did. I saw some refs you are using in `838` and wanted to check if that would somehow solve the issue before I edit `user-settings-page` and open a pr. 

Thanks :+1:
