### ISSUE TITLE
Bug: data inconsistency

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#865]
### Type of feature

🍕 Feature

### Current behavior

User @BaseMax - https://insights.opensauced.pizza/user/BaseMax reported some data inconsistency. Though it is not documented publically, we are undergoing some infrastructure changes. There will be inconsistencies until that is completed. 

Opening this issue as a way to track if these issues are fixed.

- [ ] Name is empty in API https://api.opensauced.pizza/v1/users/BaseMax
- [ ] Languages are empty despite there being contributions. 

## Name in API
 https://api.opensauced.pizza/v1/users/BaseMax
 
```
bio:""
company:""
created_at:"2022-05-20T08:42:16.619Z"
display_email:false
display_local_time:false
id:"2658040"
interests:"javascript"
is_onboarded:false
is_open_sauced_member:true
is_private:true
is_waitlisted:false
location:""
login:"BaseMax"
name:""
open_issues:"2"
receive_collaboration:false
role:10
timezone:"UTC+1"
twitter_username:""
updated_at:"2022-05-20T08:42:16.619Z"
```

## Languages
![image](https://user-images.githubusercontent.com/5713670/218252743-6e361d42-4c12-46b6-a04a-f2d43d5d93dd.png)

### Suggested solution

@Deadreyo the first issue should be fixed with https://github.com/open-sauced/insights/pull/838
@0-vortex we can use this profile to test out the indexer when it goes live in production with data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by BaseMax** [comment]
Hi friends, I am just excited to check the new website of open sauced. it's perfect and beautiful. Thanks, Brian for forwarding my reports here.

If I can do anything, let me know. I will try to do another check on the website in the coming week.

❤️ Open Source

**Comment by 0-vortex** [comment]
> Hi friends, I am just excited to check the new website of open sauced. it's perfect and beautiful. Thanks, Brian for forwarding my reports here.
> 
> Happy to meet you Teodor again. @0-vortex If I can do anything, let me know. I will try to do another check on the website in the coming week.
> 
> ❤️ Open Source

Hey, the pleasure is all mine, feel free to literally pick whatever, my biggest woe is `any` usage, however that doesn't really solve any practical issues :<

Ping me or the triage team if you hit any road-blocks <3

**Comment by 0-vortex** [comment]
Some noteworthy updates on this:

With the social graph endpoint we now have the ability to backfill a user's top 100 repositories, backfill them and aggregate the same coding languages github used to display on the profile.

We have a pending indexer pull request optimisation then we can get this data in the API publicly - currently implementing a call to the social graph generator in the user settings page, whenever a user vitis the settings page, if the social cards needs updating (3 day cache limitation right now), we will update the user basic information, top 100 repositories and contributed languages (from push access OR pull requests).

Just to make sure this is not misunderstood, this update happens only when a user visits the settings page to get their social badge copy paste code, from our server side indexing and through our etl indexer PATs. Any normal user viewing the shareable insight card picture will not trigger this call.

A small improvement to this in the settings page would be a checkbox to first "enable social cards" and a users table toggle similar to the private/public email checkbox so we don't generate any social cards for users that don't want to. Another way we can do this is if we start off like GitHub and enable it for everyone, let users opt out of it via the same checkbox.

We have not managed to document this yet but @brandonroberts is aware of the latest capabilities. Will open a pull request in insights demonstrating the social card sharing concept soon! 🔥🍕

Users should all get updated regularly (1-3 days tops) once that and updated indexer is live.

**Comment by takanome-dev** [comment]
Posting an update on this. The name is now correctly returned by the API and the languages
```json5
{
  "id": 2658040,
  "login": "BaseMax",
  "name": "Max Base",
  "followers": 5258,
  "following": 2,
  "timezone": "UTC+1",
  "languages": {},
  /* ...rest */
}
```
![basemax-issue](https://github.com/open-sauced/insights/assets/79809121/a30e8f66-491f-4ec6-a195-934a051dc116)

Not sure why there is no contribution data :eyes: 
cc @brandonroberts

**Comment by BaseMax** [comment]
Hey Hadji, I hope you are well. Just a quick reply here. sorry here is late
and I am at phone. I am not sure how that chart works. This show only my
personal PR? Or merging PR? For example reviewing this one:
https://github.com/BaseMax/GooglePlayWebServiceAPI/pull/32

**Comment by BaseMax** [comment]
https://api.opensauced.pizza/v1/users/BaseMax/prs?limit=15&range=90

Seems working, So it should be okay.
It seems this route only returns a list of PRs made by yourself. It's not about reviewing but I think it's not a good solution to show because most maintainers do not work on other projects.

Cheers

**Comment by BaseMax** [comment]
**New Update:**
It seems there is a problem because this route does not show anything, While I am sure I have at least one merged PR that I made this month.

https://api.opensauced.pizza/v1/users/BaseMax/prs?limit=15&range=30

**Comment by takanome-dev** [comment]
> It seems this route only returns a list of PRs made by yourself. 

Yeah, that's right

> It's not about reviewing but I think it's not a good solution to show because most maintainers do not work on other projects.
>
You have a point there, opened a feature request [here](https://github.com/open-sauced/insights/issues/1272)

**Comment by takanome-dev** [comment]
> **New Update:** It seems there is a problem because this route does not show anything, While I am sure I have at least one merged PR that I made this month.
> 
> https://api.opensauced.pizza/v1/users/BaseMax/prs?limit=15&range=30

This may be a bug, will open an issue in [api.opensauced.pizza](https://github.com/open-sauced/api.opensauced.pizza/)

**Comment by takanome-dev** [comment]
Hum, this route seems to be working :thinking: 
https://api.opensauced.pizza/v1/users/takanome-dev/prs?limit=15&range=30

**Comment by bdougie** [comment]
We did some work to the DB and switch how imported info. This is fixed

**Comment by BaseMax** [comment]
Nice work Brian, thanks.
