### ISSUE TITLE
Feature: add user profile linkedin fields

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#876]
### Type of feature

🍕 Feature

### Current behavior

<img width="422" alt="Screen Shot 2023-02-14 at 4 55 01 PM" src="https://user-images.githubusercontent.com/5713670/218916585-7a5897a5-5989-4e3a-96f8-6018b9a761b8.png">

### Suggested solution

Need an API connection to make this happened, but his should be straight forward.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
In addition to LinkedIn, we should have a "GitHub Sponsors" field.

**Comment by brandonroberts** [comment]
@bdougie do we want to leave the full URLs?

![image](https://user-images.githubusercontent.com/42211/220979931-a551489e-1814-44e1-9b1c-599c2c8d243f.png)

![image](https://user-images.githubusercontent.com/42211/220980149-6625dcb1-9f98-49bf-8642-0cdf5ea656b1.png)

**Comment by bdougie** [comment]
short code is fine, though I am not sure everyone has a short name on linkedin.

**Comment by bdougie** [comment]
> Ok, I'll leave LinkedIn as the full URL and shorten the GitHub Sponsors one

Nevermind, just checked and everyone has one.

**Comment by brandonroberts** [comment]
👍
