### ISSUE TITLE
feat: Make highlights editable

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#886]
As a user I should be able to edit a highlight. 

![Screen Shot 2023-02-20 at 9 35 07 AM](https://user-images.githubusercontent.com/5713670/220170961-296a09d8-49e4-4754-a821-93c989f22d90.png)

https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5876%3A7583&t=KG4cKsqY6B6hvToP-0

**Comment by OgDev-01** [comment]
Hey @bdougie, Any idea what the UI flow is going to look like?

**Comment by bdougie** [comment]
Probably go with a modal/pop-up since we will need that for the collaboration feature. Instead of "collaborate with nate," it can be "Edit your highlight"

Same elements as the input. 

![image](https://user-images.githubusercontent.com/5713670/220196755-dcb34444-446a-4867-b90e-17ceb5d5de8e.png)
