### ISSUE TITLE
feat: Share after update - Social

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#891]
After a user connects their GitHub, they should be encourage to share their profile on LinkedIn and Twitter. 

![Image](https://user-images.githubusercontent.com/5713670/220212012-e7a5f543-64a9-4245-ade0-2323685ffb67.png)

**Comment by 0-vortex** [comment]
Think you got the wrong screenshot here :D

**Comment by getaheaddev** [comment]
Just posted a campsite about this

[[Campsite Post](https://app.campsite.design/opensauced/posts/kxzxjq2yo61u)]

[[Share after highlight post](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=475%3A4318&t=IggKgB5nBNUMShqz-1)]

**Comment by bdougie** [comment]
https://github.com/open-sauced/insights/issues/1176
