### ISSUE TITLE
Bug: Update page is always disabled

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#892]
### Describe the bug

<img width="420" alt="Screen Shot 2023-02-21 at 4 55 03 AM" src="https://user-images.githubusercontent.com/5713670/220350352-c0dc9771-4266-427e-8fa0-0247b139997d.png">

cc @TAKANOME-DEV 

### Steps to reproduce

When trying to edit an insights pages, I am noticing that the update page button is always disabled 

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Didn't test it for the update :sweat:

**Comment by bdougie** [comment]
Would you be able to send a fix. Otherwise, I plan on streaming to day and can fix it later.

**Comment by TAKANOME-DEV** [comment]
> Would you be able to send a fix.
>
Sure, done :heavy_check_mark:
