### ISSUE TITLE
Feature: Limit char count in Highlights to 500 chars

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#899]
### Type of feature

🍕 Feature

### Current behavior

<img width="831" alt="Screen Shot 2023-02-22 at 7 47 17 AM" src="https://user-images.githubusercontent.com/5713670/220677100-6b6e25b1-9924-4e20-a08f-5f0c658a4939.png">

### Suggested solution

Show an error message suggestion the limit is 500 chars.

@getaheaddev in case you have time to design something in the box

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
There is now a design for a 500 character limit on figma

Campsite:
https://app.campsite.design/opensauced/posts/51ui13yun4vx

Figma:
https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=7247%3A10279&t=fJQepiZ2In4jJ64I-1
