### ISSUE TITLE
Feature: Add global container class to tailwindcss to manage the maxwidth of layouts

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#900]
### Type of feature

🍕 Feature

### Current behavior

Our current infrastructure requires us to manually define paddings and max width to layouts.

Ex: The image below is a screenshot of the user profile page on large monitor screens
![image](https://user-images.githubusercontent.com/62995161/220707789-5989868f-f821-41c4-b90e-170a17bd5fb5.png)

The layout will keep growing on larger screens with a fixed padding which might later result in breaking some components that rely's on thier root wrapper for width

### Suggested solution

My suggestion is to have a pre-defined container class in the tailwind config, to set max-width on all responsive breakpoints to certain areas on pages that needs not to grow with the user's screen width like the user profile body... Example implementation can be found [here](https://github.com/OgDev-01/ogdev/blob/main/tailwind.config.js ) on the highlighted path of the below screenshot

![image](https://user-images.githubusercontent.com/62995161/220710417-0267bee3-0251-4674-b67b-56ae05d7b4ed.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
screenshot is setting different breakpoints and disabling padding, reckon the issue is supposed to do the opposite 🍕

**Comment by TAKANOME-DEV** [comment]
IMO, we can have some predefined button variants built with tailwind + radix, and they can be overridden easily. Checkout https://ui.shadcn.com/docs/primitives/button

**Comment by 0-vortex** [comment]
> IMO, we can have some predefined button variants built with tailwind + radix, and they can be overridden easily. Checkout https://ui.shadcn.com/docs/primitives/button

No, that is loading a 3rd ui library ... tailwind can already do that for us.

**Comment by TAKANOME-DEV** [comment]
> No, that is loading a 3rd ui library...
>
That's not another library. It's some re-usable components built using Radix UI and Tailwind CSS.
> tailwind can already do that for us.
>
Sure, we can only use tailwind for that :+1:

**Comment by 0-vortex** [comment]
> > No, that is loading a 3rd ui library...
> 
> >
> 
> That's not another library. It's some re-usable components built using Radix UI and Tailwind CSS.
> 
> > tailwind can already do that for us.
> 
> >
> 
> Sure, we can only use tailwind for that :+1: 

It's a very opinionated, experimental library. There has been no discussion about this technology nor has it been vetted for production.

It's solving part of the problem and adding new ones :<
