### ISSUE TITLE
Feature: Insights need custom 404 Not-found page

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#910]
### Type of feature

🍕 Feature

### Current behavior

Our current authenticated routes are yet to redirect unauthenticated users to a 404 not found page, and a part of the reason is we don't have a custom 404-page design...  

### Suggested solution

@getaheaddev can sketch something out that can be reused across the application to handle authenticated routes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
We can use this https://github.com/open-sauced/insights/blob/beta/img/404-image.svg

cc @getaheaddev

**Comment by bdougie** [comment]
We have a 404 page. @foxyblocks can you wrap this into the work you are already doing with the devcards?

I believe the page behind could potentially scroll with profiles, and change when clicked. 

[Figma](https://www.figma.com/proto/768ifqOGWrsRN29Igkc4ip/User-Flows?page-id=403%3A5243&type=design&node-id=1468-6969&viewport=2761%2C590%2C0.25&scaling=min-zoom&starting-point-node-id=1468%3A6969)

![image](https://github.com/open-sauced/insights/assets/5713670/c0a8b4d1-0243-46aa-ab28-f05a3714cbc5)

**Comment by foxyblocks** [comment]
@bdougie any opinion on how we get the list of profiles? We can use the same list as the devcards page, but we'll probably want more of them if we're going to add scrolling.

**Comment by bdougie** [comment]
Ideally we'd want to only show folks that have contributions. Today we can grab 30 folks from he PR list.

https://api.opensauced.pizza/v1/prs/list?page=1&limit=10&range=30

That json blob has authorlogin, which is the github users. 

@OgDev-01 helped with the topUser endpoint, I believe. Perhaps we add a top user option for type in the future. I see us wanting the top top users based on types highlights, contributions, etc.

**Comment by foxyblocks** [comment]
Alright, next.js statically generates the 404 page so we'll load and render these client side. The initial plan is to use swr and infinite scroll to load the profiles. I'll start by making an initial dummy page to test the animation transition effects that we want.

> https://api.opensauced.pizza/v1/prs/list?page=1&limit=10&range=30
@bdougie @OgDev-01  what does the `range` parameter indicate here? I would expect `limit` parameter to indicate the number of results
