### ISSUE TITLE
bug: topic contributor data is causing errors

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#911]
> @payn33 would be able to create a highlight about your work on this fix?
> 
> https://opensauced.pizza/blog/social-coding-is-back

hello @bdougie  I keep getting an error when I try to view my profile

https://user-images.githubusercontent.com/66219025/221282121-d03face7-fb1e-4248-b6a2-b71d12f875a0.mp4

did a bit of debugging and found that the data structure for my contributor data used in the `useTopicContributorCommits` hook is different from what is expected(no idea why), hence the error.
![image](https://user-images.githubusercontent.com/66219025/221285550-ff20e337-0abc-4c46-9e29-19ac28d4a738.png)
the picture above is the contributor data returned for your profile(above) containing nested data and meta object, and mine (below)  an array
![usecontributorcommithook](https://user-images.githubusercontent.com/66219025/221286182-9465ee62-086c-447c-9ca4-70e88efb26bf.png)
a snippet from the `usecontributorcommithook` that expects a nested data object

_Originally posted by @payn33 in https://github.com/open-sauced/insights/pull/834#issuecomment-1444439599_

**Comment by bdougie** [comment]
@payn33, I believe this has been fixed with https://github.com/open-sauced/insights/pull/959

**Comment by bdougie** [comment]
Thanks for the triaging @takanome-dev

**Comment by takanome-dev** [comment]
My pleasure :slightly_smiling_face:
