### ISSUE TITLE
Feature: Loading indicator on Insight Pages

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#917]
### Type of feature

🍕 Feature

### Current behavior

When a user clicks on an insights page, there are a few-second delay and no indicator that the page is fetching the data. 

 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5713670/221747649-d9d4f4ac-faf5-4eda-8156-cf5c1928ae5b.gif)

### Suggested solution

Add a loading indicator or spinner to the page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Isn't this issue the same as https://github.com/open-sauced/insights/issues/903?

**Comment by Deadreyo** [comment]
> Isn't this issue the same as #903?

Nope. The other issue requires loading indicator inside specific components, this one requires a loading indicator for the whole page transition.
