### ISSUE TITLE
Bug: Default profile bio should not show.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#922]
### Describe the bug

I find it weird we got this far with user having a passion for music and coding. 

![Screen Shot 2023-02-28 at 9 35 42 AM](https://user-images.githubusercontent.com/5713670/221933420-946d3002-dfd4-49aa-a15d-f47747c1e1dc.png)

### Steps to reproduce

View this profile. https://deploy-preview-920--oss-insights.netlify.app/user/meeroslav

If they do not have a profile we should the below bio instead of this generic bio.

```
[user] has connect their GitHub, but has not added a bio.
``` 

The best solution would be adding the bio from GitHub as the default.

![Screen Shot 2023-02-28 at 9 38 03 AM](https://user-images.githubusercontent.com/5713670/221933538-144e5553-9420-4ae9-a1f2-5695086d8899.png)

### Affected services

insights.opensauced.pizza

### Additional context

The default timezone is also UTC+1 but it should not show if it is not submitted.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by shamimbinnur** [comment]
Currently, https://api.opensauced.pizza/v1/users/shamimbinnur is only returning the user's insight bio. Could we implement backend logic to have it return the GitHub bio by default if the user has not updated their insight bio? Or could we have a different field for the user's GithHub bio?

CC @bdougie @brandonroberts

**Comment by bdougie** [comment]
Yes, there is a github service in our api to do that. Did you want to take this on?

**Comment by shamimbinnur** [comment]
@bdougie I just wanted to clarify that this issue can be solved from the backend. However, I am not willing to handle any backend issues at this moment. Instead, I can replace the current `default bio` with the message, `[user] has connected their GitHub, but has not added a bio` from the front end.

**Comment by bdougie** [comment]
That would be perfect.

**Comment by 0-vortex** [comment]
> @bdougie I just wanted to clarify that this issue can be solved from the backend. However, I am not willing to handle any backend issues at this moment. Instead, I can replace the current `default bio` with the message, `[user] has connected their GitHub, but has not added a bio` from the front end.

Don't agree on the backend idea, but totally dig the frontend solution! 🍕

**Comment by brandonroberts** [comment]
The frontend solution works for now. It looks like the `bio` information isn't provided as part of the user data when initially created from the session
