### ISSUE TITLE
Bug: local times and timezones do not seem to be correct

### ISSUE THREAD

**Issue by TAKANOME-DEV** [open-sauced/insights#923]
### Describe the bug

The timezones and/or dates are not working as expected

![dates-incorrect-1m](https://user-images.githubusercontent.com/79809121/221934359-baf84a32-2ebd-4ed5-b55c-9064aed4360d.png)
![dates-incorrect-2m](https://user-images.githubusercontent.com/79809121/221934387-e1441ea5-2fe2-4ef5-a78e-b2d417bc45d1.png)

### Steps to reproduce

1. Visit a user profile page - https://insights.opensauced.pizza/user/bdougie
2. Note the displayed time and timezone
3. Visit the same user profile on github - https://github.com/bdougie
4. Notice that the dates and timezones are different

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Firefox

### Environment

Production

### Additional context

Maybe this should be tracked in https://github.com/open-sauced/insights/issues/865

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
GitHub is not correct either. 

<img width="797" alt="Screenshot 2023-03-01 at 12 49 10" src="https://user-images.githubusercontent.com/237133/222118458-1caf1539-3922-451d-bde5-0c5044f08660.png">

Letting the users set a timezone in our backend enables us to workaround the relative time difference in browser environment, similar to GitHub, but with more precise user information. You should check your local time difference to @bdougie naturally, without checking against the GitHub profile display, that would enable us to fix the potential bug you found! 🍕

**Comment by TAKANOME-DEV** [comment]
> GitHub is not correct either.
> 
You're right, it's not correct :sweat_smile: 
> 
> You should check your local time difference to @bdougie naturally, without checking against the GitHub profile display, that would enable us to fix the potential bug you found! pizza
>
Yeah the difference is `8h`. So the timezone in the screenshot above is correct even though the local time is not 100% correct.

Update: I tested it on beta for Brian, Brandon and Sunday and it's is correct. So I assume it will be for others :pizza:

**Comment by jessehouwing** [comment]
I'm still seeing a `+1` offset too much for Amsterdam. In summer we're at +2, but in winter at +1, I'm guessing a summer/winter time issue...
![image](https://github.com/open-sauced/app/assets/4173387/16043275-6622-4ea4-b5cc-464209bf336e)
![image](https://github.com/open-sauced/app/assets/4173387/3084318b-eb51-4143-98f3-0cd094ee2032)
![image](https://github.com/open-sauced/app/assets/4173387/68b5244d-f941-41c0-b913-405504d643a7)
