### ISSUE TITLE
Bug: Localtime settings doesn't do anything 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#946]
### Describe the bug

<img width="459" alt="Screen Shot 2023-03-03 at 3 37 54 PM" src="https://user-images.githubusercontent.com/5713670/222855150-fa4c1a58-4cd7-46dd-b18c-e8770f116b2a.png">

reported by @styfle

### Steps to reproduce

Users expect time to be removed from the profile. We should do that :)

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
@bdougie  are we taking off the time zone select too?

**Comment by bdougie** [comment]
Just remove local time

**Comment by bdougie** [comment]
I read this incorrect from the beginning. In addition to local time, the feature should remove the timezone at the top.
