### ISSUE TITLE
Feature: Determine the timezone based on the browser.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#948]
### Type of feature

🍕 Feature

### Current behavior

reported on [Twitter by JayCooperBell](https://twitter.com/JayCooperBell/status/1632036192601669634).

> Hey 
[@saucedopen](https://twitter.com/saucedopen)
, just signed up, couple pieces of feedback, you should be able to determine my timezone from my browser and auto fill, PST and PDT are the same timezone (just depends on time of year), your form field regexes are case sensitive but phones capitalize first letter.

### Suggested solution

This is a nice to have. The regex thing is something to we should look into as well. 

### Additional context

We should also look into getting their contributions indexed when we go live on monday https://insights.opensauced.pizza/user/yharaskrik/contributions

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @bdougie, are we still working on this?

**Comment by bdougie** [comment]
yes, low priority. But should be an easy update.

https://www.tutorialspoint.com/how-to-detect-user-timezone-in-javascript#:~:text=To%20get%20the%20timezone%2C%20use,difference%20returned%20is%20in%20minutes.

**Comment by bdougie** [comment]
Can you unset it locally and test if yours is the default when you open it up.

If it works, we can close the issue.
