### ISSUE TITLE
bug: Make PR link clickable

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#949]
### Type of feature

🍕 Feature

### Current behavior
after clicking the edit button and closing the modal form
the link to the PR becomes unclickable 
**here's a screenshot**
![image](https://user-images.githubusercontent.com/72051159/222934842-982b7df1-1e33-4597-bc08-23eabcfee2a0.png)

### Additional context
this works after refreshing the page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
i guess this should be a bug issue

**Comment by bdougie** [comment]
Updated. Would you like to work on this @dev-phantom?

**Comment by dev-phantom** [comment]
> Updated. Would you like to work on this @dev-phantom?

would have love to sir 
but the server stops anytime i try opening it 
i've not been able to resolve this ever since

**Comment by bdougie** [comment]
> > Updated. Would you like to work on this @dev-phantom?
> 
> 
> 
> would have love to sir 
> 
> but the server stops anytime i try opening it 
> 
> i've not been able to resolve this ever since

Wow still the same issue from discord?

**Comment by dev-phantom** [comment]
> > > Updated. Would you like to work on this @dev-phantom?
> > 
> > 
> > would have love to sir
> > but the server stops anytime i try opening it
> > i've not been able to resolve this ever since
> 
> Wow still the same issue from discord?
> 
> Do you have access to GitHub Codespaces?

yes sir
