### ISSUE TITLE
Bug: new highlight does not show till after refresh

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/insights#950]
### Describe the bug

after successfully adding a new highlight the new highlight does not get updated until after a refresh

### Steps to reproduce

1. go to user profile 
2. add highlight
3. see error

### Affected services

insights.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
@Deadreyo FYI,  this has been fixed on #957
