### ISSUE TITLE
Feature: Loading indicator in Feed when filtering

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/insights#968]
### Type of feature

🍕 Feature

### Current behavior

When you filter, the screen becomes blank for a moment till the items are loaded. Can get worse on slower connections
![image](https://user-images.githubusercontent.com/52013393/223492707-7f25a6eb-dd6e-4df9-875b-bd37878f41a9.png)

### Suggested solution

Add a skeleton loading indicator while loading.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Yeah, definitely. And also when paginating the highlights

**Comment by takanome-dev** [comment]
Fixed
