### ISSUE TITLE
Feature: Add teams UI for the Design System 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#974]
### Type of feature

🍕 Feature

### Current behavior

The Add Insights Page will need Teams associated with it. For now we just need the component add to the design system. 

### Suggested solution

Use the figma to see the other elements

[Figma - add team members](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/Product-Flows?node-id=125-783&t=tLrfw11H87eqZ5Jy-0)
[Prototype](https://www.figma.com/proto/768ifqOGWrsRN29Igkc4ip/Product-Flows?page-id=7%3A234&node-id=271-832&viewport=-1733%2C4896%2C0.67&scaling=min-zoom&starting-point-node-id=271%3A832)

### Additional context

<img width="431" alt="Screen Shot 2023-03-08 at 6 06 12 AM" src="https://user-images.githubusercontent.com/5713670/223739671-3704a8c5-ec08-4b4f-874c-996aad0cc182.png">
<img width="517" alt="Screen Shot 2023-03-08 at 6 29 57 AM" src="https://user-images.githubusercontent.com/5713670/223739881-2c98b70b-1ca0-4e37-91fb-a0116db6c600.png">
<img width="784" alt="Screen Shot 2023-03-08 at 6 38 41 AM" src="https://user-images.githubusercontent.com/5713670/223742209-d2123346-926c-4e9b-94d8-a90e0d8a1702.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Deadreyo** [comment]
@bdougie @getaheaddev 
We have another variant of the selector already made: 
![image](https://user-images.githubusercontent.com/52013393/224404358-05339dc2-42e3-4629-bd45-581edb933304.png)

So we will leave it and make another one with this exact styling correct?

**Comment by bdougie** [comment]
Make a variation
