### ISSUE TITLE
Feature: Add pagination to highlights in feeds and user profile

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#978]
### Type of feature

🍕 Feature

### Current behavior

Current highlights fetch hooks has no pagination.

### Suggested solution

Add pagination to the feeds and user profile highlights posts list similar to what we have in the repositories and contributors page

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/62995161/223782962-f8e5f7bf-e441-4e7b-bc7c-80591086383f.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Yes, please 🙇🏾
