### ISSUE TITLE
Feature: User Error handling service

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#980]
### Type of feature

🍕 Feature

### Current behavior

@brandonroberts can you evaluate to error handling service when you have a moment. I would love to stop supporting users in my Twitter DMs :)

### Suggested solution

Options I would love to explore

- [Replay](https://www.replay.io/) - I know the team and would love to see if it is a fit for us.
- [Sentry](https://sentry.io/) - This is the last thing I used
- Anything else?

### Additional context

Free is nice but we have budget to pay per seat if needed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@brandonroberts can we prioritize this this week? I am consistently getting an error in production.

https://github.com/open-sauced/insights/issues/1119

**Comment by brandonroberts** [comment]
Yes, will get something in place
