### ISSUE TITLE
Feature: Shareable Baseball Card

### ISSUE THREAD

**Issue by bdougie** [open-sauced/insights#981]
This is a new social design

https://app.campsite.design/opensauced/posts/2y3i98mybi11/preview/njdbe1aa50m1

**Comment by bdougie** [comment]
Blocked on #687

**Comment by getaheaddev** [comment]
Do you feel like this is ready to go now @bdougie? Did you move this?

**Comment by bdougie** [comment]
Yes please. Going to have a call with the dev on Monday.

**Comment by getaheaddev** [comment]
Here they are!

[[Figma: DevCards](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=349%3A3298&t=B0fmUuiTTS4HUVTm-1)]
