### ISSUE TITLE
Bug: highlight update input body overlaps words

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/insights#984]
### Describe the bug

![image](https://user-images.githubusercontent.com/62995161/224084800-6d48a33a-a3f3-48a8-af83-176ee78aaf13.png)

### Steps to reproduce

1. connect account
2. go to user profile page
3. create highlight with at least 300 words

### Affected services

insights.opensauced.pizza

### Environment

Production, Development

### Additional context

A recommended fix will be to reduce the margin between the wordcount and the input field
_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@OgDev-01 we also need to capitalize `Title` and `Body`

**Comment by OgDev-01** [comment]
Noted
